fix: better handling of flags

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -25,8 +25,8 @@ export AMBOSO_LVL_REC=$(($AMBOSO_LVL_REC+1))
 function echo_current_tags {
   echo -e "[DEBUG]    Current flags:\n"
   echo -en "           [MODE]    -"
-  [[ $test_mode_flag -gt 0 ]] && echo -n "t"
-  [[ $big_test_mode_flag -gt 0 ]] && echo -n "T"
+  [[ $small_test_mode_flag -gt 0 ]] && echo -n "t"
+  [[ $test_mode_flag -gt 0 ]] && echo -n "T"
   [[ $git_mode_flag -gt 0 ]] && echo -n "g"
   [[ $base_mode_flag -gt 0 ]] && echo -n "B"
   echo ""
@@ -259,7 +259,7 @@ function echo_othermode_tags {
     done
   }
   fi
-  echo "" >&2
+  echo ""
 }
 
 function echo_supported_tags {
@@ -273,7 +273,7 @@ function echo_supported_tags {
     echo -en "    \033[1;32m${supported_versions[i]}\e[0m"
   }
   done
-  echo "" >&2
+  echo ""
 }
 
 function echo_options {
@@ -282,11 +282,9 @@ function echo_options {
   echo -e "                Uses full source builds. Not recommended.\n"
   echo -e "        -g        git mode\n"
   echo -e "                Uses git checkouts of supported tags. Enabled by default.\n"
-  echo -e "        -t        test mode\n"
-  echo -e "                Tries all defined tests.\n"
-  echo -e "    [OPERATIONS]:\n"
   echo -e "        -T        test mode\n"
   echo -e "                Tries the queried test.\n"
+  echo -e "    [OPERATIONS]:\n"
   echo -e "        -b        build\n"
   echo -e "                Tries building the binary if it's not available.\n"
   echo -e "        -r        run\n"
@@ -422,7 +420,7 @@ makefile_version=""
 git_mode_flag=1 #By default we run in git mode
 base_mode_flag=0
 test_mode_flag=0
-big_test_mode_flag=0
+small_test_mode_flag=0
 test_info_was_set=0
 testdir_flag=0
 kazoj_dir=""
@@ -472,10 +470,10 @@ while getopts "M:S:E:D:K:BgVbpHhrivdlLtTq" opt; do
       git_mode_flag=1
       ;;
     t )
-      test_mode_flag=1
+      small_test_mode_flag=1
       ;;
     T )
-      big_test_mode_flag=1
+      test_mode_flag=1
       ;;
     V )
       verbose_flag=1
@@ -513,8 +511,19 @@ while getopts "M:S:E:D:K:BgVbpHhrivdlLtTq" opt; do
 tot_opts=$OPTIND
 done
 
-[[ $AMBOSO_LVL_REC -gt 1 ]] && echo -e "[AMBOSO]    recursive call , depth $((${AMBOSO_LVL_REC}-1))\n\n        args: (\"$@\")" >&2
-echo_current_tags >&2
+#Won't print call info for top level calls
+if [[ ${AMBOSO_LVL_REC} -gt 1 ]] ; then {
+#and 1+ nested test calls ( with -T, from -t calling -T)
+  echo -e "\033[1;34m[AMBOSO]    Recursive call , depth: ( $((${AMBOSO_LVL_REC}-1)) )\e[0m"
+  if [[ $AMBOSO_LVL_REC -lt 2 ]] ; then {
+    echo -e "\\n\n        args: (\"$@\")" >&2
+    echo_current_tags >&2
+  } elif [[ $AMBOSO_LVL_REC -gt 2 ]] ; then {
+    echo -e "[AMBOSO]    deep recursion, are you calling \"$prog_name\" in a test? ;)"
+  }
+  fi
+}
+fi
 
 if [[ $version_flag -gt 1 ]] ; then {
   echo_amboso_version_short
@@ -526,7 +535,7 @@ if [[ $version_flag -gt 1 ]] ; then {
 fi
 
 #We check again if testmode was requested, and reset the other mode flags.
-# -t always overrides -g and -B
+# -T always overrides -g and -B
 if [[ $test_mode_flag -gt 0 ]] ; then {
   git_mode_flag=0
   base_mode_flag=0
@@ -557,17 +566,27 @@ fi
 
 #Check if we are printing help info and exiting early
 if [[ $smallhelp_flag -gt 0 ]]; then {
-      "$prog_name" -H -D "$milestones_dir" | less
-      exit 0
+  if [[ $AMBOSO_LVL_REC -gt 1 ]] ; then {
+    echo -e "[AMBOSO]    can't ask for help on a recursive call, try running \"$prog_name -h\" from a shell. ( depth $((${AMBOSO_LVL_REC}-1)) )\n\n        args: (\"$@\")" >&2
+    exit 1
+  }
+  fi
+  "$prog_name" -H -D "$milestones_dir" | less
+  exit 0
 }
 fi
 #Check if we are printing Help info and exiting early
 if [[ $bighelp_flag -gt 0 ]]; then {
-      echo_amboso_version
-      set_source_info "$milestones_dir"
-      set_supported_versions "$milestones_dir"
-      usage
-      exit 0
+  if [[ $AMBOSO_LVL_REC -gt 1 ]] ; then {
+    echo -e "[AMBOSO]    can't ask for help on a recursive call, try running \"$prog_name -H\" from a shell. ( depth $((${AMBOSO_LVL_REC}-1)) )\n\n        args: (\"$@\")" >&2
+    exit 1
+  }
+  fi
+  echo_amboso_version
+  set_source_info "$milestones_dir"
+  set_supported_versions "$milestones_dir"
+  usage
+  exit 0
 }
 fi
 
@@ -582,8 +601,8 @@ set_tests_info "$kazoj_dir"
 set_supported_tests "$kazoj_dir"
 
 
-if [[ $quiet_flag -eq 0 ]]; then { #WIP
-    echo -e "\033[1;35m[VERB]    SYNCPOINT: list tag names\e[0m" >&2
+if [[ $verbose_flag -gt 0 ]]; then { #WIP
+    echo -e "\033[1;35m[VERB]    SYNCPOINT:  listing tag names\e[0m" >&2
     echo_supported_tags "$milestones_dir" >&2
     echo_tests_info "$kazoj_dir" >&2
 }
@@ -596,18 +615,18 @@ if [[ -z $kazoj_dir && $test_mode_flag -gt 0 ]] ; then {
        kazoj_dir="./kazoj"
        set_tests_info "$kazoj_dir"
        set_supported_tests "$kazoj_dir"
-       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  (AFTER SYNC)  No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m" >&2
+       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m" >&2
      } else {
-       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  (AFTER SYNC)  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
+       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
        set_source_info "$milestones_dir"
        kazoj_dir="${sources_info[3]}"
        set_tests_info "$kazoj_dir"
        set_supported_tests "$kazoj_dir"
-       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  (AFTER SYNC)  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
+       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
      }
      fi
   } else {
-     echo -e "\033[1;31m[ERROR]  (AFTER SYNC)  No -K flag on a test run, amboso version is < ($amboso_testflag_version).\n    Quitting.\e[0m" #>&2
+     echo -e "\033[1;31m[ERROR]    No -K flag on a test run, amboso version is < ($amboso_testflag_version).\n    Quitting.\e[0m" #>&2
      exit 0;
   }
   fi
@@ -673,9 +692,10 @@ fi
 
 #Check if we are doing init and we're not in test mode
 #Which means we want to build all tags
-if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
+#TODO: Why is this checked before determining if we're doing build mode or test mode?
+if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ]] ; then {
   if [[ $quiet_flag -eq 0 ]]; then { #WIP
-      echo -e "\033[1;35m[VERB]    Init mode (-t was 0): build all tags\e[0m" >&2
+      echo -e "\033[1;35m[VERB]    Init mode (no -tT): build all tags\e[0m" >&2
       echo_supported_tags "$milestones_dir" >&2
   }
   fi
@@ -689,11 +709,13 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
     #Init mode ALWAYS tries building, even if we have the binary already ATM
     #Save verbose flag
     verb=""
+    buildm=""
     gitm=""
     basem=""
     quietm=""
 
     [[ $verbose_flag -gt 0 ]] && verb="V" #Pass verbose mode
+    [[ $build_flag -gt 0 ]] && buildm="b" #Pass build mode
     [[ $base_mode_flag -gt 0 ]] && basem="B" #We make sure to pass on eventual base mode to the subcalls
     [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
     [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet flag mode to the subcalls
@@ -752,19 +774,28 @@ if [[ $delete_flag -gt 0 && $test_mode_flag -gt 0 ]] && [[ $verbose_flag -gt 0 |
 }
 fi
 
-quietm=""
-verbm=""
-[[ $quiet_flag -gt 0 ]] && quietm="q"
-[[ $verbose_flag -gt 0 ]] && verbm="V"
-
-#If we have -t and not -T, we always check all tests
+#If we have -t and not -T, we check all tests and DON'T EXIT
 #WIP
-if [[ $test_mode_flag -gt 0 && $big_test_mode_flag -eq 0 ]] ; then {
+if [[ $small_test_mode_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
+  if [[ $quiet_flag -eq 0 ]] ; then {
+    echo -e "\033[1;33m[DEBUG]    -t assert: shortcut to run \"$prog_name\" with -T"
+    echo -e "\033[1;33m[DEBUG]    will pass: ( -qvb ) to subcall, if asserted.\n"
+  }
+  fi
+  quietm=""
+  verbm=""
+  buildm=""
+  [[ $quiet_flag -gt 0 ]] && quietm="q"
+  [[ $verbose_flag -gt 0 ]] && verbm="V"
+  [[ $build_flag -gt 0 ]] && buildm="b"
+  [[ $init_flag -gt 0 ]] && buildm="b" && echo -e "\033[1;31m[DEBUG]    Recording all tests with -ti is deprecated.\n\n        Feature will be dropped in next major update.\n"
+
+
   start_t_tests=`date +%s.%N`
   for i in $(seq 0 $(($tot_tests-1))); do {
-    [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;34m[TEST]    Run:  \"$prog_name -Tt$quietm$verbm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m" >&2
+    [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;34m[TEST]    Run:  \"$prog_name -T$quietm$verbm$buildm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m" >&2
     start_t_curr_test=`date +%s.%N`
-    "$prog_name" -Tt"$quietm""$verbm" -K "$kazoj_dir" -D "$milestones_dir" "${supported_tests[$i]}"
+    "$prog_name" -T"$quietm""$verbm""$buildm" -K "$kazoj_dir" -D "$milestones_dir" "${supported_tests[$i]}"
     retcod="$?"
     end_t_curr_test=`date +%s.%N`
     runtime_curr_test=$( echo "$end_t_curr_test - $start_t_curr_test" | bc -l )
@@ -788,6 +819,9 @@ if [[ $test_mode_flag -gt 0 && $big_test_mode_flag -eq 0 ]] ; then {
   }
   fi
   echo -e "\033[0;34m[TEST]    Full testing took $display_zero$runtime_tests seconds ( $tot_tests done).\e[0m"
+} elif [[ $small_test_mode_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
+  echo -e "\033[1;31m[TEST]    Error: -t was asserted with -T. -t is a shortcut to run as -T on all tests found.\e[0m"
+  exit 1
 }
 fi
 
@@ -807,7 +841,6 @@ done
 v_pos=1
 query="${!v_pos}"
 
-    echo -e "\033[1;35m[VERB]    SYNCPOINT: shifted args, query was: ( $query ).\e[0m" >&2
 if [[ $quiet_flag -eq 0 && $verbose_flag -gt 0 ]]; then { #WIP
     echo -e "\033[1;35m[VERB]    SYNCPOINT: shifted args, query was: ( $query ).\e[0m" >&2
 }
@@ -835,10 +868,10 @@ if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 && $test_mod
 fi
 #Check if we are doing a test
 if [[ $test_mode_flag -gt 0 ]]; then {
-  if [[ $quiet_flag -eq 0 ]]; then { #WIP
-      echo -e "\033[1;35m[VERB]    Test mode (-t was on).\e[0m" >&2
+  if [[ $quiet_flag -eq 0 && $verbose_flag -gt 0 ]]; then { #WIP
+      echo -e "\033[1;35m[VERB]    Test mode (-T was on).\e[0m" >&2
+      [[ $smalltest_mode_flag -gt 0 ]] && echo -e "\033[1;35m[VERB]    (-t was on).\e[0m" >&2
       echo_tests_info "$kazoj_dir" >&2
-      [[ $big_test_mode_flag -gt 0 ]] && echo -e "\033[1;35m[VERB]    (-T was on).\e[0m" >&2
   }
   fi
   test_name=""
@@ -876,8 +909,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   fi
 
   if [[ $quiet_flag -eq 0 ]]; then { #WIP
-      echo -e "\033[0;35m[VERB]    SYNCPOINT: done matcing test query, was: ( $query ).\e[0m" >&2
-      echo -e "\033[0;35m[VERB]    expected:\n\n    type:  $test_type\n\n    name:  $test_name\n    path:  $test_path\n\e[0m" >&2
+      echo -e "\033[0;34m[TEST]    Expected:\n\n    type:  $test_type\n\n    name:  $test_name\n    path:  $test_path\n\e[0m" >&2
   }
   fi
 
@@ -974,16 +1006,15 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   escape_colorcodes_tee "$run_tmp_out" "$run_tmp_escout"
   escape_colorcodes_tee "$run_tmp_err" "$run_tmp_escerr"
   if [[ $build_flag -gt 0 ]] ; then {
-    :
     cp "$run_tmp_escout" "$relative_testpath.stdout" || echo -e "Failed replacing stdout with new file."
     cp "$run_tmp_escerr" "$relative_testpath.stderr" || echo -e "Failed replacing stderr with new file."
   } else {
-    :
+    echo -e "\033[1;33m[TEST]    Won't record, no [-b].\e[0m\n"
   }
   fi
-  rm -f "$run_tmp_out" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\n"
+  rm -f "$run_tmp_out" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\e[0m\n"
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_out".\e[0m" >&2
-  rm -f "$run_tmp_err" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\n"
+  rm -f "$run_tmp_err" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\e[0m\n"
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_err".\e[0m" >&2
   #Testing diff for escaped stdout
   ( diff "$run_tmp_escout" "$relative_testpath".stdout ) 2>/dev/null 1>&2
