feat: handle -a from main script to force global source

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -22,6 +22,12 @@ if [ "$(id -u)" -eq 0 ] ; then {
   exit 3
 }
 fi
+force_global_source=0
+if [[ "$1" == "-a" ]] ; then {
+    force_global_source=1
+    shift
+}
+fi
 # Set recursion env var if not exists
 prog_name="$(readlink -f "$0")"
 kernel_name="$(uname -s)"
@@ -36,9 +42,30 @@ verbose_flag=0
 tell_uname_flag=0
 quiet_flag=0
 try_default=0
+std_amboso_global_path="/usr/local/bin/amboso_fn.sh"
 #Function to try sourcing amboso_fn.sh
 source_amboso_api() {
-  if [ "$(basename "$(pwd)")" = "amboso" ] ; then {
+  force_global_source="${1:-0}"
+  local source_res=1
+  if [[ "$force_global_source" -eq 1 ]] ; then {
+    if [ -f "/usr/local/bin/amboso_fn.sh" ] ; then { #We only enter here if we force sourcing from global anvil
+      #We need one more message to show me are forcing this.
+      printf "[WARN]   Forcing source from global path -> {%s}\n" "$std_amboso_global_path" >&2
+      amboso_fn_path="/usr/local/bin/amboso_fn.sh"
+      [ "$quiet_flag" -eq 0 ] && printf "[WARN]    Fallback to default path for amboso_fn. Sourcing: \"%s\".\n" "$amboso_fn_path" >&2
+      # shellcheck source=/usr/local/bin/amboso_fn.sh
+      . "$amboso_fn_path";
+      source_res="$?"
+      if [ "$source_res" -ne 0 ] ; then {
+        printf "[PREP]    Failed loading amboso_fn. Quitting.\n\n    Using file: \"%s\".\n" "$amboso_fn_path" >&2
+        exit 3
+      }
+      fi
+    }
+    fi
+  }
+  fi
+  if [[ "$source_res" -ne 0 && "$(basename "$(pwd)")" = "amboso" ]] ; then {
     amboso_fn_path="$(realpath "$(pwd)")/amboso_fn.sh"
     if [ -f "$amboso_fn_path" ] ; then {
       [ "$verbose_flag" -gt 1 ] && printf "[PREP]    Running inside amboso dir. Sourcing: \"%s\".\n" "$amboso_fn_path">&2
@@ -55,7 +82,7 @@ source_amboso_api() {
       exit 2
     }
     fi
-  } else {
+  } elif [[ "$source_res" -ne 0 ]]; then {
     amboso_fn_path="$(realpath "$(pwd)")/amboso/amboso_fn.sh"
     found_amboso_dir=0
     [ "$verbose_flag" -gt 1 ] && printf "[PREP]    Assuming we are running in super-repo. Sourcing: \"%s\".\n" "$amboso_fn_path" >&2
@@ -151,5 +178,10 @@ is_interactive=0
 
 [ "$#" -eq 0 ] && is_interactive=1
 
-source_amboso_api
+source_amboso_api "$force_global_source"
+
+if [[ "$force_global_source" -eq 1 ]] ; then {
+    :
+}
+fi
 amboso_main "$@"
