fix: -t now exits after full testing
Contains better output for fringe cases

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -171,7 +171,7 @@ function set_supported_tests {
     test_fp="$cases_path/$FILE"
     if ! [[ -f $test_fp && -x $test_fp ]] ; then {
       skipped=$((skipped+1))
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Skip test $FILE (at $test_fp), not an executable file.\e[0m" >&2
+      [[ $verbose_flag -gt 0 && $quiet_flag -eq 0 ]] && echo -e "\033[0;36m[TEST]    Skip test $FILE (at $test_fp), not an executable file.\e[0m" >&2
       continue
     }
     fi
@@ -184,7 +184,7 @@ function set_supported_tests {
     test_fp="$errorcases_path/$FILE"
     if ! [[ -f $test_fp && -x $test_fp ]] ; then {
       skipped=$((skipped+1))
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Skip errtest $FILE (at $test_fp), not an executable file.\e[0m" >&2
+      [[ $verbose_flag -gt 0 && $quiet_flag -eq 0 ]] && echo -e "\033[0;37m[TEST]    Skip errtest $FILE (at $test_fp), not an executable file.\e[0m" >&2
       continue
     }
     fi
@@ -519,7 +519,7 @@ if [[ ${AMBOSO_LVL_REC} -gt 1 ]] ; then {
     echo -e "\\n\n        args: (\"$@\")" >&2
     echo_current_tags >&2
   } elif [[ $AMBOSO_LVL_REC -gt 2 ]] ; then {
-    echo -e "[AMBOSO]    Deep recursion (>1), are you calling \"$prog_name\" in a test? ;)" >&2
+    [[ $test_info_was_set -eq 1 ]] && echo -e "[AMBOSO]    Deep recursion (>1), are you calling \"$prog_name\" in a test? ;)" >&2
     #[[ $small_test_mode_flag -gt 0 ]] && echo "[ERROR]    Can't proceed and macro -t for -T on all tags." && exit 69
     #[[ $test_mode_flag -gt 0 ]] && echo "[ERROR]    Can't proceed with test mode." && exit 69
   }
@@ -572,9 +572,9 @@ if [[ $test_mode_flag -gt 0 && $test_info_was_set -gt 0 ]] ; then {
     echo -e "\033[1;32m[DEBUG]    bone dir: ( $cases_dir )\e[0m" >&2
     echo -e "\033[1;32m           kulpo dir: ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
   } else {
-    echo -e "\033[1;32m[DEBUG]    bone dir: ( $cases_dir )\e[0m" >&2
-    echo -e "\033[1;32m           kulpo dir: ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
-    echo -e "\n\033[1;31m[PANIC]    Running \"$prog_name\" using test mode in a program that will be called by test mode is not supported.\e[0m\n" #&& usage && exit 1
+    [[ ! -z $cases_dir ]] && echo -e "\033[1;32m[DEBUG]    bone dir: ( $cases_dir )\e[0m" >&2
+    [[ ! -z $errors_dir ]] && echo -e "\033[1;32m           kulpo dir: ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
+    echo -e "\n\033[1;31m[PANIC]    Running  \"$prog_name\" in test mode inside a test is not supported.\e[0m\n" #&& usage && exit 1
     exit 69
     #We return 69 and will check for this somewhere
   }
@@ -588,7 +588,7 @@ if [[ $test_mode_flag -gt 0 && $test_info_was_set -gt 0 ]] ; then {
     echo -e "\033[1;33m[DEBUG]    bone dir (NO -K passed to this call): ( $cases_dir )\e[0m" >&2
     echo -e "\033[1;33m           kulpo dir (NO -K passed to this amboso call): ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
 
-    echo -e "\n\033[1;31m[PANIC]    Running \"$prog_name\" using test mode in a program that will be called by test mode is not supported.\e[0m\n" >&2 #&& usage && exit 1
+    echo -e "\n\033[1;31m[PANIC]    Running  \"$prog_name\" using test mode in a program that will be called by test mode is not supported.\e[0m\n" >&2 #&& usage && exit 1
     exit 1
   }
   fi
@@ -805,7 +805,7 @@ if [[ $delete_flag -gt 0 && $test_mode_flag -gt 0 ]] && [[ $verbose_flag -gt 0 |
 }
 fi
 
-#If we have -t and not -T, we check all tests and DON'T EXIT
+#If we have -t and not -T, we check all tests and EXIT
 #WIP
 if [[ $small_test_mode_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
   if [[ $quiet_flag -eq 0 ]] ; then {
@@ -824,9 +824,9 @@ if [[ $small_test_mode_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
 
   start_t_tests=`date +%s.%N`
   for i in $(seq 0 $(($tot_tests-1))); do {
-    [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;35m[TEST]    Running:  \"$prog_name -T$quietm$verbm$buildm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m" >&2
+    [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;35m[TEST-MACRO]    Running:  \"$prog_name -T$quietm$verbm$buildm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m" >&2
     start_t_curr_test=`date +%s.%N`
-    "$prog_name" -T"$quietm""$verbm""$buildm" -K "$kazoj_dir" -D "$milestones_dir" "${supported_tests[$i]}"
+    "$prog_name" -T"$quietm$verbm$buildm" -K "$kazoj_dir" -D "$milestones_dir" "${supported_tests[$i]}"
     retcod="$?"
     end_t_curr_test=`date +%s.%N`
     runtime_curr_test=$( echo "$end_t_curr_test - $start_t_curr_test" | bc -l )
@@ -852,7 +852,7 @@ if [[ $small_test_mode_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
   #echo -e "\033[0;34m[TEST]    Full testing took $display_zero$runtime_tests seconds ( $tot_tests done).\e[0m\n"
   exit 0
 } elif [[ $small_test_mode_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
-  echo -e "\033[1;31m[TEST]    Error: -t was asserted with -T. -t is a shortcut to run as -T on all tests found.\e[0m\n"
+  echo -e "\033[1;31m[PANIC]    [-t] used with [-T].\n\n        -t is a shortcut to run as -T on all tests found.\e[0m\n"
   exit 1
   echo "UNREACHABLE"
 }
@@ -946,8 +946,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   }
   fi
 
-  if [[ -z $test_path && (( $init_flag -gt 0 || $build_flag -gt 0 )) ]]; then {
-    #We may only freak out if we don't have init flag on
+  if [[ -z $test_path ]]; then {
     if [[ $quiet_flag -eq 0 ]] ; then {
       flaginit=""
       flagbuild=""
@@ -990,6 +989,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     #echo -e "\033[0;34m[TEST]    \"-d\" is set, Deleting: ( $relative_testpath ).\e[0m" >&2
     #delete_test "$relative_testpath"
   } elif [[ $init_flag -gt 0 ]] ; then {
+    #echo "UNREACHABLE." && exit 1
     echo -e "\033[0;34m[TEST]    \"-i\" is set, Recording ALL: ( $relative_testpath ).\e[0m"
     echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
     for i in $(seq 0 $(($tot_tests-1))); do {
@@ -998,8 +998,9 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       quietm=""
       [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet flag mode to the subcalls
       [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[TEST]    Recording ALL: ( $(($i+1)) / $tot_tests ) ( $TEST )" >&2
+      echo -e "\033[1;35m[TEST]    Running:\e[0m    \033[1;34m\"$prog_name -K $kazoj_dir -D $scripts_dir -bT$quietm$verb $TEST 2>/dev/null \"\e[0m"
       start_t=`date +%s.%N`
-      ( "$prog_name" -K "$kazoj_dir" -D "$scripts_dir" -b"$quietm""$verb"Tt "$TEST" 2>/dev/null ; exit "$?")
+      ( "$prog_name" -K "$kazoj_dir" -D "$scripts_dir" -b"$quietm""$verb"T "$TEST" 2>/dev/null ; exit "$?")
       record_res="$?"
       end_t=`date +%s.%N`
       runtime=$( echo "$end_t - $start_t" | bc -l )
@@ -1015,7 +1016,11 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   fi
   if [[ -z $relative_testpath && $init_flag -eq 0 ]] ; then {
     #Exit 0 as intended behaviour FIXME
-    echo -e "\033[1;33m[TEST]    Can't proceed further with no valid target path, query was ( $query ). Quitting.\e[0m" && exit 0
+    echo -e "\033[1;31m[TEST]    Can't proceed further with no valid target path, query was ( $query ).\e[0m"
+    echo -e "\033[1;31m[TEST]    Supported tests:\e[0m"
+    echo_tests_info "$kazoj_dir"
+    echo -e "\033[1;31m[TEST]    Quitting.\e[0m"
+    exit 1
   }
   fi
   if [[ -z $relative_testpath && $init_flag -eq 1 && ! -z $query ]] ; then {
@@ -1032,7 +1037,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   run_tmp_escout="$(mktemp)"
   run_tmp_err="$(mktemp)"
   run_tmp_escerr="$(mktemp)"
-  echo -e "\033[1;33m[TEST]    Running ( $relative_testpath ).\e[0m"
+  echo -e "\033[0;36m[TEST]    Running:\e[0m    \033[1;35m\"$relative_testpath\"\e[0m"
   run_test "$relative_testpath" >>"$run_tmp_out" 2>>"$run_tmp_err"
   ran_res="$?"
 
@@ -1079,7 +1084,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Pass, registered stdout is empty. Is that expected?\e[0m" >&2
     }
     fi
-    if [[ $verbose_flag -gt 0 ]]; then {
+    if [[ $verbose_flag -gt 0 && $quiet_flag -eq 0 ]]; then {
       echo -e "\n\033[1;35m[TEST]    (stdout) Expected:\e[0m"
       cat "$relative_testpath.stdout"
       echo -e "\n\033[1;35m[TEST]    (stdout) Found:\e[0m"
@@ -1088,11 +1093,14 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     fi
   } else {
     out_res="fail"
-    echo -e "\n\033[1;31m[TEST]    (stdout) Expected:\e[0m"
-    cat "$relative_testpath.stdout"
-    echo -e "\n\033[1;31m[TEST]    (stdout) Found:\e[0m"
-    cat "$run_tmp_escout"
-    echo -e "\n\033[1;31m[TEST]    Failed: stdout changed.\e[0m"
+    if [[ $quiet_flag -eq 0 ]]; then {
+      echo -e "\n\033[1;31m[TEST]    (stdout) Expected:\e[0m"
+      cat "$relative_testpath.stdout"
+      echo -e "\n\033[1;31m[TEST]    (stdout) Found:\e[0m"
+      cat "$run_tmp_escout"
+    }
+    fi
+    echo -e "\033[1;31m[TEST]    Failed: stdout changed.\e[0m"
     #cat "$run_tmp_escout"
   }
   fi
@@ -1112,7 +1120,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Pass, registered stderr is empty. Is that expected?\e[0m" >&2
     }
     fi
-    if [[ $verbose_flag -gt 0 ]]; then {
+    if [[ $verbose_flag -gt 0 && $quiet_flag -eq 0 ]]; then {
       echo -e "\n\033[1;35m[TEST]    (stderr) Expected:\e[0m"
       cat "$relative_testpath.stderr"
       echo -e "\n\033[1;35m[TEST]    (stderr) Found:\e[0m"
@@ -1122,11 +1130,14 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     #cat "$run_tmp_escerr"
   } else {
     err_res="fail"
-    echo -e "\n\033[1;31m[TEST]    (stderr) Expected:\e[0m"
-    cat "$relative_testpath.stderr"
-    echo -e "\n\033[1;31m[TEST]    (stderr) Found:\e[0m"
-    cat "$run_tmp_escerr"
-    echo -e "\n\033[1;31m[TEST]    Failed: stderr changed.\e[0m"
+    if [[ $quiet_flag -eq 0 ]]; then {
+      echo -e "\n\033[1;31m[TEST]    (stderr) Expected:\e[0m"
+      cat "$relative_testpath.stderr"
+      echo -e "\n\033[1;31m[TEST]    (stderr) Found:\e[0m"
+      cat "$run_tmp_escerr"
+    }
+    fi
+    echo -e "\033[1;31m[TEST]    Failed: stderr changed.\e[0m"
     #cat "$run_tmp_escerr"
   }
   fi
