feat: moved delete after build/run
chore: updated try_anvil

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,7 +2,7 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
-amboso_version="amboso version 1.1.1-devel"
+amboso_version="amboso version 1.1.1"
 
 function echo_amboso_version {
   echo "$amboso_version"
@@ -454,49 +454,6 @@ if [[ $version > $makefile_version || $version = $makefile_version ]] ; then
   has_makefile=1
 fi
 
-#Check if we are deleting and exiting early
-#We skipped first deletion pass if purge mode is requested, since we will enter here later
-if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
-    clean_res=1
-  if [[ $has_makeclean -gt 0 && $base_mode_flag -gt 0 ]] ; then { #Running in git mode skips make clean
-    tool_txt="make clean"
-    has_bin=0
-    curr_dir=$(realpath .)
-    delete_path="$scripts_dir""v""$version"
-      if [[ ! -d $delete_path ]] ; then {
-        echo -e "\033[1;31m[ERROR]    '$delete_path' is not a valid directory.\n    Check your supported versions for details on ( $version ).\e[0m\n" #>&2
-      } elif [[ -x $scripts_dir/v$version/$exec_entrypoint ]] ; then { #Executable exists
-        has_bin=1 && echo -e "\033[0;33m[DELETE]   ( $version ) has an executable.\e[0m\n" >&2
-        cd "$delete_path"; make clean 2>/dev/null #1>&2
-        clean_res=$?
-        cd "$curr_dir"
-        exit "$clean_res"
-      } else {
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;31m[DELETE]   ( $versions ) does not have an executable at ( $delete_path ).\e[0m\n" # >&2
-           exit 1
-      }
-      fi
-  } else { #Doesn't have Makefile, build method 2. Running in git mode also skips using make clean
-    tool_txt="rm"
-    has_bin=0
-    if [[ -x $scripts_dir"/v$version"/"$exec_entrypoint" ]] ; then {
-      has_bin=1 && echo -e "\033[0;33m[DELETE]    ( $version ) has an executable.\e[0m" #>&2
-    }
-    fi
-    rm $(realpath "$scripts_dir"/"v$version/$exec_entrypoint") #2>/dev/null
-    clean_res=$?
-    if [[ $clean_res -eq 0 ]] ; then {
-      echo -e "\033[0;32m[DELETE]    Success on ( $version ).\e[0m" >&2
-    } else {
-      echo -e "\033[0;31m[DELETE]    Failure on ( $version ).\e[0m" >&2
-    }
-    fi
-    exit "$clean_res"
-  }
-  fi
-}
-fi
-
 #If we can't find the file we may try to build it
 if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
   echo -e "\n\033[1;33m[QUERY]    ( $version ) binary not found in ( $script_path ).\e[0m" #>&2
@@ -619,7 +576,50 @@ if [[ ! -z $version && $run_flag -eq 1 && -x $script_path/$exec_entrypoint ]] ; 
 } elif [[ ! -z $version && $run_flag -eq 0  ]] ; then {
   echo -e "\033[0;33m[DEBUG]    Running without -r flag, won't run.\e[0m" >&2
 } elif [[ -z $version && $run_flag -gt 0 ]] ; then {
-  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[DEBUG]    Running with -r flag but couldn't find bin!\e[0m\n" >&2
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[DEBUG]    Running with -r but requested an empty tag ( $version )!\e[0m" >&2
+}
+fi
+
+#Check if we are deleting and exiting early
+#We skipped first deletion pass if purge mode is requested, since we will enter here later
+if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
+    clean_res=1
+  if [[ $has_makeclean -gt 0 && $base_mode_flag -gt 0 ]] ; then { #Running in git mode skips make clean
+    tool_txt="make clean"
+    has_bin=0
+    curr_dir=$(realpath .)
+    delete_path="$scripts_dir""v""$version"
+      if [[ ! -d $delete_path ]] ; then {
+        echo -e "\033[1;31m[ERROR]    '$delete_path' is not a valid directory.\n    Check your supported versions for details on ( $version ).\e[0m\n" #>&2
+      } elif [[ -x $scripts_dir/v$version/$exec_entrypoint ]] ; then { #Executable exists
+        has_bin=1 && echo -e "\033[0;33m[DELETE]   ( $version ) has an executable.\e[0m\n" >&2
+        cd "$delete_path"; make clean 2>/dev/null #1>&2
+        clean_res=$?
+        cd "$curr_dir"
+        exit "$clean_res"
+      } else {
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;31m[DELETE]   ( $versions ) does not have an executable at ( $delete_path ).\e[0m\n" # >&2
+           exit 1
+      }
+      fi
+  } else { #Doesn't have Makefile, build method 2. Running in git mode also skips using make clean
+    tool_txt="rm"
+    has_bin=0
+    if [[ -x $scripts_dir"/v$version"/"$exec_entrypoint" ]] ; then {
+      has_bin=1 && [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[DELETE]    ( $version ) has an executable.\e[0m" >&2
+    }
+    fi
+    rm $(realpath "$scripts_dir"/"v$version/$exec_entrypoint") #2>/dev/null
+    clean_res=$?
+    if [[ $clean_res -eq 0 ]] ; then {
+      echo -e "\033[0;32m[DELETE]    Success on ( $version ).\e[0m" >&2
+    } else {
+      echo -e "\033[0;31m[DELETE]    Failure on ( $version ).\e[0m" >&2
+    }
+    fi
+    exit "$clean_res"
+  }
+  fi
 }
 fi
 
