chore: support test --list and --build

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -4687,12 +4687,25 @@ amboso_main() {
         shift
         local build_flg=0
         local list_flg=0
-        while getopts "bl" opt; do
+        while getopts "bl-:" opt; do
             case $opt in
               b ) build_flg=1; log_cl "Passed  build flag" info;;
               l ) list_flg=1; log_cl "Passed  list flag" info;;
               \? ) log_cl "Invalid option: -$OPTARG. Run with -h for help." error >&2; exit 1;;
               : ) log_cl "Option -$OPTARG requires an argument. Run with -h for help." error >&2; exit 1;;
+              -)
+                case "${OPTARG}" in
+                  build) build_flg=1;;
+                  list) list_flg=1;;
+                *)
+                  if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
+                    log_cl "Unknown option --${OPTARG}" error
+                    amboso_usage
+                    log_cl "Run with -h, --help to see available long options" info
+                    exit 1
+                  fi
+                  ;;
+                esac;;
             esac
           local tot_opts=$OPTIND
           shift $(( $tot_opts -1 ))
