fix: better herror messages
Beg for symlink in verbose-mode>1

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -182,6 +182,7 @@ if [[ $print_cfg_flag -gt 0 ]] ; then {
 fi
 
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]    Done getopts.\e[0m" >&2
+[[ $verbose_flag -gt 0 && ! $prog_name = "anvil" ]] && echo -e "\033[1;36m[AMBOZO]\e[0m    Please, symlink me to \"anvil\".\n" >&2
 
 if [[ $(basename $(pwd)) == "amboso" ]] ; then {
   amboso_fn_path="$(realpath $(pwd))/amboso_fn.sh"
@@ -1069,11 +1070,11 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
             [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Moved $exec_entrypoint to $script_path.\e[0m" #>&2
           }
           fi
-          git switch - 2>/dev/null #We get back to starting repo state
+          git switch - #We get back to starting repo state
           switch_res="$?"
-          [[ $switch_res -gt 0 ]] && echo -e "\n\033[1;31m[ERROR]    Can't finish checkin out ($version). Abort." && exit 1
+          [[ $switch_res -gt 0 ]] && echo -e "\n\033[1;31m[ERROR]    Can't finish checking out ($version).\n    You may have a dirty index and may need to run \033[1;35\"git restore .\"\e[0m.\n Abort.\n" && exit 1
           git submodule update --init --recursive #We set all submodules to commit state
-          [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[BUILD]    Switched back to starting commit.\e[0m" >&2
+          [[ $quiet_flag -eq 0 ]] && echo -e "\033[0;32m[BUILD]    Switched back to starting commit.\e[0m"
         }
         fi
       }
@@ -1086,6 +1087,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Building ( $version ), using gcc call.\e[0m" >&2
       #echo "" >&2 #new line for error output
       [[ -z $source_name ]] && echo -e "\n\033[1;31m[WTF-ERROR]    Missing source file name. ( $version ).\e[0m\n" && usage && exit 1
+      [[ $pack_flag -gt 0 ]] && echo -e "\n\033[1;33m[PACK]    -z is not supported for ($tool_txt). TAG < ($makefile_version).\n\n    \033[1;35Current: ($version @ $source_name).\e[0m\n"
 
       start_t=`date +%s.%N`
       if [[ $git_mode_flag -eq 0 ]] ; then { #Building in base mode, we cd into target directory before make
