feat: valid candidate

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -729,13 +729,13 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   relative_testpath="$test_path"
 
   if [[ $build_flag -gt 0 ]] ; then {
-    echo "\n[TEST]    recording: ( $relative_testpath ).\n"
+    echo -e "\n[TEST]    Recording: ( $relative_testpath ).\n"
     #record_test "$relative_testpath"
   } elif [[ $delete_flag -gt 0 ]] ; then {
-    echo "[TEST]    deleting: ( $relative_testpath )."
-    delete_test "$relative_testpath"
+    echo -e "\n[TEST]    Deleting: ( $relative_testpath )."
+    #delete_test "$relative_testpath"
   } elif [[ $init_flag -gt 0 ]] ; then {
-    echo "[TEST]    recording all: query ( $relative_testpath )."
+    echo -e "\n[TEST]    Recording ALL: ( $relative_testpath )."
     echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
     for i in $(seq 0 $(($tot_tests-1))); do {
       TEST="${supported_tests[$i]}"
@@ -748,12 +748,12 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     done
     #init_all_tests "$relative_testpath"
   } elif [[ $purge_flag -gt 0 ]] ; then {
-    echo "[TEST]    deleting all: query ( $relative_testpath )."
+    echo "[TEST]    Deleting ALL: ( $relative_testpath )."
     #purge_all_tests "$relative_testpath"
   }
   fi
-  [[ -z $query && $init_flag -eq 1 && $purge_flag -eq 0 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no query.\e[0m" && exit 1
-  [[ -z $query && $init_flag -eq 0 && $purge_flag -eq 1 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -p flag, with no query.\e[0m" && exit 1
+  [[ -z $query && $init_flag -eq 1 && $purge_flag -eq 0 ]] && echo -e "\033[1;33m[INIT]    Can't proceed further with no query, quitting.\e[0m" && exit 0
+  [[ -z $query && $init_flag -eq 0 && $purge_flag -eq 1 ]] && echo -e "\033[1;33m[PURGE]    Can't proceed further with no query, quitting.\e[0m" && exit 0
   [[ -z $relative_testpath && $init_flag -eq 0 && $purge_flag -eq 1 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -p flag, with no testpath. ( $relative_testpath ).\e[0m" && exit 1
   [[ -z $relative_testpath && $init_flag -eq 1 && $purge_flag -eq 0 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no testpath. ( $relative_testpath ).\e[0m" && exit 1
   [[ -z $relative_testpath ]] && echo -e "\033[1;31m[ERROR]    Can't proceed with no testpath. ( $relative_testpath ).\e[0m" && exit 1
@@ -766,10 +766,10 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   escape_colorcodes_tee "$run_tmp_err" "$run_tmp_escerr"
   if [[ $build_flag -eq 0 ]] ; then {
     :
-    #cp "$run_tmp_escout" "$relative_testpath".stdout || echo -e "Failed replacing stdout with new file."
-    #cp "$run_tmp_escerr" "$relative_testpath".stderr || echo -e "Failed replacing stderr with new file."
+    cp "$run_tmp_escout" "$relative_testpath".stdout || echo -e "Failed replacing stdout with new file."
+    cp "$run_tmp_escerr" "$relative_testpath".stderr || echo -e "Failed replacing stderr with new file."
   } else {
-    echo ciao;
+    :
   }
   fi
   rm -f "$run_tmp_out" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\n"
@@ -782,13 +782,19 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   out_res=""
   if [[ "$diff_res" -eq 0 ]]; then {
     out_res="pass"
-    [[ ! -z "$run_tmp_escout" && ! -z "$relative_testpath.stdout" ]] && echo -e "Pass, not null"
-    #cat "$run_tmp_escout"
+    [[ ! -z "$run_tmp_escout" && ! -z "$relative_testpath.stdout" ]] && echo -e "\033[0;32m[TEST]    Pass, both outputs are not empty."
+    if [[ $verbose_flag -gt 0 ]]; then {
+      echo -e "\n\033[1;35m[TEST]    (stdout) Expected:\e[0m"
+      cat "$relative_testpath.stdout"
+      echo -e "\n\033[1;35m[TEST]    (stdout) Found:\e[0m"
+      cat "$run_tmp_escout"
+    }
+    fi
   } else {
     out_res="fail"
-    echo -e "\n\033[1;31m[TEST]    Expected:\e[0m"
+    echo -e "\n\033[1;31m[TEST]    (stdout) Expected:\e[0m"
     cat "$relative_testpath.stdout"
-    echo -e "\n\033[1;31m[TEST]    Found:\e[0m"
+    echo -e "\n\033[1;31m[TEST]    (stdout) Found:\e[0m"
     cat "$run_tmp_escout"
     echo -e "\n\033[1;31m[TEST]    Failed: stdout changed.\e[0m"
     #cat "$run_tmp_escout"
@@ -801,13 +807,20 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   diff_res="$?"
   if [[ "$diff_res" -eq 0 ]]; then {
     err_res="pass"
-    [[ ! -z "$run_tmp_escerr" && ! -z "$relative_testpath.stderr" ]] && echo -e "Pass, not null"
+    [[ ! -z "$run_tmp_escerr" && ! -z "$relative_testpath.stderr" ]] && echo -e "\033[0;32m[TEST]    Pass, both outputs are not empty."
+    if [[ $verbose_flag -gt 0 ]]; then {
+      echo -e "\n\033[1;35m[TEST]    (stderr) Expected:\e[0m"
+      cat "$relative_testpath.stderr"
+      echo -e "\n\033[1;35m[TEST]    (stderr) Found:\e[0m"
+      cat "$run_tmp_escerr"
+    }
+    fi
     #cat "$run_tmp_escerr"
   } else {
     err_res="fail"
-    echo -e "\n\033[1;31m[TEST]    Expected:\e[0m"
+    echo -e "\n\033[1;31m[TEST]    (stderr) Expected:\e[0m"
     cat "$relative_testpath.stderr"
-    echo -e "\n\033[1;31m[TEST]    Found:\e[0m"
+    echo -e "\n\033[1;31m[TEST]    (stderr) Found:\e[0m"
     cat "$run_tmp_escerr"
     echo -e "\n\033[1;31m[TEST]    Failed: stderr changed.\e[0m"
     #cat "$run_tmp_escerr"
