feat: 1.6.4 Quit early on dirty git status (#41)

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -13,8 +13,8 @@ kernel_release="$(uname -r)"
 kernel_version="$(uname -v)"
 machine_name="$(uname -m)"
 os_name="$(uname -o)"
-amboso_currvers="1.6.3"
-expected_AMBOSO_API_LVL="1.6.3"
+amboso_currvers="1.6.4"
+expected_AMBOSO_API_LVL="1.6.4"
 amboso_testflag_version="1.4.9"
 export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 # check recursion
@@ -360,6 +360,15 @@ if [[ $base_mode_flag -gt 0 ]] ; then {
 fi
 if [[ $git_mode_flag -gt 0 ]] ; then {
   git_mode_check
+  git_mode_check_res="$?"
+  if [[ $git_mode_check_res -eq 0 ]]; then {
+  	[[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[GIT]    Status was clean.\e[0m" >&2
+  } else {
+  	echo -e "\033[1;31m[GIT]    Status was not clean!\e[0m" >&2
+  	echo -e "\033[1;31m[AMBOSO]    Aborting.\e[0m" >&2
+	exit 1
+  }
+  fi
 }
 fi
 
