feat: added recursion env variable
Should print call args

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,9 +2,49 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
-amboso_currvers="1.3.2"
+amboso_currvers="1.4.0-devel"
 amboso_testflag_version="1.3.0"
 amboso_version="amboso version $amboso_currvers"
+
+PARENT_COMMAND=$(ps -o comm= $PPID)
+[[ $verbose_flag -gt 0 ]] && echo parent is $PARENT_COMMAND
+
+# set env var if not exists
+export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
+
+# check recursion
+if [[ "${AMBOSO_LVL_REC}" -le "2" ]]; then
+  [[ "$AMBOSO_LVL_REC" -eq 0 ]] && echo -e "\033[1;35m[AMBOSO]    Current version: $amboso_currvers\e[0m\n"
+else
+  echo -e "\n[AMBOSO]    exceeded depth for recursion ( at ${AMBOSO_LVL_REC})"
+  exit 1
+fi
+# increment depth counter
+export AMBOSO_LVL_REC=$(($AMBOSO_LVL_REC+1))
+
+function echo_current_tags {
+  echo -e "[DEBUG]    Current flags:\n"
+  echo -en "           [MODE]    -"
+  [[ $test_mode_flag -gt 0 ]] && echo -n "t"
+  [[ $big_test_mode_flag -gt 0 ]] && echo -n "T"
+  [[ $git_mode_flag -gt 0 ]] && echo -n "g"
+  [[ $base_mode_flag -gt 0 ]] && echo -n "B"
+  echo ""
+  echo -en "           [OP]    -"
+  [[ $verbose_flag -gt 0 ]] && echo -n "V"
+  [[ $quiet_flag -gt 0 ]] && echo -n "q"
+  [[ $init_flag -gt 0 ]] && echo -n "i"
+  [[ $build_flag -gt 0 ]] && echo -n "b"
+  [[ $purge_flag -gt 0 ]] && echo -n "p"
+  [[ $delete_flag -gt 0 ]] && echo -n "d"
+  [[ $small_list_flag -gt 0 ]] && echo -n "l"
+  [[ $big_list_flag -gt 0 ]] && echo -n "L"
+  [[ $bighelp_flag -gt 0 ]] && echo -n "H"
+  [[ $smallhelp_flag -gt 0 ]] && echo -n "h"
+  [[ $version_flag -eq 1 ]] && echo -n "v"
+  [[ $version_flag -gt 1 ]] && echo -n "v" #One more level to this option
+  echo -e "\n"
+}
 
 function echo_amboso_version {
   echo "$amboso_version"
@@ -473,6 +513,9 @@ while getopts "M:S:E:D:K:BgVbpHhrivdlLtTq" opt; do
 tot_opts=$OPTIND
 done
 
+[[ $AMBOSO_LVL_REC -gt 0 ]] && echo -e "\n[AMBOSO]    recursive call , depth ${AMBOSO_LVL_REC}\n\n        args: (\"$@\")\n" >&2
+echo_current_tags >&2
+
 if [[ $version_flag -gt 1 ]] ; then {
   echo_amboso_version_short
   exit 0
@@ -483,6 +526,7 @@ if [[ $version_flag -gt 1 ]] ; then {
 fi
 
 #We check again if testmode was requested, and reset the other mode flags.
+# -t always overrides -g and -B
 if [[ $test_mode_flag -gt 0 ]] ; then {
   git_mode_flag=0
   base_mode_flag=0
@@ -492,6 +536,8 @@ fi
 
 #We check again if basemode was requested, as the only flag checked in build stage is git_mode_flag
 #If base_mode_flag is asserted, we always override git_mode_flag
+
+#Default mode with no flags should be git mode
 [[ $base_mode_flag -gt 0 ]] && git_mode_flag=0 && echo -e "\033[1;31m[AMBOSO-MODE]    Running in base mode, expecting full source builds.\e[0m" >&2
 [[ $git_mode_flag -gt 0 ]] && git_mode_check #We are now sure we can quit immediately if not running in a git repo
 
@@ -520,18 +566,28 @@ if [[ $bighelp_flag -gt 0 ]]; then {
       echo_amboso_version
       set_source_info "$milestones_dir"
       set_supported_versions "$milestones_dir"
-      set_supported_versions "$milestones_dir"
       usage
       exit 0
 }
 fi
 
+#Syncpoint: we assert we know these names after this. WIP
+
+#TODO: check if scripts_dir is needed anywhere... why
 scripts_dir="$milestones_dir" # MUST BE SET before checking for -S and -E
 set_supported_versions "$scripts_dir" # Might as well do it now
 set_source_info "$milestones_dir"
-kazoj_dir="${sources_info[3]}"
+kazoj_dir="${sources_info[3]}" #TODO: don't think this should be overwritten here if assigned earlier
 set_tests_info "$kazoj_dir"
 set_supported_tests "$kazoj_dir"
+
+
+if [[ $quiet_flag -eq 0 ]]; then { #WIP
+    echo -e "\033[1;35m[VERB]    SYNCPOINT: list tag names\e[0m" >&2
+    echo_supported_tags "$milestones_dir" >&2
+    echo_tests_info "$kazoj_dir" >&2
+}
+fi
 
 #If we're in test mode and test dir was not passed, we check if "./kazoj" is a directory and use that. If it isn't, we may get the name from stego.lock. If that is not a directory, we quit immediately.
 if [[ -z $kazoj_dir && $test_mode_flag -gt 0 ]] ; then {
@@ -540,25 +596,23 @@ if [[ -z $kazoj_dir && $test_mode_flag -gt 0 ]] ; then {
        kazoj_dir="./kazoj"
        set_tests_info "$kazoj_dir"
        set_supported_tests "$kazoj_dir"
-       echo -e "\033[1;33m[DEBUG]    No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m" >&2
+       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  (AFTER SYNC)  No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m" >&2
      } else {
-       echo -e "\033[1;33m[DEBUG]    No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
+       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  (AFTER SYNC)  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
        set_source_info "$milestones_dir"
        kazoj_dir="${sources_info[3]}"
        set_tests_info "$kazoj_dir"
        set_supported_tests "$kazoj_dir"
+       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  (AFTER SYNC)  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
      }
      fi
   } else {
-     echo -e "\033[1;31m[ERROR]    No -K flag on a test run, amboso version is < ($amboso_testflag_version).\n    Quitting.\e[0m" #>&2
+     echo -e "\033[1;31m[ERROR]  (AFTER SYNC)  No -K flag on a test run, amboso version is < ($amboso_testflag_version).\n    Quitting.\e[0m" #>&2
      exit 0;
   }
   fi
 }
 fi
-
-#echo_tests_info "$tests_dir"
-
 
 #Check if we are printing tag list for current mode and exiting early
 if [[ $small_list_flag -gt 0 ]]; then {
@@ -620,10 +674,17 @@ fi
 #Check if we are doing init and we're not in test mode
 #Which means we want to build all tags
 if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
+  if [[ $quiet_flag -eq 0 ]]; then { #WIP
+      echo -e "\033[1;35m[VERB]    Init mode (-t was 0): build all tags\e[0m" >&2
+      echo_supported_tags "$milestones_dir" >&2
+  }
+  fi
+
   count_bins=0
   start_t_init=`date +%s.%N`
   for i in $(seq 0 $(($tot_vers-1))); do
     init_vers="${supported_versions[$i]}"
+    [[ $quiet_flag -eq 0 ]] && echo -e "\n[INIT]    Trying to build ( $init_vers ) ( $(($i+1)) / $tot_vers )" >&2
     #Build this vers
     #Init mode ALWAYS tries building, even if we have the binary already ATM
     #Save verbose flag
@@ -631,12 +692,14 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
     gitm=""
     basem=""
     quietm=""
-    [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[INIT]    Trying to build ( $init_vers ) ( $(($i+1)) / $tot_vers )" >&2
+
+    [[ $verbose_flag -gt 0 ]] && verb="V" #Pass verbose mode
     [[ $base_mode_flag -gt 0 ]] && basem="B" #We make sure to pass on eventual base mode to the subcalls
     [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
     [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet flag mode to the subcalls
     #First pass sets the verbose flag but redirects stderr to /dev/null
-    $prog_name -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -b"$verb""$gitm""$basem""$quietm" "$init_vers" 2>/dev/null
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[VERB]    Running \"$prog_name -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -b$verb$gitm$basem$quietm $init_vers\" ( $(($i+1)) / $tot_vers )" >&2
+    "$prog_name" -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -b"$verb""$gitm""$basem""$quietm" "$init_vers" 2>/dev/null
     if [[ $? -eq 0 ]] ; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[INIT]    $init_vers binary ready.\e[0m" >&2
       count_bins=$(($count_bins +1))
@@ -664,7 +727,7 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
     display_zero=""
   }
   fi
-  echo -e "[INIT]    Took $display_zero$runtime_init seconds, ( $count_bins / $tot_vers ) binaries ready."
+  echo -e "\033[0;34m[INIT]    Took $display_zero$runtime_init seconds, ( $count_bins / $tot_vers ) binaries ready.\e[0m"
   #We don't quit after the full build.
   #exit 0
 }
@@ -695,13 +758,36 @@ verbm=""
 [[ $verbose_flag -gt 0 ]] && verbm="V"
 
 #If we have -t and not -T, we always check all tests
+#WIP
 if [[ $test_mode_flag -gt 0 && $big_test_mode_flag -eq 0 ]] ; then {
+  start_t_tests=`date +%s.%N`
   for i in $(seq 0 $(($tot_tests-1))); do {
-    echo -e "\033[1;34m[TEST]    Run:  \"$prog_name -Tt$quietm$verbm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m"
+    [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;34m[TEST]    Run:  \"$prog_name -Tt$quietm$verbm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m" >&2
+    start_t_curr_test=`date +%s.%N`
     "$prog_name" -Tt"$quietm""$verbm" -K "$kazoj_dir" -D "$milestones_dir" "${supported_tests[$i]}"
+    retcod="$?"
+    end_t_curr_test=`date +%s.%N`
+    runtime_curr_test=$( echo "$end_t_curr_test - $start_t_curr_test" | bc -l )
+    display_zero=$(echo $runtime_curr_test | cut -d '.' -f 1)
+    if [[ -z $display_zero ]]; then {
+      display_zero="0"
+    } else {
+      display_zero=""
+    }
+    fi
+    [[ $quiet_flag -eq 0 ]] && echo -e "\033[0;34m[TEST]  ($(($i+1))/$tot_tests)  took $display_zero$runtime_curr_test seconds.\e[0m"
   }
   done
-  #echo -e "\033[0;35m[TEST]    [-d]\e[0m    Will clean test query." >&2
+  end_t_tests=`date +%s.%N`
+  runtime_tests=$( echo "$end_t_tests - $start_t_tests" | bc -l )
+  display_zero=$(echo $runtime_tests | cut -d '.' -f 1)
+  if [[ -z $display_zero ]]; then {
+    display_zero="0"
+  } else {
+    display_zero="" #what?
+  }
+  fi
+  echo -e "\033[0;34m[TEST]    Full testing took $display_zero$runtime_tests seconds ( $tot_tests done).\e[0m"
 }
 fi
 
@@ -716,18 +802,24 @@ for i in $(seq 0 $(( $tot_opts - 2 )) ); do {
 }
 done
 
+
 # $0 is now target version, at position 1 in the array ??
 v_pos=1
 query="${!v_pos}"
 
+    echo -e "\033[1;35m[VERB]    SYNCPOINT: shifted args, query was: ( $query ).\e[0m"
+if [[ $quiet_flag -eq 0 && $verbose_flag -gt 0 ]]; then { #WIP
+    echo -e "\033[1;35m[VERB]    SYNCPOINT: shifted args, query was: ( $query ).\e[0m"
+}
+fi
+
 tot_left_args=$(( $# ))
 if [[ $tot_left_args -gt 1 ]]; then {
-  echo -e "\n\033[1;31m[ERROR]    Unknown argument: "$2".\e[0m\n"
+  echo -e "\n\033[1;31m[ERROR]    Unknown argument: "$2" (ignoring other $(($tot_left_args-1)) args).\e[0m\n"
   usage
   exit 1
 }
 fi
-
 
 #If we don't have init or purge flag, we bail on a missing version argument
 if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 && $test_mode_flag -eq 0 ]]; then {
@@ -743,10 +835,16 @@ if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 && $test_mod
 fi
 #Check if we are doing a test
 if [[ $test_mode_flag -gt 0 ]]; then {
-  #We expect $scripts_dir to end with /
+  if [[ $quiet_flag -eq 0 ]]; then { #WIP
+      echo -e "\033[1;35m[VERB]    Test mode (-t was on).\e[0m" >&2
+      echo_tests_info "$kazoj_dir" >&2
+      [[ $big_test_mode_flag -gt 0 ]] && echo -e "\033[1;35m[VERB]    (-T was on).\e[0m" >&2
+  }
+  fi
   test_name=""
   test_type=""
   test_path=""
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Checking if query $query is a testcase.\e[0m" >&2
   for i in $(seq 0 $(($count_tests_names-1))); do {
     current_item="${read_tests_files[$i]}"
     #echo "checking $current_item"
@@ -754,21 +852,21 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       test_type="casetest"
       test_name="$query"
       test_path="$kazoj_dir/$cases_dir/${read_tests_files[$i]}"
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Checking cases ($i/$count_tests_names): $test_name\e[0m" >&2
       break; #done looking
     }
     fi
   }
   done
   if [[ -z $test_name ]] ; then {
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Checking if query $query is a error testcase.\e[0m" >&2
     for i in $(seq 0 $(($count_errortests_names-1))); do {
       current_item="${read_errortests_files[$i]}"
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Checking error case ($i/$count_errortests_names): $current_item\e[0m" >&2
       #echo "checking $current_item"
       if [[ $query = $current_item ]] ; then {
 	test_type="errortest"
 	test_name="$query"
 	test_path="$kazoj_dir/$errors_dir/${read_errortests_files[$i]}"
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Checking error case ($i/$count_errortests_names): $test_name\e[0m" >&2
 	break; #done looking
       }
       fi
@@ -777,12 +875,30 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   }
   fi
 
+  if [[ $quiet_flag -eq 0 ]]; then { #WIP
+      echo -e "\033[0;35m[VERB]    SYNCPOINT: done matcing test query, was: ( $query ).\e[0m" >&2
+      echo -e "\033[0;35m[VERB]    expected:\n\n    type:  $test_type\n\n    name:  $test_name\n    path:  $test_path\n\e[0m" >&2
+  }
+  fi
+
   if [[ -z $test_path && (( $init_flag -gt 0 || $build_flag -gt 0 )) ]]; then {
     #We may only freak out if we don't have init flag on
+    if [[ $quiet_flag -eq 0 ]] ; then {
+      flaginit=""
+      flagbuild=""
+      [[ $build_flag -gt 0 ]] && flagbuild="b"
+      [[ $init_flag -gt 0 ]] && flaginit="t"
+      echo -e "\033[0;35m[VERB]    Test path was empty but we have [-$flagbuild$flaginit].\e[0m" >&2
+    }
+    fi
     if [[ -z $test_path && -z $query ]] ; then {
+      [[ $quiet_flag -eq 0 ]] && echo -e "\033[0;35m[VERB]    testpath was empty, query was empty. Should quit.\e[0m" >&2
       keep_run_txt=""
       [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( \"empty\"[$query] ) is not a supported tag. $keep_run_txt.\e[0m" >&2 ; exit 1
+      echo -e "\033[0;35m[VERB]    UNREACHABLE.\e[0m"
+      exit 1
     } elif [[ -z $test_path && ! -z $query ]] ; then {
+      [[ $quiet_flag -eq 0 ]] && echo -e "\033[0;35m[VERB]    testpath was empty, query was not empty: ( $query ).\e[0m" >&2
       keep_run_txt=""
       [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( $query ) is not a supported tag, we quit at this point. $keep_run_txt.\e[0m" >&2 && exit 0
       [[ $build_flag -gt 0 ]] && keep_run_txt="[BUILD]" && echo -e "\033[1;33m[TEST]    ( $query ) is not a supported tag, but we continue to $keep_run_txt.\e[0m" >&2
