1.4.3 better help flag (#14)

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,7 +2,8 @@
 # Bash script to run a milestone build providing the version number.
 # Set recursion env var if not exists
 prog_name="$(readlink -f "$0")"
-amboso_currvers="1.4.2"
+amboso_currvers="1.4.3"
+expected_AMBOSO_API_LVL="1.4.3"
 amboso_testflag_version="1.4.0"
 export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 # check recursion
@@ -131,10 +132,10 @@ done
 if [[ $(basename $(pwd)) == "amboso" ]] ; then {
   amboso_fn_path="$(realpath $(pwd))/amboso_fn.sh"
   if [[ -f $amboso_fn_path ]] ; then {
-    [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;37m[PREP]    Running in amboso dir. Sourcing: \"$amboso_fn_path\".\e[0m" >&2
+    [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;35m[PREP]    Running inside amboso dir. Sourcing: \"$amboso_fn_path\".\e[0m" >&2
     source "$amboso_fn_path";
     source_res="$?"
-    [[ $source_res -ne 0 ]] && echo -e "\033[1;31m[PREP]    Failed loading amboso_fn.\n\n    Using file: \"$amboso_fn_path\".\e[0m" >&2
+    [[ $source_res -ne 0 ]] && echo -e "\033[1;34m[PREP]    Failed loading amboso_fn.\n\n    Using file: \"$amboso_fn_path\".\e[0m" >&2
   } else {
     echo -e "\033[1;31m[ERROR]    Couldn't load amboso_fn, check your symlinks.\e[0m"
     exit 2
@@ -142,9 +143,8 @@ if [[ $(basename $(pwd)) == "amboso" ]] ; then {
   fi
 } else {
   amboso_fn_path="$(realpath $(pwd))/amboso/amboso_fn.sh"
-  echo "$amboso_fn_path"
   if [[ -f $amboso_fn_path ]] ; then {
-    [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;37m[PREP]    Running in amboso dir. Sourcing: \"$amboso_fn_path\".\e[0m" >&2
+    [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;35m[PREP]    Running in super-repo. Sourcing: \"$amboso_fn_path\".\e[0m" >&2
     source "$amboso_fn_path";
     source_res="$?"
     [[ $source_res -ne 0 ]] && echo -e "\033[1;31m[PREP]    Failed loading amboso_fn.\n\n    Using file: \"$amboso_fn_path\".\e[0m" >&2
@@ -157,6 +157,20 @@ if [[ $(basename $(pwd)) == "amboso" ]] ; then {
 fi
 [[ $source_res -ne 0 ]] && echo -e "\033[1;31m[PANIC]    Can't find amboso_fn. Expected path: \"$amboso_fn_path\".\e[0m" && exit 2
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]    Done loading functions.\e[0m" >&2
+[[ $verbose_flag -gt 1 ]] && echo -e "\033[0;37m[PREP]    \"\$AMBOSO_API_LVL\" is: (\033[0;34m $AMBOSO_API_LVL \033[0;37m, expected { \033[1;33m$expected_AMBOSO_API_LVL\033[0;37m } ).\e[0m" >&2
+if [[ $expected_AMBOSO_API_LVL > $AMBOSO_API_LVL ]] ; then {
+  echo -e "\033[1;31m[PANIC]    AMBOSO_API_LVL not supported. Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[1;31m } , { \033[1;33m$AMBOSO_API_LVL\033[1;31m } is too low.\n\n    Maybe check your \"amboso_fn.sh\" file.\n\e[0m"
+  echo -e "\033[1;31m[PANIC]    Couldn't load functions. Quitting.\e[0m"
+  exit 2
+} elif [[ $AMBOSO_API_LVL > $expected_AMBOSO_API_LVL ]] ; then {
+  [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;31m[WARN]    AMBOSO_API_LVL is greater than expected. Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[0;31m } , { \033[1;34m$AMBOSO_API_LVL\033[0;31m } is higher.\e[0m" >&2
+  [[ $verbose_flag -gt 1 ]] && echo -e "\n\033[1;31m[WARN]    Continuing run with unexpected AMBOSO_API_LVL: Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[1;31m } , { \033[1;34m$AMBOSO_API_LVL\033[1;31m } is higher.\e[0m"
+  #exit 2
+} elif [[ $AMBOSO_API_LVL = $expected_AMBOSO_API_LVL ]] ; then {
+  [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]   Running with \"\$AMBOSO_API_LVL\" [ \033[1;35m$AMBOSO_API_LVL\033[0;32m ]; min is { \033[1;36m$expected_AMBOSO_API_LVL\033[0;32m }.\e[0m" >&2
+}
+fi
+[[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]    Printing active flags:\e[0m" >&2 && echo_active_flags
 main_at=144
 #PROG_START_LINE
 prog_start_line="144"
@@ -177,16 +191,13 @@ PARENT_COMMAND=$(ps -o comm= $PPID)
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;37m[PREP]    Parent command is: ( $PARENT_COMMAND ).\e[0m"
 
 
-
-
-
 #Won't print call info for top level calls
 if [[ ${AMBOSO_LVL_REC} -gt 1 ]] ; then {
 #and 1+ nested test calls ( with -T, from -t calling -T)
   [[ $quiet_flag -eq 0 && $verbose_flag -gt 0 ]] && echo -e "\033[1;34m[AMBOSO]    Amboso depth: ( $((${AMBOSO_LVL_REC}-1)) )\e[0m"
   if [[ $AMBOSO_LVL_REC -lt 2 ]] ; then {
     echo -e "\\n\n        args: (\"$@\")" >&2
-    echo_current_tags >&2
+    echo_active_flags >&2
   } elif [[ $AMBOSO_LVL_REC -gt 2 ]] ; then {
     [[ $test_info_was_set -eq 1 ]] && echo -e "[AMBOSO]    Deep recursion (>1), are you calling \"$prog_name\" in a test? ;)" >&2
     #[[ $small_test_mode_flag -gt 0 ]] && echo "[ERROR]    Can't proceed and macro -t for -T on all tags." && exit 69
@@ -196,10 +207,10 @@ if [[ ${AMBOSO_LVL_REC} -gt 1 ]] ; then {
 }
 fi
 
-if [[ $version_flag -gt 1 ]] ; then {
+if [[ $version_flag -eq 1 ]] ; then {
   echo_amboso_version_short
   exit 0
-} elif [[ $version_flag -eq 1 ]] ; then {
+} elif [[ $version_flag -gt 1 ]] ; then {
   echo_amboso_version
   exit 0
 }
@@ -271,10 +282,10 @@ if [[ $smallhelp_flag -gt 0 ]]; then {
     exit 1
   }
   fi
-  (echo_amboso_version
-  set_source_info "$milestones_dir"
-  set_supported_versions "$milestones_dir"
-  usage) | less
+  echo_amboso_version
+  usage
+
+  echo -e "Try running with with -H for more info.\n"
   #"$prog_name" -H -D "$milestones_dir" | less
   exit 0
 }
@@ -289,7 +300,7 @@ if [[ $bighelp_flag -gt 0 ]]; then {
   echo_amboso_version
   set_source_info "$milestones_dir"
   set_supported_versions "$milestones_dir"
-  usage
+  amboso_help
   exit 0
 }
 fi
