feat: refactor subcommands to be handled after getopts

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -4039,6 +4039,125 @@ amboso_parse_args() {
   }
   fi
 
+  for tot_opts_idx in $(seq 0 $(( $tot_opts - 2 )) ); do {
+    shift
+  }
+  done
+  if [[ $# -ge 1 ]] ; then {
+      if [[ $1 = "help" ]] ; then {
+          amboso_help
+          exit 0
+      } elif [[ $1 = "version" ]] ; then {
+          echo_amboso_version_short
+          exit 0
+      } elif [[ $1 = "build" ]] ; then {
+          log_cl "Doing build subcommand" debug
+          build_flag=1
+          shift
+      } elif [[ $1 = "test" ]] ; then {
+          log_cl "Doing test subcommand" debug
+          shift
+          if [[ $# -ge 1 ]] ; then {
+              test_mode_flag=1
+          } else {
+              small_test_mode_flag=1
+          }
+          fi
+      } elif [[ $1 = "init" ]] ; then {
+          log_cl "Doing init subcommand" debug
+          shift
+          local kern=""
+          if [[ -z "$queried_amboso_kern" ]] ; then {
+              kern="amboso-C"
+          } else {
+              kern="$queried_amboso_kern";
+          }
+          fi
+          if [[ "$kern" = "custom" ]] ; then {
+              if [[ $# -gt 1 ]] ; then {
+                  (amboso_init_proj "$kern" "$1" 0 "$2")
+                  #FIXME
+                  #We pass 0 to NOT have strict behaviour anymore. Currently, we can't actually pass --strict in any way.
+                  #This changes from 2.0.0, but we can't run the backwards-compatible code without refactoring the logic to pass in flags with subcommands
+                  exit $?
+              } else {
+                  log_cl "Missing template name" error
+                  log_cl "Usage: amboso -k custom init $1 <TEMPLATE>" error
+                  exit "${amboso_exit_codes[invalid_arg]}"
+              }
+              fi
+          } else {
+
+            (amboso_init_proj "$kern" "$1" 0)
+            #FIXME
+            #We pass 0 to NOT have strict behaviour anymore. Currently, we can't actually pass --strict in any way.
+            #This changes from 2.0.0, but we can't run the backwards-compatible code without refactoring the logic to pass in flags with subcommands
+            exit $?
+          }
+          fi
+      } elif [[ $1 = "cgen" ]] ; then {
+          shift
+          if [[ $# -ge 2 ]] ; then {
+              log_cl "Doing cgen subcommand" debug
+              gen_headers_set=1
+              gen_headers_flag=1
+              gen_headers_destdir="$1"
+              shift
+          } else {
+              log_cl "Missing arguments for cgen subcommand" error
+              exit "${amboso_exit_codes[invalid_arg]}"
+          }
+          fi
+      } elif [[ $1 = "delete" ]] ; then {
+          log_cl "Doing delete subcommand" debug
+          delete_flag=1
+          shift
+      } elif [[ $1 = "run" ]] ; then {
+          log_cl "Doing run subcommand" debug
+          run_flag=1
+          shift
+      } elif [[ $1 = "purge" ]] ; then {
+          log_cl "Doing purge subcommand" debug
+          purge_flag=1
+          shift
+      } elif [[ $1 = "stego" ]] ; then {
+          shift
+          if [[ $# -ge 2 ]] ; then {
+              if [[ $1 = "parse" ]] ; then {
+                  be_stego_parser_flag=1
+              } elif [[ $1 = "lex" ]] ; then {
+                  be_stego_parser_flag=1
+                  big_list_flag=1
+              } elif [[ $1 = "lint" ]] ; then {
+                  be_stego_parser_flag=1
+                  list_flag=1
+              } else {
+                  log_cl "Unexpected mode for stego subcommand: {$1}" error
+                  exit "${amboso_exit_codes[invalid_arg]}"
+              }
+              fi
+              queried_stego_filepath="$2"
+          } else {
+              log_cl "Missing arguments for stego subcommand" error
+              exit "${amboso_exit_codes[invalid_arg]}"
+          }
+          fi
+      } else {
+          #local strict_regex='^([1-9][0-9]*|0)\.([1-9][0-9]*|0)\.([1-9][0-9]*|0)$'
+          #if [[ $1 =~ $strict_regex ]] ; then {
+          #    #We let semver args through
+          #    :
+          #} else {
+          #  log_cl "Unknown subcommand: $1" error
+          #  exit "${amboso_exit_codes[invalid_arg]}"
+          #}
+          #fi
+          :
+      }
+      fi
+  }
+  fi
+
   if [[ $be_stego_parser_flag -eq 1 ]] ; then {
       filepath="$queried_stego_filepath"
 
@@ -4593,10 +4712,6 @@ amboso_parse_args() {
   #check arg num
   # nothing else is allowed
   #shift all the options
-  for tot_opts_idx in $(seq 0 $(( $tot_opts - 2 )) ); do {
-    shift
-  }
-  done
 
   # $0 is now target version, at position 1 in the array ??
   v_pos=1
@@ -4613,16 +4728,6 @@ amboso_parse_args() {
   }
   fi
 
-  if [[ "$1" = "test" ]]; then {
-      if [[ $tot_left_args -gt 2 ]] ; then {
-          log_cl "\n    Unknown argument: \"$3\" (ignoring other $(($tot_left_args-2)) args).\n" error
-          amboso_usage
-          echo_timer "$amboso_start_time"  "Unknown arg [$3]" "1"
-          exit "${amboso_exit_codes[invalid_arg]}"
-      }
-      fi
-  }
-  fi
   tot_left_args=$(( $# ))
   shift # Shift over query
   if [[ $tot_left_args -gt 1 ]]; then {
