feat: quit early on dirty git status

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -360,6 +360,15 @@ if [[ $base_mode_flag -gt 0 ]] ; then {
 fi
 if [[ $git_mode_flag -gt 0 ]] ; then {
   git_mode_check
+  git_mode_check_res="$?"
+  if [[ $git_mode_check_res -eq 0 ]]; then {
+  	[[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[GIT]    Status was clean.\e[0m" >&2
+  } else {
+  	echo -e "\033[1;31m[GIT]    Status was not clean!\e[0m" >&2
+  	echo -e "\033[1;31m[AMBOSO]    Aborting.\e[0m" >&2
+	exit 1
+  }
+  fi
 }
 fi
 
