feat: Added test mode
New mandatory argument passed with -T is test directory name.
If arg is missing, first we check if we're on amboso >1.1.2+, if so we first try for "./kazoj", then we read from stego.lock.

Test mode should ATM override -prib, as it will make amboso quit before reaching any of those stages.
For now, the actual test routine is just a mock up recording the two available tests.

kazoj.lock houses dirnames for the case folder and the errorcase folder.

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -3,6 +3,8 @@
 
 prog_name="$0"
 amboso_version="amboso version 1.1.2"
+amboso_currvers="1.1.2"
+amboso_testflag_version="1.1.2"
 
 function echo_amboso_version {
   echo "$amboso_version"
@@ -10,7 +12,7 @@ function echo_amboso_version {
 
 function set_supported_versions {
   dir=$1
-  [[ ! -f $dir/stego.lock ]] && echo -e "[ERROR]    Can't find \"stego.lock\" in ( $dir ).\n" && exit 1
+  [[ ! -f $dir/stego.lock ]] && echo -e "\033[1;31m[ERROR]    Can't find \"stego.lock\" in ( $dir ).\e[0m\n" && exit 1
   git_tags_count=0
   base_tags_count=0
   j=0
@@ -18,8 +20,8 @@ function set_supported_versions {
   i=0
 
   while IFS= read -r line; do {
-    #Skip the first four lines, reserved for header, source file and target executable names, and versions header
-    [[ $j -lt 5 ]] && j=$((j+1)) && continue
+    #Skip the first five lines, reserved for header, source file and target executable names, test folder, and versions header
+    [[ $j -lt 6 ]] && j=$((j+1)) && continue
 
     was_git_tag=0
     was_base_tag=0
@@ -69,7 +71,7 @@ function set_supported_versions {
 
 function set_source_info {
   dir=$1
-  [[ ! -f $dir/stego.lock ]] && echo -e "[ERROR]    Can't find \"stego.lock\" in ( $dir ). Try running with -D to specify the right directory.\n" && exit 1
+  [[ ! -f $dir/stego.lock ]] && echo -e "\033[1;31m[ERROR]    Can't find \"stego.lock\" in ( $dir ). Try running with -D to specify the right directory.\e[0m\n" && exit 1
   j=0
   k=0
   while IFS= read -r line; do
@@ -80,12 +82,107 @@ function set_source_info {
     #echo "Text read from file, no comments: ( $( echo "$line" | cut -d '#' -f 1 ) )"
     sources_info[k]=$(echo "$line" | cut -d '#' -f 1 | cut -d ' ' -f 1 )
     k=$((k+1))
-    [[ $k -eq 3 ]] && break #we only read the first two lines
+    [[ $k -eq 4 ]] && break #we only read the first three lines
   done < "$dir/stego.lock" 2>/dev/null
   #echo "source info array size is " "${#sources_info[@]}" >&2
   count_source_infos="${#sources_info[@]}"
   #echo "$count_source_infos"
   #echo "source info array contents are: ( ${sources_info[@]} )" >&2
+}
+
+function set_tests_info {
+  dir="$1"
+  [[ ! -f "$dir"/kazoj.lock ]] && echo -e "\033[1;31m[ERROR]    Can't find \"kazoj.lock\" in ( $dir ). Try running with -T to specify the right directory.\e[0m\n" && exit 1
+  j=0
+  k=0
+  while IFS="\n" read -r line; do
+    #Skip the first and third line header
+    [[ $j -lt 1 || $j -eq 2 ]] && j=$((j+1)) && continue
+    #echo "Text read from file: ( $line )"
+    #echo "Text read from file, no comments: ( $( echo "$line" | cut -d '#' -f 1 ) )"
+    tests_info[k]=$(echo "$line" | cut -d '#' -f 1 | cut -d ' ' -f 1 )
+    k=$((k+1))
+    j=$((j+1))
+    [[ $k -lt 2 ]] || break #we only read two values
+  done < "$dir/kazoj.lock" 2>/dev/null
+  #echo "test info array size is " "${#tests_info[@]}" >&2
+  count_tests_infos="${#tests_info[@]}"
+  #echo "$count_tests_infos"
+  #echo "test info array contents are: ( ${tests_info[@]} )" >&2
+}
+
+function set_supported_tests {
+  kazoj_dir=$1
+  set_tests_info "$1"
+  cases_dir="${tests_info[0]}"
+  errors_dir="${tests_info[1]}"
+  tests_filecount=0
+  errors_filecount=0
+  skipped=0
+  i=0
+
+  #tests loop
+  cases_path="$kazoj_dir/$cases_dir"
+  errorcases_path="$kazoj_dir/$errors_dir"
+  for FILE in $(ls "$cases_path"); do {
+    test_fp="$cases_path/$FILE"
+    if ! [[ -f $test_fp && -x $test_fp ]] ; then {
+      skipped=$((skipped+1))
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Ignoring test $FILE (at $test_fp), not an executable file.\e[0m" >&2
+      continue
+    }
+    fi
+    read_tests_files["$tests_filecount"]="$test_fp"
+    tests_filecount=$(($tests_filecount+1))
+  }
+  done
+  #errors loop
+  for FILE in $(ls "$errorcases_path"); do {
+    test_fp="$errorcases_path/$FILE"
+    if ! [[ -f $test_fp && -x $test_fp ]] ; then {
+      skipped=$((skipped+1))
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Ignoring errtest $FILE (at $test_fp), not an executable file.\e[0m" >&2
+      continue
+    }
+    fi
+    read_errortest_files["$errors_filecount"]="$test_fp"
+    errors_filecount=$(($errors_filecount+1))
+  }
+  done
+  #echo "version array size is " "${#read_versions[@]}" >&2
+  count_tests_names="${#read_tests_files[@]}"
+  count_errortests_names="${#read_errortest_files[@]}"
+  for i in $(seq 0 $(($count_tests_names-1))); do
+    supported_tests[i]=${read_tests_files[$i]}
+  done
+  for i in $(seq 0 $(($count_errortests_names-1))); do
+    supported_tests[$(($i + $count_tests_names))]=${read_errortest_files[$i]}
+  done
+  tot_tests=${#supported_tests[@]}
+  #echo "tot tests: $tot_tests"
+}
+
+function echo_tests_info {
+  kazoj_dir="$1"
+  set_supported_tests "$kazoj_dir" 2>/dev/null
+  echoed_cases_dir="${tests_info[0]}"
+  echoed_errors_dir="${tests_info[1]}"
+  echo -e "\033[1;33m[DEBUG]    Tests dir is: ( $kazoj_dir ).\e[0m" >&2
+  echo -e "\033[1;33m[DEBUG]    Cases dir is: ( $echoed_cases_dir ).\e[0m" >&2
+  echo -e "\033[1;33m[DEBUG]    ( $count_tests_names ) cases ready.\e[0m" >&2
+  for i in $(seq 0 $(($count_tests_names-1))) ; do {
+    echo -e "\033[1;33m[DEBUG]      ( ${read_tests_files[$i]} ).\e[0m" >&2
+  }
+  done
+  echo -e "\033[1;33m[DEBUG]    Errors dir is: ( $echoed_errors_dir ).\e[0m" >&2
+  echo -e "\033[1;33m[DEBUG]    ( $count_errortests_names ) error cases ready.\e[0m" >&2
+  for i in $(seq 0 $(($count_errortests_names-1))) ; do {
+    echo -e "\033[1;33m[DEBUG]      ( ${read_errortest_files[$i]} ).\e[0m" >&2
+  }
+  done
+  echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
+  #echo "$count_tests_infos"
+  #echo "test info array contents are: ( ${tests_info[@]} )" >&2
 }
 
 function echo_othermode_tags {
@@ -136,6 +233,8 @@ function echo_options {
   echo -e "                Uses full source builds. Not recommended.\n"
   echo -e "        -g        git mode\n"
   echo -e "                Uses git checkouts of supported tags. Enabled by default.\n"
+  echo -e "        -t        test mode\n"
+  echo -e "                Tries all defined tests.\n"
   echo -e "    [OPERATIONS]:\n"
   echo -e "        -b        build\n"
   echo -e "                Tries building the binary if it's not available.\n"
@@ -156,6 +255,8 @@ function echo_options {
   echo -e "                Specifies sourcefile name for single file mode.\n"
   echo -e "        -M MAKEFILE_SUPPORT       tagname\n"
   echo -e "                Specifies a tag name for lowest version to support make.\n"
+  echo -e "        -T TEST_FOLDER       path\n"
+  echo -e "                Specifies a relative dirname for test folder.\n"
   echo -e "    [INFO]:\n"
   echo -e "        -l/L        list\n"
   echo -e "                Prints supported tags for current mode (all modes if L) and quits.\n"
@@ -185,6 +286,12 @@ function usage {
   echo_options
 }
 
+function record_test {
+  tfp="$1" # test_file_path
+  ( "$tfp" >"$tfp".stdout 2>"$tfp".stderr )
+  #TODO: get return code
+}
+
 #Prepare flag values to default value
 purge_flag=0
 run_flag=0 #By default we don't run the binary
@@ -203,10 +310,13 @@ vers_make_flag=0
 makefile_version=""
 git_mode_flag=1 #By default we run in git mode
 base_mode_flag=0
+test_mode_flag=0
+testdir_flag=0
+kazoj_dir=""
 big_list_flag=0
 small_list_flag=0
 
-while getopts "M:S:E:D:BgVbpHhrivdlL" opt; do
+while getopts "M:S:E:D:T:BgVbpHhrivdlLt" opt; do
   case $opt in
     S )
       source_name="$OPTARG"
@@ -219,6 +329,10 @@ while getopts "M:S:E:D:BgVbpHhrivdlL" opt; do
     D )
       dir_flag=1
       milestones_dir="$OPTARG"
+      ;;
+    T )
+      testdir_flag=1
+      kazoj_dir="$OPTARG"
       ;;
     M )
       vers_make_flag=1
@@ -241,6 +355,9 @@ while getopts "M:S:E:D:BgVbpHhrivdlL" opt; do
       ;;
     g )
       git_mode_flag=1
+      ;;
+    t )
+      test_mode_flag=1
       ;;
     V )
       verbose_flag=1
@@ -276,6 +393,14 @@ while getopts "M:S:E:D:BgVbpHhrivdlL" opt; do
 tot_opts=$OPTIND
 done
 
+#We check again if testmode was requested, and reset the other mode flags.
+if [[ $test_mode_flag -gt 0 ]] ; then {
+  git_mode_flag=0
+  base_mode_flag=0
+  echo -e "\033[1;33m[AMBOSO-MODE]    Running in test mode.\e[0m" >&2
+}
+fi
+
 #We check again if basemode was requested, as the only flag checked in build stage is git_mode_flag
 #If base_mode_flag is asserted, we always override git_mode_flag
 [[ $base_mode_flag -gt 0 ]] && git_mode_flag=0 && echo -e "\033[1;31m[AMBOSO-MODE]    Running in base mode, expecting full source builds.\e[0m" >&2
@@ -283,21 +408,6 @@ done
 
 #We always notify of missing -D argument
 [[ ! $dir_flag -gt 0 ]] && milestones_dir="$(pwd)/bin/" && echo -e "\033[1;33m[DEBUG]    No -D flag, using ( $milestones_dir ) for target dir. Run with -V to see more.\e[0m" >&2 #&& usage && exit 1
-
-#Check if we are printing tag list for current mode and exiting early
-if [[ $small_list_flag -gt 0 ]]; then {
-  echo_supported_tags "$milestones_dir"
-  exit 0
-}
-fi
-
-#Check if we are printing tag list for both modes and exiting early
-if [[ $big_list_flag -gt 0 ]]; then {
-  echo_supported_tags "$milestones_dir"
-  echo_othermode_tags "$milestones_dir"
-  exit 0
-}
-fi
 
 #Check if we are printing help info and exiting early
 if [[ $smallhelp_flag -gt 0 ]]; then {
@@ -317,6 +427,56 @@ fi
 
 scripts_dir="$milestones_dir" # MUST BE SET before checking for -S and -E
 set_supported_versions "$scripts_dir" # Might as well do it now
+
+#If we're in test mode and test dir was not passed, we check if "./kazoj" is a directory and use that. If it isn't, we may get the name from stego.lock. If that is not a directory, we quit immediately.
+if [[ -z $kazoj_dir && $test_mode_flag -gt 0 ]] ; then {
+  if [[ "$amboso_currvers" > "$amboso_testflag_version" ||
+        "$amboso_currvers" = "$amboso_testflag_version" ]] ; then {
+     if [[ -d "./kazoj" ]]; then {
+       kazoj_dir=$(realpath "./kazoj")
+       set_tests_info "$kazoj_dir"
+       set_supported_tests "$kazoj_dir"
+       echo -e "\033[1;33m[DEBUG]    No -T flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m" >&2
+     } else {
+       echo -e "\033[1;33m[DEBUG]    No -T flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
+       set_source_info "$milestones_dir"
+       kazoj_dir=${sources_info[3]}
+       set_tests_info "$kazoj_dir"
+       set_supported_tests "$kazoj_dir"
+       #echo_tests_info "$tests_dir"
+     }
+     fi
+  } else {
+     echo -e "\033[1;31m[ERROR]    No -T flag on a test run, amboso version is < ($amboso_testflag_version).\n    Quitting.\e[0m" #>&2
+  }
+  fi
+}
+fi
+
+#Check if we are printing tag list for current mode and exiting early
+if [[ $small_list_flag -gt 0 ]]; then {
+  if [[ $git_mode_flag -gt 0 || $base_mode_flag -gt 0 ]] ; then {
+    echo_supported_tags "$milestones_dir"
+  } elif [[ $test_mode_flag -gt 0 ]]; then {
+    echo_tests_info "$kazoj_dir"
+  }
+  fi
+  exit 0
+}
+fi
+
+#Check if we are printing tag list for both modes and exiting early
+if [[ $big_list_flag -gt 0 ]]; then {
+  if [[ $git_mode_flag -gt 0 || $base_mode_flag -gt 0 ]] ; then {
+    echo_supported_tags "$milestones_dir"
+    echo_othermode_tags "$milestones_dir"
+  } elif [[ $test_mode_flag -gt 0 ]]; then {
+    echo_tests_info "$kazoj_dir"
+  }
+  fi
+  exit 0
+}
+fi
 
 #If version for makefile support was not specified, it's read from the stego.lock (an empty value would work maybe)
 if [[ -z $makefile_version ]] ; then {
@@ -347,6 +507,21 @@ fi
 [[ $verbose_flag -gt 0 && ! $exec_was_set -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using target bin: ( $exec_entrypoint ).\e[0m" >&2
 [[ $verbose_flag -gt 0 && ! $sourcename_was_set -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using source file name: ( $source_name ).\e[0m" >&2
 [[ $verbose_flag -gt 0 && ! $vers_make_flag -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using tag for make support: ( $makefile_version ) as first tag compiled with make.\e[0m" >&2
+[[ $test_mode_flag -gt 0 && ! $testdir_flag -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using tests dir: ( $kazoj_dir ).\e[0m" >&2
+
+#Check if we are doing a test
+if [[ $test_mode_flag -gt 0 ]] ; then {
+  relative_testpath="${supported_tests[0]}"
+  echo "[TEST]    recording: ( $relative_testpath )."
+  record_test "$relative_testpath"
+  relative_testpath="${supported_tests[1]}"
+  echo "[TEST]    recording: ( $relative_testpath )."
+  record_test "$relative_testpath"
+  echo "[TEST]    Done testing, we quit."
+  #TODO: run test
+  exit 0;
+}
+fi
 
 #Check if we are doing init
 if [[ $init_flag -gt 0 ]] ; then {
@@ -418,11 +593,15 @@ if [[ $tot_left_args -gt 1 ]]; then {
 }
 fi
 
-#If we don't have init or purge flag, we bail on a missing version argument
-if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 ]]; then {
+#If we don't have init or purge flag, and we are not in test mode, we bail on a missing version argument
+if [[ $tot_left_args -lt 1 && $test_mode_flag -eq 0 && $purge_flag -eq 0 && $init_flag -eq 0 ]]; then {
   echo -e "\033[1;31m[ERROR]    Missing version query.\e[0m\n"
   echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
   exit 1
+} elif [[ $tot_left_args -lt 1 && $test_mod_flag -gt 0 ]] ; then {
+  #If in test mode, whine about a target test
+  echo -e "\033[1;31m[ERROR]    Missing test query.\e[0m\n"
+  echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
 }
 fi
 
@@ -433,12 +612,12 @@ for i in $(seq 0 $(($tot_vers-1))); do
 done
 
 if [[ -z $version ]]; then {
-  #We only freak out if we don't have purge or init flags on
-  if [[ $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
+  #We only freak out if we don't have test_mode, purge or init flags on
+  if [[ $test_mode_flag -eq 0 && $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
     echo -e "\033[1;31m[ERROR]    ( $queried_version ) is not a supported tag.\e[0m\n"
     echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
     exit 1
-  } elif [[ ! -z $queried_version ]] ; then { #We gently tell the user that the version is not supported
+  } elif [[ ! -z $queried_version && $test_mode_flag -eq 0 ]] ; then { #If we're not in test mode, gently tell the user that the version is not supported
     keep_run_txt=""
     [[ $init_flag -gt 0 ]] && keep_run_txt="$mode_txt[INIT]"
     [[ $purge_flag -gt 0 ]] && keep_run_txt="$mode_txt[PURGE]"
@@ -473,7 +652,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Building ( $version ), using make.\e[0m" >&2
       curr_dir=$(realpath .)
       start_t=`date +%s.%N`
-      if [[ $git_mode_flag -eq 0 ]] ; then { #Building in base mode, we cd into target directory before make
+      if [[ $git_mode_flag -eq 0 && $base_mode_flag -eq 1 ]] ; then { #Building in base mode, we cd into target directory before make
         [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m" #>&2
         cd $script_path; make >&2
         comp_res=$?
@@ -683,4 +862,4 @@ if [[ purge_flag -gt 0 ]]; then
   fi
 fi
 
-exit 0
+exie 0
