feat: improve sourcing check

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -106,21 +106,37 @@ source_amboso_api() {
   [ "$verbose_flag" -gt 1 ] && printf "[PREP]    \"\$AMBOSO_API_LVL\" is: ( %s , expected { %s } ).\n" "$AMBOSO_API_LVL" "$expected_AMBOSO_API_LVL" >&2
   [ "$tell_uname_flag" -eq 1 ] && print_sysinfo
   if expr "'$expected_AMBOSO_API_LVL" \> "'$AMBOSO_API_LVL" >/dev/null ; then {
-    printf "[PANIC]    AMBOSO_API_LVL not supported. Needed { %s } , { %s } is too low.\n\n    Maybe check your \"amboso_fn.sh\" file.\n\n" "$expected_AMBOSO_API_LVL" "$AMBOSO_API_LVL"
+    printf "[PANIC]    Unexpected AMBOSO_API_LVL. Needed { %s } , { %s } is too low.\n\n    Check your \"amboso_fn.sh\" file.\n\n" "$expected_AMBOSO_API_LVL" "$AMBOSO_API_LVL"
+    lesser_res=255
     if [[ "$AMBOSO_API_LVL" < "1.4.3" ]] ; then {
-       printf "[WARN]    amboso_fn.sh does not contain AMBOSO_API_LVL.\n"
+        printf "[WARN]    amboso_fn.sh does not contain AMBOSO_API_LVL.\n"
+        lesser_res=1
     } elif [[ "$AMBOSO_API_LVL" > "1.4.2" && "$AMBOSO_API_LVL" < "1.6.6" ]] ; then {
-       printf "[WARN]    Unstable amboso version detected.\n"
+        printf "[WARN]    Unstable amboso version detected.\n"
+        lesser_res=2
     } elif [[ "$AMBOSO_API_LVL" > "1.6.5" && "$AMBOSO_API_LVL" < "1.7.4" ]] ; then {
-       printf "[WARN]    Legacy stego.lock format is not supported.\n"
+        printf "[WARN]    Legacy stego.lock format is not supported.\n"
+        lesser_res=3
     } elif [[ "$AMBOSO_API_LVL" > "1.7.4" && "$AMBOSO_API_LVL" < "1.9.6" ]] ; then {
-       printf "[WARN]    Incompatible -C flag, test mode\n"
-    } elif [[ "$AMBOSO_API_LVL" < "2.0.2" ]] ;  then {
-       printf "[WARN]    Deprecated amboso 1.x API found.\n"
+        printf "[WARN]    Incompatible -C flag, test mode\n"
+        lesser_res=4
+    } elif [[ "$AMBOSO_API_LVL" < "2.0.0" ]] ;  then {
+        printf "[WARN]    Deprecated amboso 1.x API found.\n"
+        lesser_res=5
+    } elif [[ "$AMBOSO_API_LVL" = "2.0.0" ]] ; then {
+        printf "[WARN]    Minimal amboso 2.0 API found.\n"
+        lesser_res=0
+    } elif [[ "$AMBOSO_API_LVL" < "2.1" ]] ; then {
+        printf "[WARN]    Minimal amboso 2.0.x API found.\n"
+        lesser_res=0
     }
     fi
-    printf "[PANIC]    Could not load functions. Quitting.\n"
-    exit 2
+    if [[ "$lesser_res" -ne 0 ]] ; then {
+        printf "[PANIC]    Could not load functions. Quitting.\n"
+        exit "$lesser_res"
+        exit 1
+    }
+    fi
   } elif expr "'$AMBOSO_API_LVL" \> "'$expected_AMBOSO_API_LVL" >/dev/null ; then {
     [ "$verbose_flag" -gt 0 ] && printf "[WARN]    AMBOSO_API_LVL is greater than expected. Needed { %s } , { %s } is higher.\n" "$expected_AMBOSO_API_LVL" "$AMBOSO_API_LVL" >&2
     [ "$verbose_flag" -gt 0 ] && printf "\n[WARN]    Continuing run with unexpected AMBOSO_API_LVL: Needed { %s } , { %s } is higher.\n" "$expected_AMBOSO_API_LVL" "$AMBOSO_API_LVL"
