feat: test mode flags, WIP
ATM the test run just displays diff information.
The last if condition is still hanging. Mostly working.

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,7 +2,7 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
-amboso_version="amboso version 1.1.2"
+amboso_version="amboso version 1.2.0-devel"
 amboso_currvers="1.1.2"
 amboso_testflag_version="1.1.2"
 
@@ -132,7 +132,7 @@ function set_supported_tests {
       continue
     }
     fi
-    read_tests_files["$tests_filecount"]="$test_fp"
+    read_tests_files["$tests_filecount"]="$FILE"
     tests_filecount=$(($tests_filecount+1))
   }
   done
@@ -145,18 +145,18 @@ function set_supported_tests {
       continue
     }
     fi
-    read_errortest_files["$errors_filecount"]="$test_fp"
+    read_errortests_files["$errors_filecount"]="$FILE"
     errors_filecount=$(($errors_filecount+1))
   }
   done
   #echo "version array size is " "${#read_versions[@]}" >&2
   count_tests_names="${#read_tests_files[@]}"
-  count_errortests_names="${#read_errortest_files[@]}"
+  count_errortests_names="${#read_errortests_files[@]}"
   for i in $(seq 0 $(($count_tests_names-1))); do
     supported_tests[i]=${read_tests_files[$i]}
   done
   for i in $(seq 0 $(($count_errortests_names-1))); do
-    supported_tests[$(($i + $count_tests_names))]=${read_errortest_files[$i]}
+    supported_tests[$(($i + $count_tests_names))]=${read_errortests_files[$i]}
   done
   tot_tests=${#supported_tests[@]}
   #echo "tot tests: $tot_tests"
@@ -169,17 +169,23 @@ function echo_tests_info {
   echoed_errors_dir="${tests_info[1]}"
   echo -e "\033[1;33m[DEBUG]    Tests dir is: ( $kazoj_dir ).\e[0m" >&2
   echo -e "\033[1;33m[DEBUG]    Cases dir is: ( $echoed_cases_dir ).\e[0m" >&2
-  echo -e "\033[1;33m[DEBUG]    ( $count_tests_names ) cases ready.\e[0m" >&2
-  for i in $(seq 0 $(($count_tests_names-1))) ; do {
-    echo -e "\033[1;33m[DEBUG]      ( ${read_tests_files[$i]} ).\e[0m" >&2
+  echo -e "\033[1;33m[DEBUG]      ( $count_tests_names ) cases ready.\e[0m" >&2
+  if [[ $big_list_flag -gt 0 ]] ; then {
+    for i in $(seq 0 $(($count_tests_names-1))) ; do {
+      echo -e "\033[1;33m[DEBUG]      ( ${read_tests_files[$i]} ).\e[0m" >&2
+    }
+    done
   }
-  done
+  fi
   echo -e "\033[1;33m[DEBUG]    Errors dir is: ( $echoed_errors_dir ).\e[0m" >&2
-  echo -e "\033[1;33m[DEBUG]    ( $count_errortests_names ) error cases ready.\e[0m" >&2
-  for i in $(seq 0 $(($count_errortests_names-1))) ; do {
-    echo -e "\033[1;33m[DEBUG]      ( ${read_errortest_files[$i]} ).\e[0m" >&2
+  echo -e "\033[1;33m[DEBUG]      ( $count_errortests_names ) error cases ready.\e[0m" >&2
+  if [[ $big_list_flag -gt 0 ]] ; then {
+    for i in $(seq 0 $(($count_errortests_names-1))) ; do {
+      echo -e "\033[1;33m[DEBUG]      ( ${read_errortests_files[$i]} ).\e[0m" >&2
+    }
+    done
   }
-  done
+  fi
   echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
   #echo "$count_tests_infos"
   #echo "test info array contents are: ( ${tests_info[@]} )" >&2
@@ -286,10 +292,53 @@ function usage {
   echo_options
 }
 
+function escape_colorcodes {
+  file="$1"
+  outfile="$2"
+  echo "" >"$outfile"
+  #sed -r 's/\/\\3/g' "$file"
+  #sed -e 's/\\033\[/COLOR[/g' -e 's/COLOR\[1;3/"<colorTag[Heavy,/g' -e 's/COLOR\[0;3/"<colorTag[Light,/g' -e 's/\\e\[0m/\]>"/g' "$file" >>"$outfile"
+  #sed 's/\x1B\[\([0-9]\{1,2\}\(;[0-9]\{1,2\}\)\?\)\?[mGK]//g' <"$file"
+  cat -e "$file" >"$outfile"
+}
+
 function record_test {
   tfp="$1" # test_file_path
-  ( "$tfp" >"$tfp".stdout 2>"$tfp".stderr )
-  #TODO: get return code
+  echo "" > "$tfp.stdout"
+  echo "" > "$tfp.stderr"
+  tmp_stdout="$(mktemp)"
+  tmp_stderr="$(mktemp)"
+  run_test "$tfp" >>"$tmp_stdout" 2>>"$tmp_stderr"
+  res=$?
+  echo "r: $res" >> "$tmp_stdout"
+  escape_colorcodes "$tmp_stdout" "$tfp.stdout"
+  escape_colorcodes "$tmp_stderr" "$tfp.stderr"
+  rm -f "$tmp_stdout" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($tmp_stdout). Why?\n"
+  rm -f "$tmp_stderr" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($tmp_stderr). Why?\n"
+}
+
+function run_test {
+  tfp="$1" # test_file_path
+  #echo -en "\033[1;36m"
+  ( "$tfp" )
+  #echo -en "\e[0m"
+  res=$?
+}
+
+function delete_test {
+  tfp="$1" # test_file_path
+  (
+    echo "deleting $tfp" 2>/dev/null
+    exit "$?"
+  )
+  res="$?"
+
+  if [[ $res -eq 0 ]]; then {
+    echo -e "\033[0;32m[TEST]    Deleted $tfp.\e[0m" >&2
+  } else {
+    echo -e "\033[1;31m[TEST]    Failed deleting $tfp. How?\e[0m" >&2
+  }
+  fi
 }
 
 #Prepare flag values to default value
@@ -509,22 +558,9 @@ fi
 [[ $verbose_flag -gt 0 && ! $vers_make_flag -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using tag for make support: ( $makefile_version ) as first tag compiled with make.\e[0m" >&2
 [[ $test_mode_flag -gt 0 && ! $testdir_flag -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using tests dir: ( $kazoj_dir ).\e[0m" >&2
 
-#Check if we are doing a test
-if [[ $test_mode_flag -gt 0 ]] ; then {
-  relative_testpath="${supported_tests[0]}"
-  echo "[TEST]    recording: ( $relative_testpath )."
-  record_test "$relative_testpath"
-  relative_testpath="${supported_tests[1]}"
-  echo "[TEST]    recording: ( $relative_testpath )."
-  record_test "$relative_testpath"
-  echo "[TEST]    Done testing, we quit."
-  #TODO: run test
-  exit 0;
-}
-fi
-
-#Check if we are doing init
-if [[ $init_flag -gt 0 ]] ; then {
+#Check if we are doing init and we're not in test mode
+#Which means we want to build all tags
+if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
   count_bins=0
   start_t_init=`date +%s.%N`
   for i in $(seq 0 $(($tot_vers-1))); do
@@ -573,6 +609,23 @@ if [[ $init_flag -gt 0 ]] ; then {
 }
 fi
 
+if [[ $init_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
+  echo -e "\033[0;32m[TEST]    -i Will record all tests.\e[0m" >&2
+}
+fi
+if [[ $purge_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
+  echo -e "\033[0;32m[TEST]    -p Will delete all tests.\e[0m" >&2
+}
+fi
+if [[ $build_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
+  echo -e "\033[0;32m[TEST]    -b Will record query.\e[0m" >&2
+}
+fi
+if [[ $delete_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
+  echo -e "\033[0;32m[TEST]    -d Will delete query.\e[0m" >&2
+}
+fi
+
 #Version argument is mandatory outside of purge or init mode
 #check arg num
 # nothing else is allowed
@@ -583,7 +636,7 @@ done
 
 # $0 is now target version, at position 1 in the array ??
 v_pos=1
-queried_version="${!v_pos}"
+query="${!v_pos}"
 
 tot_left_args=$(( $# ))
 if [[ $tot_left_args -gt 1 ]]; then {
@@ -593,35 +646,141 @@ if [[ $tot_left_args -gt 1 ]]; then {
 }
 fi
 
-#If we don't have init or purge flag, and we are not in test mode, we bail on a missing version argument
-if [[ $tot_left_args -lt 1 && $test_mode_flag -eq 0 && $purge_flag -eq 0 && $init_flag -eq 0 ]]; then {
-  echo -e "\033[1;31m[ERROR]    Missing version query.\e[0m\n"
+#If we don't have init or purge flag, we bail on a missing version argument
+if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 ]]; then {
+  echo -e "\033[1;31m[ERROR]    Missing query.\e[0m\n"
   echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
   exit 1
 } elif [[ $tot_left_args -lt 1 && $test_mod_flag -gt 0 ]] ; then {
-  #If in test mode, whine about a target test
+  #If in test mode, we still whine about a target test
   echo -e "\033[1;31m[ERROR]    Missing test query.\e[0m\n"
   echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
+  echo "can we do init/purge?"
+}
+fi
+
+#Check if we are doing a test
+if [[ $test_mode_flag -gt 0 ]] ; then {
+  #We expect $scripts_dir to end with /
+  test_name=""
+  test_type=""
+  test_path=""
+  for i in $(seq 0 $(($count_tests_names-1))); do {
+    current_item="${read_tests_files[$i]}"
+    #echo "checking $current_item"
+    if [[ $query = $current_item ]] ; then {
+      test_type="casetest"
+      test_name="$query"
+      test_path="$kazoj_dir/$cases_dir/${read_tests_files[$i]}"
+      break; #done looking
+    }
+    fi
+  }
+  done
+  [[ -z $test_name ]] && for i in $(seq 0 $(($count_errortests_names-1))); do {
+    current_item="${read_errortests_files[$i]}"
+    #echo "checking $current_item"
+    if [[ $query = $current_item ]] ; then {
+      test_type="errortest"
+      test_name="$query"
+      test_path="$kazoj_dir/$errors_dir/${read_errortests_files[$i]}"
+      break; #done looking
+    }
+    fi
+  }
+  done
+
+  if [[ -z $test_name ]]; then {
+    #We only freak out if we don't have test_mode, purge or init flags on
+    if [[ $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
+      echo -e "\033[1;31m[TEST]    ( $query ) is not a supported test.\e[0m\n"
+      echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
+      exit 1
+    } elif [[ ! -z $query && $test_mode_flag -eq 1 ]] ; then { #If we're in test mode (should be always true here...), gently tell the user that the version is not supported
+      keep_run_txt=""
+      [[ $init_flag -gt 0 ]] && keep_run_txt="$mode_txt[INIT]"
+      [[ $purge_flag -gt 0 ]] && keep_run_txt="$mode_txt[PURGE]"
+      echo -e "\n\033[1;33m[TEST]    ( $query ) is not a supported tag, but we keep running to do $keep_run_txt.\e[0m" >&2
+    }
+    fi
+  } else {
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[TEST] expected:\n  $test_type\n\n  name: $test_name\n  path: $test_path\e[0m" >&2
+    echo -e "\033[0;32m[TEST]    target: ( $test_name ).\e[0m\n"
+  }
+  fi
+
+  relative_testpath="$test_path"
+
+  if [[ $build_flag -gt 0 ]] ; then {
+    echo "[TEST]    recording: ( $relative_testpath )."
+    record_test "$relative_testpath"
+  } elif [[ $delete_flag -gt 0 ]] ; then {
+    echo "[TEST]    deleting: ( $relative_testpath )."
+    delete_test "$relative_testpath"
+  } elif [[ $init_flag -gt 0 ]] ; then {
+    echo "[TEST]    recording all: query ( $relative_testpath )."
+    #init_all_tests "$relative_testpath"
+  } elif [[ $purge_flag -gt 0 ]] ; then {
+    echo "[TEST]    deleting all: query ( $relative_testpath )."
+    #purge_all_tests "$relative_testpath"
+  }
+  fi
+  run_tmp_out="$(mktemp)"
+  run_tmp_escout="$(mktemp)"
+  run_tmp_err="$(mktemp)"
+  run_tmp_escerr="$(mktemp)"
+  run_test "$relative_testpath" >>"$run_tmp_out" 2>>"$run_tmp_out"
+  escape_colorcodes "$run_tmp_out" "$run_tmp_escout"
+  rm -f "$run_tmp_out" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\n"
+  escape_colorcodes "$run_tmp_err" "$run_tmp_escerr"
+  rm -f "$run_tmp_err" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\n"
+  #Testing diff for escaped stdout
+  ( diff "$run_tmp_escout" "$relative_testpath".stdout ) #2>/dev/null 1>&2
+  diff_res="$?"
+  if [[ "$diff_res" -eq 0 ]]; then {
+    echo -e"\n\n\nIIIIIif\n\n"
+    #cat "$run_tmp_escout"
+  } else {
+    echo "\n\n\nELSE\n\n"
+    #cat "$run_tmp_escout"
+  }
+  fi
+  rm -f "$run_tmp_escout" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escout). Why?\n"
+  #Testing diff for escaped stderr
+  ( diff "$run_tmp_escerr" "$relative_testpath".stderr ) #2>/dev/null 1>&2
+  diff_res="$?"
+  if [[ "$diff_res" -eq 0 ]]; then {
+    echo -e"\n\n\nIIIIIif\n\n"
+    #cat "$run_tmp_escerr"
+  } else {
+    echo "\n\n\nELSE\n\n"
+    #cat "$run_tmp_escerr"
+  }
+  fi
+  rm -f "$run_tmp_escerr" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escerr). Why?\n"
+  echo "[TEST]    Done testing, we quit."
+  #TODO: init/purge tests
+  exit 0;
 }
 fi
 
 #We expect $scripts_dir to end with /
 version=""
 for i in $(seq 0 $(($tot_vers-1))); do
-  [[ $queried_version = ${supported_versions[$i]} ]] && version="$queried_version" && script_path=""$scripts_dir"v"$version""
+  [[ $query = ${supported_versions[$i]} ]] && version="$query" && script_path=""$scripts_dir"v"$version""
 done
 
 if [[ -z $version ]]; then {
   #We only freak out if we don't have test_mode, purge or init flags on
   if [[ $test_mode_flag -eq 0 && $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
-    echo -e "\033[1;31m[ERROR]    ( $queried_version ) is not a supported tag.\e[0m\n"
+    echo -e "\033[1;31m[ERROR]    ( $query ) is not a supported tag.\e[0m\n"
     echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
     exit 1
-  } elif [[ ! -z $queried_version && $test_mode_flag -eq 0 ]] ; then { #If we're not in test mode, gently tell the user that the version is not supported
+  } elif [[ ! -z $query && $test_mode_flag -eq 0 ]] ; then { #If we're not in test mode, gently tell the user that the version is not supported
     keep_run_txt=""
     [[ $init_flag -gt 0 ]] && keep_run_txt="$mode_txt[INIT]"
     [[ $purge_flag -gt 0 ]] && keep_run_txt="$mode_txt[PURGE]"
-    echo -e "\n\033[1;33m[DEBUG]    ( $queried_version ) is not a supported tag, but we keep running to do $keep_run_txt.\e[0m" >&2
+    echo -e "\n\033[1;33m[DEBUG]    ( $query ) is not a supported tag, but we keep running to do $keep_run_txt.\e[0m" >&2
   }
   fi
 }
@@ -735,8 +894,8 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
 } elif [[ ! -z $version ]] ; then { #Binary was present, we notify if we were running with build flag
   echo -e "\n\033[1;32m[QUERY]    ( $version ) binary is ready at ( $script_path ) .\e[0m" >&2
   [[ $build_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Found binary for ( $version ), won't build.\e[0m" >&2
-} elif [[ ! -z $queried_version ]] ; then {
-  echo -e "\033[1;31m[QUERY]    ( $queried_version ) invalid query, run with -V to see more.\e[0m"
+} elif [[ ! -z $query ]] ; then {
+  echo -e "\033[1;31m[QUERY]    ( $query ) invalid query, run with -V to see more.\e[0m"
 }
 fi
 
@@ -862,4 +1021,4 @@ if [[ purge_flag -gt 0 ]]; then
   fi
 fi
 
-exie 0
+exit 0
