feat: added version option, moved verbose to -V
feat: updated try_anvil

chore: updated README.md

chore: clarified README.md on using amboso in its own repo

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,6 +2,11 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
+amboso_version="amboso version 1.0.0"
+
+function echo_amboso_version {
+  echo "$amboso_version"
+}
 
 function set_supported_versions {
   dir=$1
@@ -65,8 +70,10 @@ function usage {
   echo -e "                Specifies sourcefile name for single file mode.\n"
   echo -e "        -M MAKEFILE_SUPPORT       tagname\n"
   echo -e "                Specifies a tag name for lowest version to support make.\n"
+  echo -e "        -B        base mode\n"
+  echo -e "                Uses full source builds. Not recommended.\n"
   echo -e "        -g        git mode\n"
-  echo -e "                Uses git checkouts of supported tags.\n"
+  echo -e "                Uses git checkouts of supported tags. Enabled by default.\n"
   echo -e "        -b        build\n"
   echo -e "                Tries building the binary if it's not available.\n"
   echo -e "        -r        run\n"
@@ -75,12 +82,14 @@ function usage {
   echo -e "                Tries building all supported versions.\n"
   echo -e "        -p        purge\n"
   echo -e "                Removes all milestone binaries and quits.\n"
-  echo -e "        -v        verbose\n"
+  echo -e "        -V        verbose\n"
   echo -e "                More debug output.\n"
   echo -e "        -h        help\n"
   echo -e "                Prints help info in paged format.\n"
   echo -e "        -H        help\n"
   echo -e "                Prints help message and quits.\n"
+  echo -e "        -v        version\n"
+  echo -e "                Prints version message and quits.\n"
 }
 
 function git_mode_check {
@@ -89,7 +98,7 @@ function git_mode_check {
   git rev-parse --is-inside-work-tree 2>/dev/null 1>&2
   is_git_repo="$?"
   [[ $is_git_repo -gt 0 ]] && echo -e "\n\033[1;31m[ERROR]    Not running in a git repo. Try running with -B to use base mode.\e[0m\n" && exit 1
-  [[ $verbose_flag -gt 0 ]] && echo -e "\n[INFO]    Running in git mode." >&2
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;34m[AMBOSO-MODE]    Running in git mode.\e[0m" >&2
 }
 
 #Prepare flag values to default value
@@ -110,7 +119,7 @@ makefile_version=""
 git_mode_flag=1 #By default we run in git mode
 base_mode_flag=0
 
-while getopts "M:S:E:D:BgvbpHhri" opt; do
+while getopts "M:S:E:D:BgVbpHhriv" opt; do
   case $opt in
     S )
       source_name="$OPTARG"
@@ -140,8 +149,12 @@ while getopts "M:S:E:D:BgvbpHhri" opt; do
     g )
       git_mode_flag=1
       ;;
-    v )
+    V )
       verbose_flag=1
+      ;;
+    v )
+      echo_amboso_version
+      exit 0
       ;;
     p )
       purge_flag=1
@@ -170,11 +183,11 @@ tot_opts=$OPTIND
 done
 
 #We check again if basemode was requested, as the only flag checked in build stage is git_mode_flag
-[[ $base_mode_flag -gt 0 ]] && git_mode_flag=0
+[[ $base_mode_flag -gt 0 ]] && git_mode_flag=0 && echo -e "\033[1;31m[AMBOSO-MODE]    Running in base mode, expecting full source builds.\e[0m" >&2
 [[ $git_mode_flag -gt 0 ]] && git_mode_check #We are now sure we can quit immediately if not running in a git repo
 
 #We always notify of missing -D argument
-[[ ! $dir_flag -gt 0 ]] && milestones_dir="$(pwd)/bin/" && echo -e "\n\033[1;33m[DEBUG]    No -D flag, using ./bin for target dir. Run with -v to see more.\e[0m" >&2 #&& usage && exit 1
+[[ ! $dir_flag -gt 0 ]] && milestones_dir="$(pwd)/bin/" && echo -e "\033[1;33m[DEBUG]    No -D flag, using ./bin for target dir. Run with -v to see more.\e[0m" >&2 #&& usage && exit 1
 
 #Check if we are printing help info and exiting early
 if [[ $smallhelp_flag -gt 0 ]]; then {
@@ -184,6 +197,7 @@ if [[ $smallhelp_flag -gt 0 ]]; then {
 fi
 #Check if we are printing Help info and exiting early
 if [[ $bighelp_flag -gt 0 ]]; then {
+      echo_amboso_version
       set_source_info "$milestones_dir"
       set_supported_versions "$milestones_dir"
       usage
@@ -198,7 +212,7 @@ set_supported_versions "$scripts_dir" # Might as well do it now
 if [[ -z $makefile_version ]] ; then {
   set_source_info "$milestones_dir"
   makefile_version=${sources_info[2]}
-  [[ $verbose_flag -gt 0 ]] && echo -e "\n\033[1;33m[DEBUG]    No -F flag, reading stego.lock for target makefile support version.\e[0m" >&2 # && usage && exit 1
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[DEBUG]    No -F flag, reading stego.lock for target makefile support version.\e[0m" >&2 # && usage && exit 1
 }
 fi
 
@@ -206,7 +220,7 @@ fi
 if [[ -z $exec_entrypoint ]] ; then {
   set_source_info "$milestones_dir"
   exec_entrypoint=${sources_info[1]}
-  [[ $verbose_flag -gt 0 ]] && echo -e "\n\033[1;33m[DEBUG]    No -E flag, reading stego.lock for target bin.\e[0m" >&2 # && usage && exit 1
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[DEBUG]    No -E flag, reading stego.lock for target bin.\e[0m" >&2 # && usage && exit 1
 }
 fi
 
@@ -214,17 +228,17 @@ fi
 if [[ -z $source_name ]] ; then {
   set_source_info "$milestones_dir"
   source_name=${sources_info[0]}
-  [[ $verbose_flag -gt 0 ]] && echo -e "\n\033[1;33m[DEBUG]    No -S flag, reading stego.lock for target sourcename.\e[0m" >&2 # && usage && exit 1
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[DEBUG]    No -S flag, reading stego.lock for target sourcename.\e[0m" >&2 # && usage && exit 1
 }
 fi
 
-echo "" >&2
+#echo "" >&2
 
 #Display needed values if in verbose mose
-[[ $verbose_flag -gt 0 && ! $dir_flag -gt 0 ]] && echo "[INFO]    Using target dir: ( $scripts_dir )." >&2
-[[ $verbose_flag -gt 0 && ! $exec_was_set -gt 0 ]] && echo "[INFO]    Using target bin: ( $exec_entrypoint )." >&2
-[[ $verbose_flag -gt 0 && ! $sourcename_was_set -gt 0 ]] && echo "[INFO]    Using source file name: ( $source_name )." >&2
-[[ $verbose_flag -gt 0 && ! $vers_make_flag -gt 0 ]] && echo "[INFO]    Using tag for make support: ( $makefile_version ) as first tag compiled with make." >&2
+[[ $verbose_flag -gt 0 && ! $dir_flag -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using target dir: ( $scripts_dir ).\e[0m" >&2
+[[ $verbose_flag -gt 0 && ! $exec_was_set -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using target bin: ( $exec_entrypoint ).\e[0m" >&2
+[[ $verbose_flag -gt 0 && ! $sourcename_was_set -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using source file name: ( $source_name ).\e[0m" >&2
+[[ $verbose_flag -gt 0 && ! $vers_make_flag -gt 0 ]] && echo -e "\033[0;32m[INFO]    Using tag for make support: ( $makefile_version ) as first tag compiled with make.\e[0m" >&2
 
 #Check if we are doing init
 if [[ $init_flag -gt 0 ]] ; then {
@@ -238,7 +252,7 @@ if [[ $init_flag -gt 0 ]] ; then {
     verb=""
     gitm=""
     basem=""
-    [[ $verbose_flag -gt 0 ]] && verb="v" && echo -e "\n[INIT]    Try building ( $init_vers )" >&2
+    [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[INIT]    Trying to build ( $init_vers ) ( $(($i+1)) / $tot_vers )" >&2
     [[ $base_mode_flag -gt 0 ]] && basem="B" #We make sure to pass on eventual base mode to the subcalls
     [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
     #First pass sets the verbose flag but redirects stderr to /dev/null
@@ -254,7 +268,7 @@ if [[ $init_flag -gt 0 ]] ; then {
       #
       #we could just pass -v to the first call if we have it on
       if [[ $verbose_flag -gt 0 ]]; then {
-	echo -e "[INIT]    Checking errors, running \033[1;33m$(basename "$prog_name") -bv $init_vers\e[0m." >&2
+	echo -e "[INIT]    Checking errors, running \033[1;33m$(basename "$prog_name") -bV $init_vers\e[0m." >&2
 	("$prog_name" -M "$makefile_version" -S "$source_name" -D "$scripts_dir" -E "$exec_entrypoint" -bv"$gitm""$basem" "$init_vers") >&2
       }
       fi
@@ -270,7 +284,7 @@ if [[ $init_flag -gt 0 ]] ; then {
     display_zero=""
   }
   fi
-  echo -e "[INIT]    Took $display_zero$runtime_init seconds, $count_bins/$tot_vers binaries ready.\n"
+  echo -e "[INIT]    Took $display_zero$runtime_init seconds, ( $count_bins / $tot_vers ) binaries ready."
   #We don't quit after the full build.
   #exit 0
 }
@@ -334,7 +348,7 @@ fi
 
 #If we can't find the file we may try to build it
 if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
-  echo -e "\n\033[1;33m[QUERY]    ( $version ) binary not ready.\e[0m" #>&2
+  echo -e "\n\033[1;33m[QUERY]    ( $version ) binary not found in ( $script_path ).\e[0m" #>&2
   if [[ ! $build_flag -gt 0 ]] ; then { #We exit here if we don't want to try building and we're not going to purge
     echo -e "\033[0;33m[DEBUG]    To try building, run with -b flag\e[0m\n" >&2
     [[ ! $purge_flag -gt 0 ]] && exit 1 # quit if we're not purging
@@ -347,16 +361,16 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
     tool_txt="single file gcc"
     if [[ $has_makefile -gt 0 ]]; then { #Make mode
       tool_txt="make"
-      echo -e "$version >= $makefile_version, has Makefile" >&2
+      echo -e "\033[0;33m[MODE]    target ( $version ) >= ( $makefile_version ), has Makefile.\e[0m" >&2
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Building ( $version ), using make.\e[0m" >&2
       curr_dir=$(realpath .)
       start_t=`date +%s.%N`
       if [[ $git_mode_flag -eq 0 ]] ; then { #Building in base mode, we cd into target directory before make
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m" #>&2
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m" #>&2
         cd $script_path; make >&2
         comp_res=$?
       } else { #Building in git mode, we checkout the tag and move the binary after the build
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in git mode, checking out ( $version ).\e[0m" #>&2
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;34m[BUILD]    Running in git mode, checking out ( $version ).\e[0m" #>&2
         git checkout "$version" 2>/dev/null #Repo goes back to tagged state
         checkout_res=$?
         if [[ $checkout_res -gt 0 ]] ; then { #Checkout failed, we don't build and we set comp_res
@@ -386,18 +400,18 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
       runtime=$( echo "$end_t - $start_t" | bc -l )
       cd "$curr_dir"
     } else { #Straight gcc mode
-      [[ $verbose_flag -gt 0 ]] && echo -e "\n$version < $makefile_version, single file build with gcc" >&2
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[MODE]    target ( $version ) < ( $makefile_version ), single file build with gcc.\e[0m" >&2
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Building ( $version ), using gcc call.\e[0m" >&2
       #echo "" >&2 #new line for error output
       [[ -z $source_name ]] && echo -e "\n\033[1;31m[WTF-ERROR]    Missing source file name. ( $version ).\e[0m\n" && usage && exit 1
 
       start_t=`date +%s.%N`
       if [[ $git_mode_flag -eq 0 ]] ; then { #Building in base mode, we cd into target directory before make
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m" #>&2
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m" #>&2
         gcc "$script_path"/"$source_name" -o "$script_path"/"$exec_entrypoint" -lm 2>&2
         comp_res=$?
       } else { #Building in git mode, we checkout the tag and move the binary after the build
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in git mode, checking out ( $version ).\e[0m" #>&2
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;34m[BUILD]    Running in git mode, checking out ( $version ).\e[0m" #>&2
         git checkout "$version" 2>/dev/null #Repo goes back to tagged state
         checkout_res=$?
         if [[ $checkout_res -gt 0 ]] ; then { #Checkout failed, we set comp_res and don't build
@@ -422,7 +436,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
     fi
     #Check compilation result
     if [[ $comp_res -eq 0 ]] ; then
-      echo -e "\n\033[1;32m[BUILD]    Done Building ( $version ) (took $runtime seconds, using $tool_txt).\e[0m"
+      echo -e "\n\033[1;32m[BUILD]    Done Building ( $version ) , took $runtime seconds, using ( $tool_txt ).\e[0m"
     else
       echo -e "\n\033[1;31m[ERROR]    Build for ( $version ) failed, quitting.\e[0m\n" >&2
       exit 1
@@ -432,8 +446,8 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
   fi
 
 } elif [[ ! -z $version ]] ; then { #Binary was present, we notify if we were running with build flag
-  echo -e "\n\033[1;32m[QUERY]    ( $version ) binary is built.\e[0m" >&2
-  [[ $build_flag -gt 0 ]] && echo -e "\n\033[0;33m[DEBUG]    Build: Found binary for ( $version ), won't build.\e[0m\n" >&2
+  echo -e "\n\033[1;32m[QUERY]    ( $version ) binary is ready at ( $script_path ) .\e[0m" >&2
+  [[ $build_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Found binary for ( $version ), won't build.\e[0m" >&2
 } elif [[ ! -z $queried_version ]] ; then {
   echo -e "\033[1;31m[QUERY]    ( $queried_version ) invalid query, run with -v to see more.\e[0m"
 }
@@ -499,20 +513,19 @@ if [[ purge_flag -gt 0 ]]; then
     if [[ $clean_res -eq 0 && $has_bin -gt 0 ]] ; then {
       #we advance the count
       tot_removed=$(($tot_removed +1))
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[PURGE]    Removed $purge_vers using $tool_txt.\e[0m\n" >&2
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[PURGE]    Removed ( $purge_vers ) using ( $tool_txt ).\e[0m" >&2
     } else {
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;31m[PURGE]    Failed removing $purge_vers using $tool_txt.\e[0m\n" >&2
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;31m[PURGE]    Failed removing ( $purge_vers ) using ( $tool_txt ).\e[0m" >&2
     }
     fi
 
   done
   if [[ $tot_removed -gt 0 ]] ; then {
-    echo -e "\033[0;33m[PURGE]    Purged $tot_removed/$tot_vers versions, quitting.\e[0m\n"
+    echo -e "\033[0;33m[PURGE]    Purged ( $tot_removed / $tot_vers ) versions, quitting.\e[0m\n"
   } else {
-    echo -e "\n\033[0;33m[PURGE]    No binaries to purge found, quitting. Run with -v to see more.\e[0m\n"
+    echo -e "\n\033[0;33m[PURGE]    No binaries to purge found.\e[0m\n"
   }
   fi
-  exit 0 #purge always returns 0?
 fi
 
 exit 0
