fix: various SC warnings fixed

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -299,10 +299,10 @@ if [[ $(basename "$(pwd)") == "amboso" ]] ; then {
   }
   fi
 } else {
-  amboso_fn_path="$(realpath $(pwd))/amboso/amboso_fn.sh"
+  amboso_fn_path="$(realpath "$(pwd)")/amboso/amboso_fn.sh"
   found_amboso_dir=0
   [[ $verbose_flag -gt 1 ]] && printf "\033[0;33m[PREP]    Assuming we are running in super-repo. Sourcing: \"$amboso_fn_path\".\e[0m\n" >&2
-  [[ -d "$(realpath $(pwd))"/amboso ]] && found_amboso_dir=1
+  [[ -d "$(realpath "$(pwd)")"/amboso ]] && found_amboso_dir=1
   [[ $verbose_flag -gt 1 && $found_amboso_dir -gt 0 ]] && printf "\033[0;32m[PREP]    Found amboso dir.\e[0m\n" >&2
   if [[ -f $amboso_fn_path ]] ; then {
     [[ $verbose_flag -gt 1 ]] && printf "\033[0;35m[PREP]    Valid file at: \"$amboso_fn_path\".\e[0m\n" >&2
@@ -358,7 +358,7 @@ if [[ $expected_AMBOSO_API_LVL > $AMBOSO_API_LVL ]] ; then {
   [[ $verbose_flag -gt 1 ]] && printf "\033[0;31m[WARN]    AMBOSO_API_LVL is greater than expected. Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[0;31m } , { \033[1;34m$AMBOSO_API_LVL\033[0;31m } is higher.\e[0m\n" >&2
   [[ $verbose_flag -gt 1 ]] && printf "\n\033[1;31m[WARN]    Continuing run with unexpected AMBOSO_API_LVL: Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[1;31m } , { \033[1;34m$AMBOSO_API_LVL\033[1;31m } is higher.\e[0m\n"
   #exit 2
-} elif [[ $AMBOSO_API_LVL = $expected_AMBOSO_API_LVL ]] ; then {
+} elif [[ $AMBOSO_API_LVL = "$expected_AMBOSO_API_LVL" ]] ; then {
   [[ $verbose_flag -gt 1 ]] && printf "\033[0;32m[PREP]   Running with \"\$AMBOSO_API_LVL\" [ \033[1;35m$AMBOSO_API_LVL\033[0;32m ]; min is { \033[1;36m$expected_AMBOSO_API_LVL\033[0;32m }.\e[0m\n" >&2
 }
 fi
@@ -721,7 +721,7 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ]
     [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
     [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet mode to the subcalls
     #First pass sets the verbose flag but redirects stderr to /dev/null
-    [[ $verbose_flag -gt 0 ]] && printf "\033[0;35m[VERB]    Running \"$(dirname $(basename $prog_name)) -W $amboso_start_time -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -b$verb$gitm$basem$quietm$silentm$packm$ignore_gitcheck$showtimem $init_vers\" ( $(($i+1)) / $tot_vers )\n" >&2
+    [[ $verbose_flag -gt 0 ]] && printf "\033[0;35m[VERB]    Running \"$(dirname "$(basename $prog_name)") -W $amboso_start_time -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -b$verb$gitm$basem$quietm$silentm$packm$ignore_gitcheck$showtimem $init_vers\" ( $(($i+1)) / $tot_vers )\n" >&2
     "$prog_name" -W "$amboso_start_time" -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -b"$verb""$gitm""$basem""$quietm""$silentm""$packm""$ignore_gitcheck""$showtimem" "$init_vers" 2>/dev/null
     if [[ $? -eq 0 ]] ; then {
       [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[INIT]    $init_vers binary ready.\e[0m\n" >&2
@@ -875,7 +875,7 @@ fi
 
 tot_left_args=$(( $# ))
 if [[ $tot_left_args -gt 1 ]]; then {
-  printf "\n\033[1;31m[ERROR]    Unknown argument: "$2" (ignoring other $(($tot_left_args-1)) args).\e[0m\n\n"
+  printf "\n\033[1;31m[ERROR]    Unknown argument: \"$2\" (ignoring other $(($tot_left_args-1)) args).\e[0m\n\n"
   usage
   echo_timer "$amboso_start_time"  "Unknown arg [$2]" "1"
   exit 1
@@ -891,7 +891,7 @@ if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 && $test_mod
   printf "\033[1;33m           Run with -h for help.\e[0m\n\n"
   echo_timer "$amboso_start_time"  "Missing query" "1"
   exit 1
-} elif [[ $tot_left_args -lt 1 && $test_mod_flag -gt 0 ]] ; then {
+} elif [[ $tot_left_args -lt 1 && $test_mode_flag -gt 0 ]] ; then {
   app "$(echo_node silence_check missing_test_query)"
   app "$(echo_node missing_test_query end_node)"
   end_digraph
@@ -906,7 +906,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   app "$(echo_node recursion_lt_3 doing_test)"
   if [[ $quiet_flag -eq 0 && $verbose_flag -gt 1 ]]; then { #WIP
       printf "\033[1;35m[VERB]    Test mode (-T was on).\e[0m\n" >&2
-      [[ $smalltest_mode_flag -gt 0 ]] && printf "\033[1;35m[VERB]    (-t was on).\e[0m\n" >&2
+      [[ $small_test_mode_flag -gt 0 ]] && printf "\033[1;35m[VERB]    (-t was on).\e[0m\n" >&2
       echo_tests_info "$kazoj_dir" >&2
   }
   fi
@@ -918,7 +918,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     current_item="${read_tests_files[$i]}"
     [[ $verbose_flag -gt 0 ]] && printf "\033[0;35m[TEST]    Checking case ($i/$count_tests_names): $current_item\e[0m\n" >&2
     #echo "checking $current_item"
-    if [[ $query = $current_item ]]; then {
+    if [[ $query = "$current_item" ]]; then {
       test_type="casetest"
       test_name="$query"
       test_path="$kazoj_dir/$cases_dir/${read_tests_files[$i]}"
@@ -933,7 +933,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       current_item="${read_errortests_files[$i]}"
       [[ $verbose_flag -gt 0 ]] && printf "\033[0;35m[TEST]    Checking error case ($i/$count_errortests_names): $current_item\e[0m\n" >&2
       #echo "checking $current_item"
-      if [[ $query = $current_item ]] ; then {
+      if [[ $query = "$current_item" ]] ; then {
 	test_type="errortest"
 	test_name="$query"
 	test_path="$kazoj_dir/$errors_dir/${read_errortests_files[$i]}"
@@ -1075,13 +1075,13 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     printf "\033[1;31m[WARN]    Test call returned 69, we clean tmpfiles and follow suit.\e[0m\n"
     #Delete tmpfiles
     rm -f "$run_tmp_out" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\e[0m\n\n"
-    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_out".\e[0m\n" >&2
+    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_out\".\e[0m\n" >&2
     rm -f "$run_tmp_err" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\e[0m\n\n"
-    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_err".\e[0m\n" >&2
+    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_err\".\e[0m\n" >&2
     rm -f "$run_tmp_escout" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escout). Why?\n\n"
-    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escout".\e[0m\n" >&2
+    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_escout\".\e[0m\n" >&2
     rm -f "$run_tmp_escerr" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escerr). Why?\n\n"
-    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escerr".\e[0m\n" >&2
+    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_escerr\".\e[0m\n" >&2
     printf "\033[1;31m[PANIC]    Quitting with 69.\e[0m\n"
     echo_timer "$amboso_start_time"  "Test run ended with 69" "1"
     exit 69
@@ -1098,9 +1098,9 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   }
   fi
   rm -f "$run_tmp_out" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\e[0m\n\n"
-  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_out".\e[0m\n" >&2
+  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_out\".\e[0m\n" >&2
   rm -f "$run_tmp_err" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\e[0m\n\n"
-  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_err".\e[0m\n" >&2
+  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_err\".\e[0m\n" >&2
   #Testing diff for escaped stdout
   ( diff "$run_tmp_escout" "$relative_testpath".stdout ) 2>/dev/null 1>&2
   diff_res="$?"
@@ -1137,7 +1137,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   }
   fi
   rm -f "$run_tmp_escout" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escout). Why?\n\n"
-  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escout".\e[0m\n" >&2
+  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_escout\".\e[0m\n" >&2
   #Testing diff for escaped stderr
   ( diff "$run_tmp_escerr" "$relative_testpath".stderr ) 2>/dev/null 1>&2
   diff_res="$?"
@@ -1174,7 +1174,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   }
   fi
   rm -f "$run_tmp_escerr" || printf "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escerr). Why?\n\n"
-  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escerr".\e[0m\n" >&2
+  [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[TEST]    Removed tempfile \"$run_tmp_escerr\".\e[0m\n" >&2
   if [[ $build_flag -gt 0 ]] ; then {
     #We simulate success since we're recording
     printf "\033[1;33m[TEST]    Phony pass (recording).\e[0m\n"
