feat: 1.4.5 dotfile CFG dump

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -8,8 +8,8 @@ if [[ "$EUID" -eq 0 ]] ; then {
 fi
 # Set recursion env var if not exists
 prog_name="$(readlink -f "$0")"
-amboso_currvers="1.4.5-devel"
-expected_AMBOSO_API_LVL="1.4.5-devel"
+amboso_currvers="1.4.5"
+expected_AMBOSO_API_LVL="1.4.5"
 amboso_testflag_version="1.4.4"
 export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 # check recursion
@@ -21,6 +21,29 @@ else
 fi
 #Increment depth counter
 export AMBOSO_LVL_REC=$(($AMBOSO_LVL_REC+1))
+
+#Functions to output dotfile
+dotfile="./amboso_cfg.dot"
+function app () {
+  [[ $print_cfg_flag -eq 0 || ${AMBOSO_LVL_REC} -gt 1 ]] && return
+  txt="$1" file="$dotfile"
+  echo "$txt" >> "$file"
+}
+function echo_node() {
+  frm="$1" nd="$2"
+  echo " $frm -> $nd "
+}
+function echo_start_node() {
+  sn="$1"
+  echo -n " $sn ->"
+}
+function start_digraph() {
+  app "digraph {"
+}
+function end_digraph() {
+  app "}"
+}
+
 #Prepare flag values to default value
 amboso_version="amboso version $amboso_currvers"
 purge_flag=0
@@ -50,9 +73,13 @@ big_list_flag=0
 small_list_flag=0
 version_flag=0
 silent_flag=0
+print_cfg_flag=0
 
-while getopts "M:S:E:D:K:BgVbpHhrivdlLtTqs" opt; do
+while getopts "M:S:E:D:K:BgVbpHhrivdlLtTqsc" opt; do
   case $opt in
+    c )
+      print_cfg_flag=1
+      ;;
     s )
       silent_flag=1
       ;;
@@ -137,6 +164,19 @@ while getopts "M:S:E:D:K:BgVbpHhrivdlLtTqs" opt; do
 tot_opts=$OPTIND
 done
 
+if [[ $print_cfg_flag -gt 0 ]] ; then {
+  #Reset output file
+  echo "" > "$dotfile"
+  #Print opening digraph
+  start_digraph
+  start_node="start"
+  #Unnecessary?
+  #app "$( echo_start_node "$start_node" )"
+
+  app "$( echo_node "$start_node" begin_node )"
+}
+fi
+
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]    Done getopts.\e[0m" >&2
 
 if [[ $(basename $(pwd)) == "amboso" ]] ; then {
@@ -165,7 +205,16 @@ if [[ $(basename $(pwd)) == "amboso" ]] ; then {
   fi
 }
 fi
-[[ $source_res -ne 0 ]] && echo -e "\033[1;31m[PANIC]    Can't find amboso_fn. Expected path: \"$amboso_fn_path\".\e[0m" && exit 2
+
+if [[ $source_res -ne 0 ]] ; then {
+  echo -e "\033[1;31m[PANIC]    Can't find amboso_fn. Expected path: \"$amboso_fn_path\".\e[0m"
+  app "$(echo_node begin_node failed_sourcing_fn)"
+  app "$(echo_node failed_sourcing_fn end_node)"
+  end_digraph
+  exit 2
+}
+fi
+app "$(echo_node begin_node loaded_fn)"
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]    Done loading functions.\e[0m" >&2
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;37m[PREP]    \"\$AMBOSO_API_LVL\" is: (\033[0;34m $AMBOSO_API_LVL \033[0;37m, expected { \033[1;33m$expected_AMBOSO_API_LVL\033[0;37m } ).\e[0m" >&2
 if [[ $expected_AMBOSO_API_LVL > $AMBOSO_API_LVL ]] ; then {
@@ -181,9 +230,9 @@ if [[ $expected_AMBOSO_API_LVL > $AMBOSO_API_LVL ]] ; then {
 }
 fi
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]    Printing active flags:\e[0m" >&2 && echo_active_flags >&2
-main_at=144
+main_at=235
 #PROG_START_LINE
-prog_start_line="144"
+prog_start_line="235"
 trace_flag=0
 trace_line="421"
 # Check env var to enable backtrace
@@ -228,6 +277,8 @@ fi
 
 [[ "$AMBOSO_LVL_REC" -eq 0 ]] && echo -e "\033[1;35m[AMBOSO]    Current version: $amboso_currvers\e[0m\n"
 
+app "$(echo_node loaded_fn silence_check)"
+
 #We check if we have to silence all subsequent output
 if [[ ( $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ) && $silent_flag -gt 0 ]] ; then {
   echo -e "\033[1;33m[MODE]\e[0m    Running in silent mode, will now suppress all output.\n"
@@ -250,8 +301,15 @@ fi
 #If base_mode_flag is asserted, we always override git_mode_flag
 
 #Default mode with no flags should be git mode
-[[ $base_mode_flag -gt 0 ]] && git_mode_flag=0 && echo -e "\033[1;31m[MODE]    Running in base mode, expecting full source builds.\e[0m" >&2
-[[ $git_mode_flag -gt 0 ]] && git_mode_check #We are now sure we can quit immediately if not running in a git repo
+if [[ $base_mode_flag -gt 0 ]] ; then {
+  git_mode_flag=0
+  echo -e "\033[1;31m[MODE]    Running in base mode, expecting full source builds.\e[0m" >&2
+}
+fi
+if [[ $git_mode_flag -gt 0 ]] ; then {
+  git_mode_check
+}
+fi
 
 #We always notify of missing -D argument
 [[ ! $dir_flag -gt 0 ]] && milestones_dir="./bin/" && echo -e "\033[1;33m[DEBUG]    No -D flag, using ( $milestones_dir ) for target dir. Run with -V to see more.\e[0m" >&2 #&& usage && exit 1
@@ -268,9 +326,15 @@ if [[ $test_mode_flag -gt 0 && ! $testdir_flag -gt 0 ]] ; then {
 fi
 if [[ $test_mode_flag -gt 0 && $test_info_was_set -gt 0 ]] ; then {
   if [[ $AMBOSO_LVL_REC -lt 3 ]] ; then {
+    app "$(echo_node silence_check test_mode)"
+    app "$(echo_node test_mode recursion_lt_3)"
     echo -e "\033[1;32m[DEBUG]    bone dir: ( $cases_dir )\e[0m" >&2
     echo -e "\033[1;32m           kulpo dir: ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
   } else {
+    app "$(echo_node silence_check test_mode)"
+    app "$(echo_node test_mode recursion_ge_3)"
+    app "$(echo_node recursion_ge_3 end_node)"
+    end_digraph
     [[ ! -z $cases_dir ]] && echo -e "\033[1;32m[DEBUG]    bone dir: ( $cases_dir )\e[0m" >&2
     [[ ! -z $errors_dir ]] && echo -e "\033[1;32m           kulpo dir: ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
     echo -e "\n\033[1;31m[PANIC]    Running  as \"$prog_name\" in test mode is not supported. Quitting with 69.\e[0m\n" #&& usage && exit 1
@@ -279,10 +343,16 @@ if [[ $test_mode_flag -gt 0 && $test_info_was_set -gt 0 ]] ; then {
   }
   fi
 } elif [[ $test_info_was_set -eq 0 && $test_mode_flag -gt 0 ]] ; then {
+    app "$(echo_node silence_check test_mode)"
+    app "$(echo_node test_mode no_test_info)"
   if [[ $AMBOSO_LVL_REC -lt 3 ]] ; then {
+    app "$(echo_node no_test_info recursion_lt_3)"
     echo -e "\033[1;33m[DEBUG]    bone dir (NO -K passed to this call): ( $cases_dir )\e[0m" >&2
     echo -e "\033[1;33m           kulpo dir (NO -K passed to this amboso call): ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
   } else {
+    app "$(echo_node no_test_info recursion_ge_3)"
+    app "$(echo_node recursion_ge_3 end_node)"
+    end_digraph
     #Deep case: we're running a test, calling a program that calls amboso in test mode.
     echo -e "\033[1;33m[DEBUG]    bone dir (NO -K passed to this call): ( $cases_dir )\e[0m" >&2
     echo -e "\033[1;33m           kulpo dir (NO -K passed to this amboso call): ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
@@ -296,6 +366,9 @@ fi
 
 #Check if we are printing help info and exiting early
 if [[ $smallhelp_flag -gt 0 ]]; then {
+    app "$(echo_node silence_check doing_help)"
+    app "$(echo_node doing_help end_node)"
+    end_digraph
   if [[ $AMBOSO_LVL_REC -gt 1 ]] ; then {
     echo -e "[AMBOSO]    can't ask for help on a recursive call, try running \"$prog_name -h\" from a shell. ( depth $((${AMBOSO_LVL_REC}-1)) )\n\n        args: (\"$@\")" >&2
     exit 1
@@ -311,6 +384,9 @@ if [[ $smallhelp_flag -gt 0 ]]; then {
 fi
 #Check if we are printing Help info and exiting early
 if [[ $bighelp_flag -gt 0 ]]; then {
+    app "$(echo_node silence_check doing_big_help)"
+    app "$(echo_node doing_big_help end_node)"
+    end_digraph
   if [[ $AMBOSO_LVL_REC -gt 1 ]] ; then {
     echo -e "[AMBOSO]    can't ask for help on a recursive call, try running \"$prog_name -H\" from a shell. ( depth $((${AMBOSO_LVL_REC}-1)) )\n\n        args: (\"$@\")" >&2
     exit 1
@@ -333,7 +409,6 @@ set_source_info "$milestones_dir"
 kazoj_dir="${sources_info[3]}" #TODO: don't think this should be overwritten here if assigned earlier
 set_tests_info "$kazoj_dir"
 set_supported_tests "$kazoj_dir"
-
 
 if [[ $verbose_flag -gt 1 ]]; then { #WIP
     echo -e "\033[1;35m[VERB]    SYNCPOINT:  listing tag names\e[0m" >&2
@@ -433,6 +508,7 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ]
       echo_supported_tags "$milestones_dir" >&2
   }
   fi
+  app "$(echo_node silence_check doing_init)"
 
   count_bins=0
   start_t_init=`date +%s.%N`
@@ -511,6 +587,9 @@ fi
 #If we have -t and not -T, we check all tests and EXIT
 #WIP
 if [[ $small_test_mode_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
+  app "$(echo_node silence_check doing_test_macro)"
+  app "$(echo_node doing_test_macro end_node)"
+  end_digraph
   if [[ $quiet_flag -eq 0 ]] ; then {
     echo -e "\033[1;33m[DEBUG]    -t assert: shortcut to run \"$prog_name\" with -T"
     echo -e "\033[1;33m[DEBUG]    will pass: ( -qVb ) to subcall, if asserted.\n"
@@ -593,10 +672,16 @@ fi
 
 #If we don't have init or purge flag, we bail on a missing version argument
 if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 && $test_mode_flag -eq 0 ]]; then {
+  app "$(echo_node silence_check missing_query)"
+  app "$(echo_node missing_query end_node)"
+  end_digraph
   echo -e "\033[1;31m[ERROR]    Missing query.\e[0m\n"
   echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
   exit 1
 } elif [[ $tot_left_args -lt 1 && $test_mod_flag -gt 0 ]] ; then {
+  app "$(echo_node silence_check missing_test_query)"
+  app "$(echo_node missing_test_query end_node)"
+  end_digraph
   #If in test mode, we still whine about a target test
   echo -e "\033[1;31m[ERROR]    Missing test query.\e[0m\n"
   echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
@@ -605,6 +690,7 @@ if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 && $test_mod
 fi
 #Check if we are doing a test
 if [[ $test_mode_flag -gt 0 ]]; then {
+  app "$(echo_node recursion_lt_3 doing_test)"
   if [[ $quiet_flag -eq 0 && $verbose_flag -gt 1 ]]; then { #WIP
       echo -e "\033[1;35m[VERB]    Test mode (-T was on).\e[0m" >&2
       [[ $smalltest_mode_flag -gt 0 ]] && echo -e "\033[1;35m[VERB]    (-t was on).\e[0m" >&2
@@ -882,6 +968,9 @@ done
 if [[ -z $version ]]; then {
   #We only freak out if we don't have test_mode, purge or init flags on
   if [[ $test_mode_flag -eq 0 && $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
+    app "$(echo_node silence_check query_invalid)"
+    app "$(echo_node query_invalid end_node)"
+    end_digraph
     echo -e "\033[1;31m[ERROR]    ( $query ) is not a supported tag.\e[0m\n"
     echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
     exit 1
@@ -904,17 +993,29 @@ fi
 
 #If we can't find the file we may try to build it
 if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
+  if [[ $init_flag -eq 0 ]] ; then {
+    app "$(echo_node silence_check query_success_not_ready)"
+  }
+  fi
   echo -e "\n\033[1;33m[QUERY]    ( $version ) binary not found in ( $script_path ).\e[0m" #>&2
   if [[ ! $build_flag -gt 0 ]] ; then { #We exit here if we don't want to try building and we're not going to purge
     echo -e "\033[0;33m[DEBUG]    To try building, run with -b flag\e[0m\n" >&2
-    [[ ! $purge_flag -gt 0 ]] && exit 1 # quit if we're not purging
+    if [[ ! $purge_flag -gt 0 ]] ; then {
+     app "$(echo_node query_success_not_ready end_node)"
+     end_digraph
+     exit 1 # quit if we're not purging
+    }
+    fi
   } else {
     if [[ ! -d "$script_path" ]] ; then
       echo -e "\033[1;31m[ERROR]    '$script_path' is not a valid directory.\n    Check your supported versions for details on ( $version ).\e[0m\n" >&2
+      app "$(echo_node query_success_not_ready end_node)"
+      end_digraph
       exit 1
     fi
     #we try to build
     tool_txt="single file gcc"
+    app "$(echo_node query_success_not_ready building)"
     if [[ $has_makefile -gt 0 ]]; then { #Make mode
       tool_txt="make"
       echo -e "\033[0;33m[MODE]    target ( $version ) >= ( $makefile_version ), has Makefile.\e[0m" >&2
@@ -993,8 +1094,12 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
     #Check compilation result
     if [[ $comp_res -eq 0 ]] ; then
       echo -e "\033[1;32m[BUILD]    Done Building ( $version ) , took $runtime seconds, using ( $tool_txt ).\e[0m"
+      app "$(echo_node building build_success)"
     else
       echo -e "\033[1;31m[ERROR]    Build for ( $version ) failed, quitting.\e[0m\n" >&2
+      app "$(echo_node building build_fail)"
+      app "$(echo_node build_fail end_node)"
+      end_digraph
       exit 1
     fi
 
@@ -1002,15 +1107,33 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
   fi
 
 } elif [[ ! -z $version ]] ; then { #Binary was present, we notify if we were running with build flag
+  if [[ $init_flag -eq 0 ]] ; then {
+    app "$(echo_node silence_check query_success_ready)"
+  } else {
+    app "$(echo_node doing_init query_success_ready)"
+  }
+  fi
   echo -e "\n\033[1;32m[QUERY]    ( $version ) binary is ready at ( $script_path ) .\e[0m\n" >&2
-  [[ $build_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Found binary for ( $version ), won't build.\e[0m" >&2
+  if [[ $build_flag -gt 0 ]] ; then {
+    echo -e "\033[0;33m[BUILD]    Found binary for ( $version ), won't build.\e[0m" >&2
+    app "$(echo_node query_success_ready build_success)"
+
+  }
+  fi
 } elif [[ ! -z $query ]] ; then {
+  app "$(echo_node silence_check query_invalid)"
   echo -e "\033[1;31m[QUERY]    ( $query ) invalid query, run with -V to see more.\e[0m"
 }
 fi
 
 #We check the run flag to run the binary
 if [[ ! -z $version && $run_flag -eq 1 && -x $script_path/$exec_entrypoint ]] ; then {
+  if [[ $build_flag -gt 0 && $comp_res -eq 0 ]]; then { #The second condition is needed to catch running a freshly built tag
+    app "$(echo_node build_success running)"
+  } else {
+    app "$(echo_node query_success_ready running)"
+  }
+  fi
   echo -e "\n\033[0;32m[DEBUG]    Running script $script_path/$exec_entrypoint\e[0m"
   #echo -n "."
   #sleep 1
@@ -1026,6 +1149,14 @@ fi
 #Check if we are deleting and exiting early
 #We skipped first deletion pass if purge mode is requested, since we will enter here later
 if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
+  if [[ $run_flag -gt 0 ]] ; then {
+    app "$(echo_node running deleting)"
+  } elif [[ $build_flag -gt 0 ]] ; then {
+    app "$(echo_node build_success deleting)"
+  } else {
+    app "$(echo_node query_success_ready deleting)"
+  }
+  fi
     clean_res=1
   if [[ $has_makeclean -gt 0 && $base_mode_flag -gt 0 ]] ; then { #Running in git mode skips make clean
     tool_txt="make clean"
@@ -1042,7 +1173,10 @@ if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
         exit "$clean_res"
       } else {
         [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;31m[DELETE]   ( $versions ) does not have an executable at ( $delete_path ).\e[0m\n" # >&2
-           exit 1
+        app "$(echo_node deleting no_target_error)"
+        app "$(echo_node no_target_error end_node)"
+        end_digraph
+        exit 1
       }
       fi
   } else { #Doesn't have Makefile, build method 2. Running in git mode also skips using make clean
@@ -1056,8 +1190,14 @@ if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
     clean_res=$?
     if [[ $clean_res -eq 0 ]] ; then {
       echo -e "\033[0;32m[DELETE]    Success on ( $version ).\e[0m"
+      app "$(echo_node deleting delete_success)"
+      app "$(echo_node delete_success end_node)"
+      end_digraph
     } else {
       echo -e "\033[0;31m[DELETE]    Failure on ( $version ).\e[0m"
+      app "$(echo_node deleting delete_fail)"
+      app "$(echo_node delete_fail end_node)"
+      end_digraph
     }
     fi
     exit "$clean_res"
@@ -1068,6 +1208,14 @@ fi
 
 #Check if we are purging
 if [[ purge_flag -gt 0 ]]; then
+  if [[ $run_flag -gt 0 ]] ; then {
+    app "$(echo_node running purging)"
+  } elif [[ $build_flag -gt 0 ]] ; then {
+    app "$(echo_node build_success purging)"
+  } else {
+    app "$(echo_node query_success_ready purging)"
+  }
+  fi
   #echo "" >&2 #This newline can be redirected when doing recursion for init mode
   tot_removed=0
   tool_txt="rm"
@@ -1126,10 +1274,29 @@ if [[ purge_flag -gt 0 ]]; then
   done
   if [[ $tot_removed -gt 0 ]] ; then {
     echo -e "\033[0;33m[PURGE]    Purged ( $tot_removed / $tot_vers ) versions, quitting.\e[0m\n"
+    app "$(echo_node purging purging_success)"
+    app "$(echo_node purging_success end_node)"
   } else {
     echo -e "\n\033[0;33m[PURGE]    No binaries to purge found.\e[0m\n"
+    app "$(echo_node purging purging_fail)"
+    app "$(echo_node purging_fail end_node)"
   }
   fi
 fi
+
+if [[ $delete_flag -eq 0 ]]; then {
+    #We need to close cfg dump
+    if [[ $run_flag -gt 0 ]] ; then {
+      app "$(echo_node running end_node)"
+    } elif [[ $build_flag -gt 0 ]] ; then {
+      app "$(echo_node build_success end_node)"
+    } else {
+      app "$(echo_node query_success_ready end_node)"
+    }
+    fi
+}
+fi
+
+end_digraph
 
 exit 0
