fix: remove last echoes
fix: remove echo_timer from getopt section, where it's not defined

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -37,9 +37,9 @@ export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 # check recursion
 if [[ "${AMBOSO_LVL_REC}" -le "2" ]]; then
   PARENT_COMMAND=$(ps -o comm= $PPID)
-  [[ $PARENT_COMMAND = "$prog_name" ]] && echo "Unexpected result while checking amboso recursion level." && exit 1
+  [[ $PARENT_COMMAND = "$prog_name" ]] && printf "Unexpected result while checking amboso recursion level.\n" && exit 1
 else
-  echo -e "\n[AMBOSO]    Exceeded depth for recursion ( nested ${AMBOSO_LVL_REC} times).\n"
+  printf "\n[AMBOSO]    Exceeded depth for recursion ( nested ${AMBOSO_LVL_REC} times).\n\n"
   echo_timer "$amboso_start_time"  "Excessive recursion" "1"
   exit 69
 fi
@@ -124,8 +124,8 @@ while getopts "A:M:S:E:D:K:G:W:wBgVbpHhrivdlLtTqsczUXC" opt; do
       gen_C_headers_flag=1
       gen_C_headers_destdir="$OPTARG"
       if [[ ! -d $gen_C_headers_destdir ]] ; then {
-	      echo -e "\033[1;31m[ERROR]    ($gen_C_headers_destdir) was not a valid directory.\e[0m"
-	      echo -e "\033[1;33m[AMBOSO]    Run with -h for help.\e[0m"
+	      printf "\033[1;31m[ERROR]    ($gen_C_headers_destdir) was not a valid directory.\e[0m\n"
+	      printf "\033[1;33m[AMBOSO]    Run with -h for help.\e[0m\n"
   	      echo_timer "$amboso_start_time"  "Invalid dir for C gen" "1"
 	      exit 1
       } else {
@@ -228,13 +228,11 @@ while getopts "A:M:S:E:D:K:G:W:wBgVbpHhrivdlLtTqsczUXC" opt; do
       init_flag=1
       ;;
     \? )
-      echo "Invalid option: -$OPTARG. Run with -h for help." >&2
-      echo_timer "$amboso_start_time"  "Invalid option: [$OPTARG]" "1"
+      printf "Invalid option: -$OPTARG. Run with -h for help.\n" >&2
       exit 1
       ;;
     : )
-      echo "Option -$OPTARG requires an argument. Run with -h for help." >&2
-      echo_timer "$amboso_start_time"  "Missing argument: [$OPTARG]" "1"
+      printf "Option -$OPTARG requires an argument. Run with -h for help.\n" >&2
       exit 1
       ;;
   esac
@@ -268,7 +266,7 @@ fi
 
 if [[ $print_cfg_flag -gt 0 ]] ; then {
   #Reset output file
-  echo "" > "$dotfile"
+  printf "" > "$dotfile"
   #Print opening digraph
   start_digraph
   start_node="start"
@@ -339,7 +337,7 @@ if [[ $(basename $(pwd)) == "amboso" ]] ; then {
 fi
 
 if [[ $source_res -ne 0 ]] ; then {
-  echo -e "\033[1;31m[PANIC]    Failed sourcing amboso_fn. Expected path: \"$amboso_fn_path\".\e[0m"
+  printf "\033[1;31m[PANIC]    Failed sourcing amboso_fn. Expected path: \"$amboso_fn_path\".\e[0m\n"
   app "$(echo_node begin_node failed_sourcing_fn)"
   app "$(echo_node failed_sourcing_fn end_node)"
   end_digraph
@@ -425,8 +423,8 @@ if [[ ( $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ) && $silent_flag -
   printf "\033[1;33m[MODE]\e[0m    Running in silent mode, will now suppress all output.\n\n"
   echo_timer "$amboso_start_time"  "Silent run, turning off outputs" "2"
   exec 3>&1 &>/dev/null
-  echo -e "This output is going to dev null"
-  echo -e "This erroutput is going to dev null" >&2
+  printf "This output is going to dev null\n"
+  printf "This erroutput is going to dev null\n" >&2
 }
 fi
 
