chore: somewhat better test handling
It is still failing often.

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -128,7 +128,7 @@ function set_supported_tests {
     test_fp="$cases_path/$FILE"
     if ! [[ -f $test_fp && -x $test_fp ]] ; then {
       skipped=$((skipped+1))
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Ignoring test $FILE (at $test_fp), not an executable file.\e[0m" >&2
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Skip test $FILE (at $test_fp), not an executable file.\e[0m" >&2
       continue
     }
     fi
@@ -141,7 +141,7 @@ function set_supported_tests {
     test_fp="$errorcases_path/$FILE"
     if ! [[ -f $test_fp && -x $test_fp ]] ; then {
       skipped=$((skipped+1))
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Ignoring errtest $FILE (at $test_fp), not an executable file.\e[0m" >&2
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Skip errtest $FILE (at $test_fp), not an executable file.\e[0m" >&2
       continue
     }
     fi
@@ -292,6 +292,16 @@ function usage {
   echo_options
 }
 
+function escape_colorcodes_tee {
+  file="$1"
+  outfile="$2"
+  echo "" >"$outfile"
+  #sed -r 's/\/\\3/g' "$file"
+  #sed -e 's/\\033\[/COLOR[/g' -e 's/COLOR\[1;3/"<colorTag[Heavy,/g' -e 's/COLOR\[0;3/"<colorTag[Light,/g' -e 's/\\e\[0m/\]>"/g' "$file" >>"$outfile"
+  #sed 's/\x1B\[\([0-9]\{1,2\}\(;[0-9]\{1,2\}\)\?\)\?[mGK]//g' <"$file"
+  cat -e "$file" | tee "$outfile"
+}
+
 function escape_colorcodes {
   file="$1"
   outfile="$2"
@@ -308,13 +318,15 @@ function record_test {
   echo "" > "$tfp.stderr"
   tmp_stdout="$(mktemp)"
   tmp_stderr="$(mktemp)"
-  run_test "$tfp" >>"$tmp_stdout" 2>>"$tmp_stderr"
+  (run_test "$tfp" >>"$tmp_stdout" 2>>"$tmp_stderr")
   res=$?
-  echo "r: $res" >> "$tmp_stdout"
+  #echo "r: $res" >> "$tmp_stdout"
   escape_colorcodes "$tmp_stdout" "$tfp.stdout"
   escape_colorcodes "$tmp_stderr" "$tfp.stderr"
   rm -f "$tmp_stdout" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($tmp_stdout). Why?\n"
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$tmp_stdout".\e[0m" >&2
   rm -f "$tmp_stderr" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($tmp_stderr). Why?\n"
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$tmp_stderr".\e[0m" >&2
 }
 
 function run_test {
@@ -695,12 +707,13 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
     if [[ $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
       echo -e "\033[1;31m[TEST]    ( $query ) is not a supported test.\e[0m\n"
       echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
-      exit 1
-    } elif [[ ! -z $query && $test_mode_flag -eq 1 ]] ; then { #If we're in test mode (should be always true here...), gently tell the user that the version is not supported
+    } elif [[ -z $test_name && -z $query && $test_mode_flag -eq 1 ]] ; then { #If we're in test mode (should be always true here...), we tell the user that the tag is supported by amboso but something failed.
       keep_run_txt=""
       [[ $init_flag -gt 0 ]] && keep_run_txt="$mode_txt[INIT]"
       [[ $purge_flag -gt 0 ]] && keep_run_txt="$mode_txt[PURGE]"
-      echo -e "\n\033[1;33m[TEST]    ( $query ) is not a supported tag, but we keep running to do $keep_run_txt.\e[0m" >&2
+      echo -e "\n\033[1;33m[TEST]    ( \"empty\"$query ) is not a supported tag , but we go on to do $keep_run_txt.\e[0m" >&2
+    } elif [[ -z $test_name && ! -z $query ]] ; then {
+      echo -e "\n\033[1;33m[TEST]    ( $query ) is not a supported tag, but we go on to do $keep_run_txt.\e[0m" >&2
     }
     fi
   } else {
@@ -711,6 +724,7 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
 
   relative_testpath="$test_path"
 
+
   if [[ $build_flag -gt 0 ]] ; then {
     echo "[TEST]    recording: ( $relative_testpath )."
     record_test "$relative_testpath"
@@ -719,48 +733,84 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
     delete_test "$relative_testpath"
   } elif [[ $init_flag -gt 0 ]] ; then {
     echo "[TEST]    recording all: query ( $relative_testpath )."
+  echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
+    for i in $(seq 0 $(($tot_tests-1))); do {
+      TEST="${supported_tests[$i]}"
+      verb=""
+      gitm=""
+      [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[TEST]    Recording ( $TEST ) ( $(($i+1)) / $tot_tests )" >&2
+      ( "$prog_name" -D "$scripts_dir" -b"$verb"t "$TEST" 2>/dev/null ; exit "$?")
+      clean_res="$?"
+
+    }
+    done
     #init_all_tests "$relative_testpath"
   } elif [[ $purge_flag -gt 0 ]] ; then {
     echo "[TEST]    deleting all: query ( $relative_testpath )."
     #purge_all_tests "$relative_testpath"
   }
   fi
+  [[ -z $query && $init_flag -eq 1 && $purge_flag -eq 0 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no query.\e[0m" && exit 1
+  [[ -z $query && $init_flag -eq 0 && $purge_flag -eq 1 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -p flag, with no query.\e[0m" && exit 1
+  [[ -z $relative_testpath && $init_flag -eq 0 && $purge_flag -eq 1 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -p flag, with no testpath. ( $relative_testpath ).\e[0m" && exit 1
+  [[ -z $relative_testpath && $init_flag -eq 1 && $purge_flag -eq 0 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no testpath. ( $relative_testpath ).\e[0m" && exit 1
+  [[ -z $relative_testpath ]] && echo -e "\033[1;31m[ERROR]    Can't proceed with no testpath. ( $relative_testpath ).\e[0m" && exit 1
   run_tmp_out="$(mktemp)"
   run_tmp_escout="$(mktemp)"
   run_tmp_err="$(mktemp)"
   run_tmp_escerr="$(mktemp)"
   run_test "$relative_testpath" >>"$run_tmp_out" 2>>"$run_tmp_out"
-  escape_colorcodes "$run_tmp_out" "$run_tmp_escout"
-  rm -f "$run_tmp_out" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\n"
+  escape_colorcodes_tee "$run_tmp_out" "$run_tmp_escout"
+  rm -f "$run_tmp_out" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\n"
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_out".\e[0m" >&2
   escape_colorcodes "$run_tmp_err" "$run_tmp_escerr"
-  rm -f "$run_tmp_err" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\n"
+  rm -f "$run_tmp_err" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\n"
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_err".\e[0m" >&2
   #Testing diff for escaped stdout
-  ( diff "$run_tmp_escout" "$relative_testpath".stdout ) #2>/dev/null 1>&2
+  ( diff "$run_tmp_escout" "$relative_testpath".stdout ) 2>/dev/null 1>&2
   diff_res="$?"
+  out_res=""
   if [[ "$diff_res" -eq 0 ]]; then {
-    echo -e"\n\n\nIIIIIif\n\n"
+    out_res="pass"
     #cat "$run_tmp_escout"
   } else {
-    echo "\n\n\nELSE\n\n"
+    out_res="fail"
     #cat "$run_tmp_escout"
   }
   fi
-  rm -f "$run_tmp_escout" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escout). Why?\n"
+  rm -f "$run_tmp_escout" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escout). Why?\n"
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escout".\e[0m" >&2
   #Testing diff for escaped stderr
-  ( diff "$run_tmp_escerr" "$relative_testpath".stderr ) #2>/dev/null 1>&2
+  ( diff "$run_tmp_escerr" "$relative_testpath".stderr ) 2>/dev/null 1>&2
   diff_res="$?"
   if [[ "$diff_res" -eq 0 ]]; then {
-    echo -e"\n\n\nIIIIIif\n\n"
+    err_res="pass"
     #cat "$run_tmp_escerr"
   } else {
-    echo "\n\n\nELSE\n\n"
+    err_res="fail"
     #cat "$run_tmp_escerr"
   }
   fi
   rm -f "$run_tmp_escerr" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escerr). Why?\n"
-  echo "[TEST]    Done testing, we quit."
-  #TODO: init/purge tests
-  exit 0;
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escerr".\e[0m" >&2
+  if [[ $build_flag -gt 0 ]] ; then {
+    #We simulate success since we're recording
+    echo -e "\033[1;32m[TEST]    Phony pass.\e[0m"
+    echo -e "\033[1;32m    (out: $out_res)\e[0m"
+    echo -e "\033[1;32m    (err: $err_res)\e[0m"
+    exit 0; #We return earlier
+  } elif [[ $out_res = "pass" && $err_res = "pass" ]]; then {
+    echo -e "\033[1;32m[TEST]    Passed.\e[0m"
+    exit 0; #We return earlier
+  } elif [[ $out_res = "fail" ]] ; then {
+    echo -e "\033[1;31m[TEST]    Failed: stdout changed.\e[0m"
+  } elif [[ $err_res = "fail" ]] ; then {
+    echo -e "\033[1;31m[TEST]    Failed: stderr changed.\e[0m"
+  } else {
+    echo -e "\033[1;31m[ERROR]    Unexpected values (o:$out_res/e:$err_res) should be either pass or fail.\e[0m. How?"
+  }
+  fi
+  exit 1;
 }
 fi
 
@@ -776,11 +826,12 @@ if [[ -z $version ]]; then {
     echo -e "\033[1;31m[ERROR]    ( $query ) is not a supported tag.\e[0m\n"
     echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
     exit 1
-  } elif [[ ! -z $query && $test_mode_flag -eq 0 ]] ; then { #If we're not in test mode, gently tell the user that the version is not supported
+  } elif [[ ! -z $query && $test_mode_flag -gt 0 ]] ; then { #If we're in test mode, gently tell the user that the version is not supported
     keep_run_txt=""
     [[ $init_flag -gt 0 ]] && keep_run_txt="$mode_txt[INIT]"
     [[ $purge_flag -gt 0 ]] && keep_run_txt="$mode_txt[PURGE]"
-    echo -e "\n\033[1;33m[DEBUG]    ( $query ) is not a supported tag, but we keep running to do $keep_run_txt.\e[0m" >&2
+    echo -e "\n\033[1;33m[DEBUG]    ( $query ) is not a supported test. $keep_run_txt.\e[0m" >&2
+    exit 1;
   }
   fi
 }
