feat: 1.8.0 Use new stego format (#56)
 - Switch to set_amboso_stego_info() from set_versions_info()
 - Drop legacy set_info functions
 - Assert test info is known in test mode
 - Check if awk is available

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -30,9 +30,9 @@ kernel_release="$(uname -r)"
 kernel_version="$(uname -v)"
 machine_name="$(uname -m)"
 os_name="$(uname -o)"
-amboso_currvers="1.7.4"
-expected_AMBOSO_API_LVL="1.7.4"
-amboso_testflag_version="1.7.2"
+amboso_currvers="1.8.0"
+expected_AMBOSO_API_LVL="1.8.0"
+amboso_testflag_version="1.8.0"
 export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 # check recursion
 if [[ "${AMBOSO_LVL_REC}" -le "2" ]]; then
@@ -505,11 +505,9 @@ fi
 
 #We always notify of missing -K argument, if in test mode
 if [[ $test_mode_flag -gt 0 && ! $testdir_flag -gt 0 ]] ; then {
-  set_source_info "$milestones_dir"
-  kazoj_dir="${sources_info[3]}"
-  set_tests_info "$kazoj_dir"
+  set_amboso_stego_info "$milestones_dir/stego.lock" "$verbose_flag"
   res="$?"
-  [[ $res -eq 0 ]] || printf "\033[0;33m[WARN]\e[0m    Problems when doing set_tests_info($kazoj_dir).\n\n"
+  [[ $res -eq 0 ]] || printf "\033[0;33m[WARN]\e[0m    Problems when doing set_amboso_stego_info($kazoj_dir).\n\n"
   set_supported_tests "$kazoj_dir"
   res="$?"
   [[ $res -eq 0 ]] || printf "\033[0;33m[WARN]\e[0m    Problems when doing set_supported_tests($kazoj_dir).\n\n"
@@ -591,8 +589,6 @@ if [[ $bighelp_flag -gt 0 ]]; then {
   }
   fi
   echo_amboso_version
-  set_source_info "$milestones_dir"
-  set_supported_versions "$milestones_dir"
   amboso_help
   echo_timer "$amboso_start_time"  "Show big help" "2"
   exit 0
@@ -603,11 +599,19 @@ fi
 
 #TODO: check if scripts_dir is needed anywhere... why
 scripts_dir="$milestones_dir" # MUST BE SET before checking for -S and -E
-set_supported_versions "$scripts_dir" # Might as well do it now
-set_source_info "$milestones_dir"
-kazoj_dir="${sources_info[3]}" #TODO: don't think this should be overwritten here if assigned earlier
-use_automake_version="${sources_info[4]}"
-set_tests_info "$kazoj_dir"
+set_amboso_stego_info "$milestones_dir/stego.lock" "$verbose_flag"
+if [[ ! $? -eq 0 ]] ; then {
+  printf "\033[1;31m[CRITICAL]    Could not set amboso stego info.\033[0m\n"
+  exit 1
+}
+fi
+
+# LEGACY
+#      set_supported_versions "$scripts_dir" # Might as well do it now
+#      set_source_info "$milestones_dir"
+#      kazoj_dir="${sources_info[3]}" #TODO: don't think this should be overwritten here if assigned earlier
+#      use_automake_version="${sources_info[4]}"
+#      set_tests_info "$kazoj_dir"
 set_supported_tests "$kazoj_dir"
 
 if [[ $verbose_flag -gt 1 ]]; then {
@@ -623,29 +627,34 @@ if [[ $verbose_flag -gt 1 ]]; then { #WIP
 }
 fi
 
-#If we're in test mode and test dir was not passed, we check if "./kazoj" is a directory and use that. If it isn't, we may get the name from stego.lock. If that is not a directory, we quit immediately.
+#If we're in test mode and test dir was not set, we check if "./kazoj" is a directory and use that. If it isn't, we may get the name from stego.lock. If that is not a directory, we quit immediately.
 if [[ -z $kazoj_dir && $test_mode_flag -gt 0 ]] ; then {
-  if [[ "$amboso_currvers" > "$amboso_testflag_version" || "$amboso_currvers" = "$amboso_testflag_version" ]] ; then {
-     if [[ -d "./kazoj" ]]; then {
-       kazoj_dir="./kazoj"
-       set_tests_info "$kazoj_dir"
-       set_supported_tests "$kazoj_dir"
-       [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && printf "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m\n" >&2
-     } else {
-       [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && printf "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m\n" >&2
-       set_source_info "$milestones_dir"
-       kazoj_dir="${sources_info[3]}"
-       set_tests_info "$kazoj_dir"
-       set_supported_tests "$kazoj_dir"
-       [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && printf "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m\n" >&2
-     }
-     fi
-  } else {
-     printf "\033[1;31m[ERROR]    No -K flag on a test run, amboso version is < ($amboso_testflag_version).\n    Quitting.\e[0m\n" #>&2
-     echo_timer "$amboso_start_time"  "No -K on test run" "3"
-     exit 0
-  }
-  fi
+
+  #TODO Do we need to do further checks for amboso_testflag_version?
+  printf "\033[1;31m[ERROR]    kazoj_dir was not set, while in test mode.\033[0m\n"
+  exit 3
+
+  # LEGACY
+  #
+  #if [[ "$amboso_currvers" > "$amboso_testflag_version" || "$amboso_currvers" = "$amboso_testflag_version" ]] ; then {
+  #   if [[ -d "./kazoj" ]]; then {
+  #     kazoj_dir="./kazoj"
+  #     set_tests_info "$kazoj_dir"
+  #     set_supported_tests "$kazoj_dir"
+  #     [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && printf "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m\n" >&2
+  #   } else {
+  #     [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && printf "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m\n" >&2
+  #     set_supported_tests "$kazoj_dir"
+  #     [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && printf "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m\n" >&2
+  #   }
+  #   fi
+  #} else {
+  #   printf "\033[1;31m[ERROR]    No -K flag on a test run, amboso version is < ($amboso_testflag_version).\n    Quitting.\e[0m\n" #>&2
+  #   echo_timer "$amboso_start_time"  "No -K on test run" "3"
+  #   exit 0
+  #}
+  #fi
+  #
 }
 fi
 
@@ -676,36 +685,31 @@ if [[ $big_list_flag -gt 0 ]]; then {
 }
 fi
 
-#If version for makefile support was not specified, it's read from the stego.lock (an empty value would work maybe)
-#We notify in verbose mode or not in quiet mode
+#If version for makefile support was not specified, we notify in verbose mode or not in quiet mode
 if [[ -z $makefile_version ]] ; then {
-  set_source_info "$milestones_dir"
-  makefile_version=${sources_info[2]}
-  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;33m[DEBUG]    No -F flag, reading stego.lock for target makefile support version.\e[0m\n" >&2 # && usage && exit 1
+  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;31m[ASSERT-FALSE]    makefile_version was empty.\e[0m\n" >&2
+  exit 1
 }
 fi
 
 #We notify of missing -E argument if we're in verbose mode or not in quiet mode
 if [[ -z $exec_entrypoint ]] ; then {
-  set_source_info "$milestones_dir"
-  exec_entrypoint=${sources_info[1]}
-  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;33m[DEBUG]    No -E flag, reading stego.lock for target bin.\e[0m\n" >&2 # && usage && exit 1
+  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;31m[ASSERT-FALSE]    exec_entrypoint was empty.\e[0m\n" >&2
+  exit 1
 }
 fi
 
 #We notify of missing -S argument if we're in verbose mode or not in quiet mode
 if [[ -z $source_name ]] ; then {
-  set_source_info "$milestones_dir"
-  source_name=${sources_info[0]}
-  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;33m[DEBUG]    No -S flag, reading stego.lock for target sourcename.\e[0m\n" >&2 # && usage && exit 1
+  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;31m[ASSERT-FALSE]    source_name was empty.\e[0m\n" >&2
+  exit 1
 }
 fi
 
 #We notify of missing -A argument if we're in verbose mode or not in quiet mode
 if [[ -z $use_autoconf_version ]] ; then {
-  set_source_info "$milestones_dir"
-  use_autoconf_version=${sources_info[4]}
-  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;33m[DEBUG]    No -A flag, reading stego.lock for autoconf support version.\e[0m\n" >&2 # && usage && exit 1
+  [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && printf "\033[1;31m[ASSERT-FALSE]    use_autoconf_version was empty.\e[0m\n" >&2
+  exit 1
 }
 fi
 
