1.1.1 Introduced list tags (#6)

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,7 +2,7 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
-amboso_version="amboso version 1.1.0"
+amboso_version="amboso version 1.1.1"
 
 function echo_amboso_version {
   echo "$amboso_version"
@@ -23,13 +23,13 @@ function set_supported_versions {
 
     was_git_tag=0
     was_base_tag=0
-    for tag in $(echo "$line" | grep -v '^?' | cut -d '#' -f 1 | grep -v '^$'); do {
+    for tag in $(echo "$line" | grep -v '^?' | cut -d '#' -f 1 | cut -d ' ' -f 1 | grep -v '^$'); do {
       read_git_mode_tags[git_tags_count]="$tag"
       git_tags_count=$(($git_tags_count+1))
       was_git_tag=1
     }
     done
-    for tag in $(echo "$line" | grep '^?'| cut -d '?' -f2 | cut -d '#' -f 1 | grep -v '^$'); do {
+    for tag in $(echo "$line" | grep '^?'| cut -d '?' -f2 | cut -d '#' -f 1 | cut -d ' ' -f1 | grep -v '^$'); do {
       read_base_mode_tags[base_tags_count]="$tag"
       base_tags_count=$(($base_tags_count+1))
       was_base_tag=1
@@ -78,7 +78,7 @@ function set_source_info {
 
     #echo "Text read from file: ( $line )"
     #echo "Text read from file, no comments: ( $( echo "$line" | cut -d '#' -f 1 ) )"
-    sources_info[k]=$(echo "$line" | cut -d '#' -f 1)
+    sources_info[k]=$(echo "$line" | cut -d '#' -f 1 | cut -d ' ' -f 1 )
     k=$((k+1))
     [[ $k -eq 3 ]] && break #we only read the first two lines
   done < "$dir/stego.lock" 2>/dev/null
@@ -88,49 +88,55 @@ function set_source_info {
   #echo "source info array contents are: ( ${sources_info[@]} )" >&2
 }
 
-function usage {
-  mode_txt="\033[1;34mgit\e[0m"
-  [[ $base_mode_flag -gt 0 ]] && mode_txt="\033[1;31mbase\e[0m"
-  echo -e "Usage: $(basename $prog_name) [OPTION]... VERSION_QUERY\n"
-  echo "    Query for a build version"
-  echo -e "\n    $tot_vers Supported tags for current mode ( $mode_txt )."
-  for i in $(seq 0 $(($tot_vers-1))); do { #Print currently supported versions (only ones conforming to mode)
-    (( $i % 4 == 0)) && echo -en "\n        "
-    echo -en "\033[1;32m${supported_versions[i]}\e[0m  "
-  }
-  done
+function echo_othermode_tags {
+  dir="$1"
+  set_supported_versions "$dir"
+
   #Print remaining read versions not available in current mode
   if [[ $base_mode_flag -gt 0 ]] ; then {
     mode_txt="\033[1;34mgit\e[0m"
-    echo -e "\n    $count_git_versions Supported tags, when running in ( $mode_txt ) mode ."
+    echo -e "  ( $count_git_versions ) supported tags when running in ( $mode_txt ) mode."
+    echo -e "  Run again in ( $mode_txt ) mode to use them."
     for i in $(seq 0 $(($count_git_versions-1))); do {
-      (( $i % 4 == 0)) && echo -en "\n        "
-      echo -en "\033[0;33m${read_git_mode_tags[i]}\e[0m  "
+      (( $i % 4 == 0)) && [[ $i -ne 0 ]] && echo -en "\n        "
+      echo -en "    \033[0;33m${read_git_mode_tags[i]}\e[0m"
     }
     done
   } else {
     mode_txt="\033[1;31mbase\e[0m"
-    echo -e "\n    $count_base_versions Supported local versions, when in ( $mode_txt ) mode."
+    echo -e "  ( $count_base_versions ) supported tags when running in ( $mode_txt ) mode."
+    echo -e "  Run again in ( $mode_txt ) mode to use them."
     for i in $(seq 0 $(($count_base_versions-1))); do {
-      (( $i % 4 == 0)) && echo -en "\n        "
-      echo -en "\033[0;33m${read_base_mode_tags[i]}\e[0m  "
+      (( $i % 4 == 0)) && [[ $i -ne 0 ]] && echo -en "\n        "
+      echo -en "    \033[0;33m${read_base_mode_tags[i]}\e[0m"
     }
     done
   }
   fi
-  echo -e "\n\n    [OPTIONS]:\n"
-  echo -e "        -D TARGET_DIR        directory\n"
-  echo -e "                Specifies target directory\n"
-  echo -e "        -E TARGET_EXEC       executable\n"
-  echo -e "                Specifies target executable name\n"
-  echo -e "        -S TARGET_SOURCE       sourcename\n"
-  echo -e "                Specifies sourcefile name for single file mode.\n"
-  echo -e "        -M MAKEFILE_SUPPORT       tagname\n"
-  echo -e "                Specifies a tag name for lowest version to support make.\n"
+  echo "" >&2
+}
+
+function echo_supported_tags {
+  mode_txt="\033[1;34mgit\e[0m"
+  [[ $base_mode_flag -gt 0 ]] && mode_txt="\033[1;31mbase\e[0m"
+  dir="$1"
+  set_supported_versions "$dir"
+  echo -e "  ( $tot_vers ) supported tags for current mode ( $mode_txt )."
+  for i in $(seq 0 $(($tot_vers-1))); do { #Print currently supported versions (only ones conforming to mode)
+    (( $i % 4 == 0)) && [[ $i -ne 0 ]] && echo -en "\n"
+    echo -en "    \033[1;32m${supported_versions[i]}\e[0m"
+  }
+  done
+  echo "" >&2
+}
+
+function echo_options {
+  echo -e "\n    [RUNMODES]:\n"
   echo -e "        -B        base mode\n"
   echo -e "                Uses full source builds. Not recommended.\n"
   echo -e "        -g        git mode\n"
   echo -e "                Uses git checkouts of supported tags. Enabled by default.\n"
+  echo -e "    [OPERATIONS]:\n"
   echo -e "        -b        build\n"
   echo -e "                Tries building the binary if it's not available.\n"
   echo -e "        -r        run\n"
@@ -141,12 +147,22 @@ function usage {
   echo -e "                Tries building all supported versions.\n"
   echo -e "        -p        purge\n"
   echo -e "                Removes all tags binaries and quits.\n"
+  echo -e "    [OPTIONS]:\n"
+  echo -e "        -D TARGET_DIR        directory\n"
+  echo -e "                Specifies target directory\n"
+  echo -e "        -E TARGET_EXEC       executable\n"
+  echo -e "                Specifies target executable name\n"
+  echo -e "        -S TARGET_SOURCE       sourcename\n"
+  echo -e "                Specifies sourcefile name for single file mode.\n"
+  echo -e "        -M MAKEFILE_SUPPORT       tagname\n"
+  echo -e "                Specifies a tag name for lowest version to support make.\n"
+  echo -e "    [INFO]:\n"
+  echo -e "        -l/L        list\n"
+  echo -e "                Prints supported tags for current mode (all modes if L) and quits.\n"
   echo -e "        -V        verbose\n"
   echo -e "                More debug output.\n"
-  echo -e "        -h        help\n"
-  echo -e "                Prints help info in paged format.\n"
-  echo -e "        -H        help\n"
-  echo -e "                Prints help message and quits.\n"
+  echo -e "        -h/H        help\n"
+  echo -e "                Prints help info (paged if -h) and quits.\n"
   echo -e "        -v        version\n"
   echo -e "                Prints version message and quits.\n"
 }
@@ -158,6 +174,15 @@ function git_mode_check {
   is_git_repo="$?"
   [[ $is_git_repo -gt 0 ]] && echo -e "\n\033[1;31m[ERROR]    Not running in a git repo. Try running with -B to use base mode.\e[0m\n" && exit 1
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;34m[AMBOSO-MODE]    Running in git mode.\e[0m" >&2
+}
+
+function usage {
+  echo -e "Usage: $(basename $prog_name) [OPTION]... VERSION_QUERY\n"
+  echo "    Query for a build version"
+  #echo_supported_tags "$milestones_dir"
+  #echo ""
+  #echo_othermode_tags "$milestones_dir"
+  echo_options
 }
 
 #Prepare flag values to default value
@@ -178,8 +203,10 @@ vers_make_flag=0
 makefile_version=""
 git_mode_flag=1 #By default we run in git mode
 base_mode_flag=0
+big_list_flag=0
+small_list_flag=0
 
-while getopts "M:S:E:D:BgVbpHhrivd" opt; do
+while getopts "M:S:E:D:BgVbpHhrivdlL" opt; do
   case $opt in
     S )
       source_name="$OPTARG"
@@ -196,6 +223,12 @@ while getopts "M:S:E:D:BgVbpHhrivd" opt; do
     M )
       vers_make_flag=1
       makefile_version="$OPTARG"
+      ;;
+    L )
+      big_list_flag=1
+      ;;
+    l )
+      small_list_flag=1
       ;;
     H )
       bighelp_flag=1
@@ -232,13 +265,11 @@ while getopts "M:S:E:D:BgVbpHhrivd" opt; do
       init_flag=1
       ;;
     \? )
-      echo "Invalid option: -$OPTARG" >&2
-      usage
+      echo "Invalid option: -$OPTARG. Run with -h for help." >&2
       exit 1
       ;;
     : )
-      echo "Option -$OPTARG requires an argument." >&2
-      usage
+      echo "Option -$OPTARG requires an argument. Run with -h for help." >&2
       exit 1
       ;;
   esac
@@ -251,7 +282,22 @@ done
 [[ $git_mode_flag -gt 0 ]] && git_mode_check #We are now sure we can quit immediately if not running in a git repo
 
 #We always notify of missing -D argument
-[[ ! $dir_flag -gt 0 ]] && milestones_dir="$(pwd)/bin/" && echo -e "\033[1;33m[DEBUG]    No -D flag, using ./bin for target dir. Run with -V to see more.\e[0m" >&2 #&& usage && exit 1
+[[ ! $dir_flag -gt 0 ]] && milestones_dir="$(pwd)/bin/" && echo -e "\033[1;33m[DEBUG]    No -D flag, using ( $milestones_dir ) for target dir. Run with -V to see more.\e[0m" >&2 #&& usage && exit 1
+
+#Check if we are printing tag list for current mode and exiting early
+if [[ $small_list_flag -gt 0 ]]; then {
+  echo_supported_tags "$milestones_dir"
+  exit 0
+}
+fi
+
+#Check if we are printing tag list for both modes and exiting early
+if [[ $big_list_flag -gt 0 ]]; then {
+  echo_supported_tags "$milestones_dir"
+  echo_othermode_tags "$milestones_dir"
+  exit 0
+}
+fi
 
 #Check if we are printing help info and exiting early
 if [[ $smallhelp_flag -gt 0 ]]; then {
@@ -408,49 +454,6 @@ if [[ $version > $makefile_version || $version = $makefile_version ]] ; then
   has_makefile=1
 fi
 
-#Check if we are deleting and exiting early
-#We skipped first deletion pass if purge mode is requested, since we will enter here later
-if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
-    clean_res=1
-  if [[ $has_makeclean -gt 0 && $base_mode_flag -gt 0 ]] ; then { #Running in git mode skips make clean
-    tool_txt="make clean"
-    has_bin=0
-    curr_dir=$(realpath .)
-    delete_path="$scripts_dir""v""$version"
-      if [[ ! -d $delete_path ]] ; then {
-        echo -e "\033[1;31m[ERROR]    '$delete_path' is not a valid directory.\n    Check your supported versions for details on ( $version ).\e[0m\n" #>&2
-      } elif [[ -x $scripts_dir/v$version/$exec_entrypoint ]] ; then { #Executable exists
-        has_bin=1 && echo -e "\033[0;33m[DELETE]   ( $version ) has an executable.\e[0m\n" >&2
-        cd "$delete_path"; make clean 2>/dev/null #1>&2
-        clean_res=$?
-        cd "$curr_dir"
-        exit "$clean_res"
-      } else {
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;31m[DELETE]   ( $versions ) does not have an executable at ( $delete_path ).\e[0m\n" # >&2
-           exit 1
-      }
-      fi
-  } else { #Doesn't have Makefile, build method 2. Running in git mode also skips using make clean
-    tool_txt="rm"
-    has_bin=0
-    if [[ -x $scripts_dir"/v$version"/"$exec_entrypoint" ]] ; then {
-      has_bin=1 && echo -e "\033[0;33m[DELETE]    ( $version ) has an executable.\e[0m" #>&2
-    }
-    fi
-    rm $(realpath "$scripts_dir"/"v$version/$exec_entrypoint") #2>/dev/null
-    clean_res=$?
-    if [[ $clean_res -eq 0 ]] ; then {
-      echo -e "\033[0;32m[DELETE]    Success on ( $version ).\e[0m" >&2
-    } else {
-      echo -e "\033[0;31m[DELETE]    Failure on ( $version ).\e[0m" >&2
-    }
-    fi
-    exit "$clean_res"
-  }
-  fi
-}
-fi
-
 #If we can't find the file we may try to build it
 if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
   echo -e "\n\033[1;33m[QUERY]    ( $version ) binary not found in ( $script_path ).\e[0m" #>&2
@@ -573,7 +576,50 @@ if [[ ! -z $version && $run_flag -eq 1 && -x $script_path/$exec_entrypoint ]] ; 
 } elif [[ ! -z $version && $run_flag -eq 0  ]] ; then {
   echo -e "\033[0;33m[DEBUG]    Running without -r flag, won't run.\e[0m" >&2
 } elif [[ -z $version && $run_flag -gt 0 ]] ; then {
-  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[DEBUG]    Running with -r flag but couldn't find bin!\e[0m\n" >&2
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[DEBUG]    Running with -r but requested an empty tag ( $version )!\e[0m" >&2
+}
+fi
+
+#Check if we are deleting and exiting early
+#We skipped first deletion pass if purge mode is requested, since we will enter here later
+if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
+    clean_res=1
+  if [[ $has_makeclean -gt 0 && $base_mode_flag -gt 0 ]] ; then { #Running in git mode skips make clean
+    tool_txt="make clean"
+    has_bin=0
+    curr_dir=$(realpath .)
+    delete_path="$scripts_dir""v""$version"
+      if [[ ! -d $delete_path ]] ; then {
+        echo -e "\033[1;31m[ERROR]    '$delete_path' is not a valid directory.\n    Check your supported versions for details on ( $version ).\e[0m\n" #>&2
+      } elif [[ -x $scripts_dir/v$version/$exec_entrypoint ]] ; then { #Executable exists
+        has_bin=1 && echo -e "\033[0;33m[DELETE]   ( $version ) has an executable.\e[0m\n" >&2
+        cd "$delete_path"; make clean 2>/dev/null #1>&2
+        clean_res=$?
+        cd "$curr_dir"
+        exit "$clean_res"
+      } else {
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;31m[DELETE]   ( $versions ) does not have an executable at ( $delete_path ).\e[0m\n" # >&2
+           exit 1
+      }
+      fi
+  } else { #Doesn't have Makefile, build method 2. Running in git mode also skips using make clean
+    tool_txt="rm"
+    has_bin=0
+    if [[ -x $scripts_dir"/v$version"/"$exec_entrypoint" ]] ; then {
+      has_bin=1 && [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[DELETE]    ( $version ) has an executable.\e[0m" >&2
+    }
+    fi
+    rm $(realpath "$scripts_dir"/"v$version/$exec_entrypoint") #2>/dev/null
+    clean_res=$?
+    if [[ $clean_res -eq 0 ]] ; then {
+      echo -e "\033[0;32m[DELETE]    Success on ( $version ).\e[0m" >&2
+    } else {
+      echo -e "\033[0;31m[DELETE]    Failure on ( $version ).\e[0m" >&2
+    }
+    fi
+    exit "$clean_res"
+  }
+  fi
 }
 fi
 
