feat: release candidate
Will be missing -p and -d, but control flow should be stable.
Still needs testing to see if we have to pass -T when we go for recursion in test -i.

chore: bump amboso bin

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,9 +2,9 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
-amboso_version="amboso version 1.2.0-devel"
-amboso_currvers="1.1.2"
+amboso_currvers="1.2.0"
 amboso_testflag_version="1.1.2"
+amboso_version="amboso version $amboso_currvers"
 
 function echo_amboso_version {
   echo "$amboso_version"
@@ -620,20 +620,22 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
 }
 fi
 
-if [[ $init_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
-  echo -e "\033[0;32m[TEST]    -i Will record all tests.\e[0m" >&2
+if [[ $init_flag -gt 0 && $test_mode_flag -gt 0 && $verbose_flag -gt 0 ]] ; then {
+  echo -e "\033[0;35m[TEST]    [-i]\e[0m    Will record all tests." >&2
 }
 fi
-if [[ $purge_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
-  echo -e "\033[0;32m[TEST]    -p Will delete all tests.\e[0m" >&2
+if [[ $purge_flag -gt 0 && $test_mode_flag -gt 0 && $verbose_flag -gt 0 ]] ; then {
+  :
+  #echo -e "\033[0;35m[TEST]    [-p]\e[0m    Will clean all tests." >&2
 }
 fi
-if [[ $build_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
-  echo -e "\033[0;32m[TEST]    -b Will record query.\e[0m" >&2
+if [[ $build_flag -gt 0 && $test_mode_flag -gt 0 && $verbose_flag -gt 0 ]] ; then {
+  echo -e "\033[0;35m[TEST]    [-b]\e[0m    Will record test query." >&2
 }
 fi
-if [[ $delete_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
-  echo -e "\033[0;32m[TEST]    -d Will delete query.\e[0m" >&2
+if [[ $delete_flag -gt 0 && $test_mode_flag -gt 0 && $verbose_flag -gt 0 ]] ; then {
+  :
+  #echo -e "\033[0;35m[TEST]    [-d]\e[0m    Will clean test query." >&2
 }
 fi
 
@@ -660,7 +662,7 @@ fi
 
 
 #If we don't have init or purge flag, we bail on a missing version argument
-if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 ]]; then {
+if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 && $test_mode_flag -eq 0 ]]; then {
   echo -e "\033[1;31m[ERROR]    Missing query.\e[0m\n"
   echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
   exit 1
@@ -684,6 +686,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       test_type="casetest"
       test_name="$query"
       test_path="$kazoj_dir/$cases_dir/${read_tests_files[$i]}"
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Recording cases ($i/$count_tests_names): $test_name\e[0m" >&2
       break; #done looking
     }
     fi
@@ -697,6 +700,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
 	test_type="errortest"
 	test_name="$query"
 	test_path="$kazoj_dir/$errors_dir/${read_errortests_files[$i]}"
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Recording error case ($i/$count_errortests_names): $test_name\e[0m" >&2
 	break; #done looking
       }
       fi
@@ -705,62 +709,73 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   }
   fi
 
-  if [[ -z $test_name ]]; then {
-    #We only freak out if we don't have test_mode, purge or init flags on
-    if [[ $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
-      echo -e "\033[1;31m[TEST]    ( $query ) is not a supported test.\e[0m\n"
-      echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
-    } elif [[ -z $test_name && -z $query ]] ; then {
-      #We tell the user that the tag is supported by amboso but something failed.
+  if [[ -z $test_path && (( $init_flag -gt 0 || $build_flag -gt 0 )) ]]; then {
+    #We may only freak out if we don't have init flag on
+    if [[ -z $test_path && -z $query ]] ; then {
       keep_run_txt=""
-      [[ $init_flag -gt 0 ]] && keep_run_txt="$mode_txt[INIT]"
-      [[ $purge_flag -gt 0 ]] && keep_run_txt="$mode_txt[PURGE]"
-      echo -e "\n\033[1;33m[TEST]    ( \"empty\"$query ) is not a supported tag , but we go on to do $keep_run_txt.\e[0m" >&2
-    } elif [[ -z $test_name && ! -z $query ]] ; then {
-      echo -e "\n\033[1;33m[TEST]    ( $query ) is not a supported tag, but we go on to do $keep_run_txt.\e[0m" >&2
+      [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( \"empty\"[$query] ) is not a supported tag , but we go on to $keep_run_txt.\e[0m" >&2
+    } elif [[ -z $test_path && ! -z $query ]] ; then {
+      keep_run_txt=""
+      [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( $query ) is not a supported tag, but we continue to $keep_run_txt.\e[0m" >&2
+      [[ $build_flag -gt 0 ]] && keep_run_txt="[BUILD]" && echo -e "\033[1;33m[TEST]    ( $query ) is not a supported tag, but we continue to $keep_run_txt.\e[0m" >&2
     } else {
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[TEST] expected:\n  $test_type\n\n  name: $test_name\n  path: $test_path\e[0m" >&2
-      echo -e "\033[0;32m[TEST]    target: ( $test_name ).\e[0m\n"
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[TEST] expected:\n  $test_type\n\n  name: $test_name\n  path: $test_path\e[0m"# >&2
+      echo -e "\033[0;32m[TEST]    target: ( $test_path ).\e[0m\n"
     }
     fi
+  } elif [[ -z $test_path && -z $query ]] ; then {
+    #Panic
+    echo -e "\033[1;31m[ERROR]    ( $test_name : at  $test_path ) is not a supported test.\e[0m\n"
+    echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
+    exit 1
   }
   fi
 
   relative_testpath="$test_path"
 
   if [[ $build_flag -gt 0 ]] ; then {
-    echo -e "\n[TEST]    Recording: ( $relative_testpath ).\n"
+    echo -e "\033[0;34m[TEST]    \"-b\" is set, Recording: ( $relative_testpath ).\e[0m" >&2
     #record_test "$relative_testpath"
   } elif [[ $delete_flag -gt 0 ]] ; then {
-    echo -e "\n[TEST]    Deleting: ( $relative_testpath )."
+    :
+    #echo -e "\033[0;34m[TEST]    \"-d\" is set, Deleting: ( $relative_testpath ).\e[0m" >&2
     #delete_test "$relative_testpath"
   } elif [[ $init_flag -gt 0 ]] ; then {
-    echo -e "\n[TEST]    Recording ALL: ( $relative_testpath )."
+    echo -e "\033[0;34m[TEST]    \"-i\" is set, Recording ALL: ( $relative_testpath ).\e[0m"
     echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
     for i in $(seq 0 $(($tot_tests-1))); do {
       TEST="${supported_tests[$i]}"
       verb=""
       gitm=""
-      [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[TEST]    Recording ( $TEST ) ( $(($i+1)) / $tot_tests )" >&2
+      [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[TEST]    Recording ALL: ( $(($i+1)) / $tot_tests ) ( $TEST )" >&2
       ( "$prog_name" -D "$scripts_dir" -b"$verb"t "$TEST" 2>/dev/null ; exit "$?")
       clean_res="$?"
     }
     done
     #init_all_tests "$relative_testpath"
   } elif [[ $purge_flag -gt 0 ]] ; then {
-    echo "[TEST]    Deleting ALL: ( $relative_testpath )."
+    :
+    #echo "[TEST]    Deleting ALL: ( $relative_testpath )."
     #purge_all_tests "$relative_testpath"
   }
   fi
-  [[ -z $query && $init_flag -eq 1 && $purge_flag -eq 0 ]] && echo -e "\033[1;33m[INIT]    Can't proceed further with no query, quitting.\e[0m" && exit 0
-  [[ -z $query && $init_flag -eq 0 && $purge_flag -eq 1 ]] && echo -e "\033[1;33m[PURGE]    Can't proceed further with no query, quitting.\e[0m" && exit 0
-  [[ -z $relative_testpath && $init_flag -eq 0 && $purge_flag -eq 1 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -p flag, with no testpath. ( $relative_testpath ).\e[0m" && exit 1
-  [[ -z $relative_testpath && $init_flag -eq 1 && $purge_flag -eq 0 ]] && echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no testpath. ( $relative_testpath ).\e[0m" && exit 1
-  [[ -z $relative_testpath ]] && echo -e "\033[1;31m[ERROR]    Can't proceed with no testpath. ( $relative_testpath ).\e[0m" && exit 1
+  if [[ -z $query && $init_flag -eq 0 ]] ; then {
+    echo -e "\033[1;33m[INIT]    Can't proceed further with no query, quitting.\e[0m" && exit 0
+  }
+  fi
+  if [[ -z $relative_testpath && $init_flag -eq 1 && ! -z $query ]] ; then {
+    echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no testpath. ( $relative_testpath ) will be ( $query ).\e[0m"
+  }
+  fi
+  if [[ -z $relative_testpath && $init_flag -eq 1 && -z $query ]] ; then {
+    echo -e "\033[1;31m[ERROR]    Can't proceed with no query.  ( q: $query, p: $relative_testpath ).\e[0m" && exit 1
+  }
+  fi
   run_tmp_out="$(mktemp)"
   run_tmp_escout="$(mktemp)"
   run_tmp_err="$(mktemp)"
   run_tmp_escerr="$(mktemp)"
+  echo -e "\033[1;33m[TEST]    Running ( $relative_testpath ).\e[0m"
   run_test "$relative_testpath" >>"$run_tmp_out" 2>>"$run_tmp_err"
   escape_colorcodes_tee "$run_tmp_out" "$run_tmp_escout"
   escape_colorcodes_tee "$run_tmp_err" "$run_tmp_escerr"
@@ -782,7 +797,15 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   out_res=""
   if [[ "$diff_res" -eq 0 ]]; then {
     out_res="pass"
-    [[ ! -z "$run_tmp_escout" && ! -z "$relative_testpath.stdout" ]] && echo -e "\033[0;32m[TEST]    Pass, both outputs are not empty."
+    if [[ ! -z "$run_tmp_escout" && ! -z "$relative_testpath.stdout" ]]; then {
+      #This one doesn't go on stderr since we still want it in recursive calls:
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Pass, both outputs are not empty.\e[0m"
+    } elif [[ -z "$run_tmp_escout" ]]; then {
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Pass, current stdout is empty. Is that expected?\e[0m">&2
+    } elif [[ -z "$relative_testpath.stdout" ]]; then {
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Pass, registered stdout is empty. Is that expected?\e[0m" >&2
+    }
+    fi
     if [[ $verbose_flag -gt 0 ]]; then {
       echo -e "\n\033[1;35m[TEST]    (stdout) Expected:\e[0m"
       cat "$relative_testpath.stdout"
@@ -807,7 +830,15 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   diff_res="$?"
   if [[ "$diff_res" -eq 0 ]]; then {
     err_res="pass"
-    [[ ! -z "$run_tmp_escerr" && ! -z "$relative_testpath.stderr" ]] && echo -e "\033[0;32m[TEST]    Pass, both outputs are not empty."
+    if [[ ! -z "$run_tmp_escerr" && ! -z "$relative_testpath.stderr" ]]; then {
+      #This one doesn't go on stderr since we still want it in recursive calls:
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Pass, both stderrs are not empty.\e[0m"
+    } elif [[ -z "$run_tmp_escerr" ]]; then {
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Pass, current run stderr is empty. Is that expected?\e[0m">&2
+    } elif [[ -z "$relative_testpath.stderr" ]]; then {
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Pass, registered stderr is empty. Is that expected?\e[0m" >&2
+    }
+    fi
     if [[ $verbose_flag -gt 0 ]]; then {
       echo -e "\n\033[1;35m[TEST]    (stderr) Expected:\e[0m"
       cat "$relative_testpath.stderr"
