feat: 1.3.1 stable test mode
Removed bugs from most wrong paths, I think the flags should now mostly work as intended.

fix: removed dirty output from git commands

chore: added a test for calls with a lot of flags
chore: added a test for updating helloworld so it reflects -vv output

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,12 +2,15 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
-amboso_currvers="1.3.0"
-amboso_testflag_version="1.1.2"
+amboso_currvers="1.3.1"
+amboso_testflag_version="1.3.0"
 amboso_version="amboso version $amboso_currvers"
 
 function echo_amboso_version {
   echo "$amboso_version"
+}
+function echo_amboso_version_short {
+  echo "$amboso_currvers"
 }
 
 function set_supported_versions {
@@ -323,10 +326,10 @@ function record_test {
   tmp_stdout="$(mktemp)"
   tmp_stderr="$(mktemp)"
   run_test "$tfp" >>"$tmp_stdout" 2>>"$tmp_stderr"
-  res=$?
+  res="$?"
   echo "r: $res" >> "$tmp_stdout"
-  escape_colorcodes "$tmp_stdout" "$tfp.stdout"
-  escape_colorcodes "$tmp_stderr" "$tfp.stderr"
+  escape_colorcodes_tee "$tmp_stdout" "$tfp.stdout"
+  escape_colorcodes_tee "$tmp_stderr" "$tfp.stderr"
   rm -f "$tmp_stdout" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($tmp_stdout). Why?\n"
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$tmp_stdout".\e[0m" >&2
   rm -f "$tmp_stderr" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($tmp_stderr). Why?\n"
@@ -383,6 +386,7 @@ testdir_flag=0
 kazoj_dir=""
 big_list_flag=0
 small_list_flag=0
+version_flag=0
 
 while getopts "M:S:E:D:K:BgVbpHhrivdlLtTq" opt; do
   case $opt in
@@ -438,8 +442,7 @@ while getopts "M:S:E:D:K:BgVbpHhrivdlLtTq" opt; do
       quiet_flag=1
       ;;
     v )
-      echo_amboso_version
-      exit 0
+      version_flag=$(($version_flag+1))
       ;;
     p )
       purge_flag=1
@@ -467,6 +470,15 @@ while getopts "M:S:E:D:K:BgVbpHhrivdlLtTq" opt; do
   esac
 tot_opts=$OPTIND
 done
+
+if [[ $version_flag -gt 1 ]] ; then {
+  echo_amboso_version_short
+  exit 0
+} elif [[ $version_flag -eq 1 ]] ; then {
+  echo_amboso_version
+  exit 0
+}
+fi
 
 #We check again if testmode was requested, and reset the other mode flags.
 if [[ $test_mode_flag -gt 0 ]] ; then {
@@ -680,6 +692,7 @@ verbm=""
 [[ $quiet_flag -gt 0 ]] && quietm="q"
 [[ $verbose_flag -gt 0 ]] && verbm="V"
 
+#If we have -t and not -T, we always check all tests
 if [[ $test_mode_flag -gt 0 && $big_test_mode_flag -eq 0 ]] ; then {
   for i in $(seq 0 $(($tot_tests-1))); do {
     echo -e "\033[1;34m[TEST]    Run:  \"$prog_name -Tt$quietm$verbm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m"
@@ -739,7 +752,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       test_type="casetest"
       test_name="$query"
       test_path="$kazoj_dir/$cases_dir/${read_tests_files[$i]}"
-      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Recording cases ($i/$count_tests_names): $test_name\e[0m" >&2
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Checking cases ($i/$count_tests_names): $test_name\e[0m" >&2
       break; #done looking
     }
     fi
@@ -753,7 +766,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
 	test_type="errortest"
 	test_name="$query"
 	test_path="$kazoj_dir/$errors_dir/${read_errortests_files[$i]}"
-        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Recording error case ($i/$count_errortests_names): $test_name\e[0m" >&2
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[TEST]    Checking error case ($i/$count_errortests_names): $test_name\e[0m" >&2
 	break; #done looking
       }
       fi
@@ -766,10 +779,10 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     #We may only freak out if we don't have init flag on
     if [[ -z $test_path && -z $query ]] ; then {
       keep_run_txt=""
-      [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( \"empty\"[$query] ) is not a supported tag , but we go on to $keep_run_txt.\e[0m" >&2
+      [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( \"empty\"[$query] ) is not a supported tag. $keep_run_txt.\e[0m" >&2 ; exit 1
     } elif [[ -z $test_path && ! -z $query ]] ; then {
       keep_run_txt=""
-      [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( $query ) is not a supported tag, but we continue to $keep_run_txt.\e[0m" >&2
+      [[ $init_flag -gt 0 ]] && keep_run_txt="[INIT]" && echo -e "\033[1;33m[TEST]    ( $query ) is not a supported tag, we quit at this point. $keep_run_txt.\e[0m" >&2 && exit 0
       [[ $build_flag -gt 0 ]] && keep_run_txt="[BUILD]" && echo -e "\033[1;33m[TEST]    ( $query ) is not a supported tag, but we continue to $keep_run_txt.\e[0m" >&2
     } else {
       [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]] && echo -e "\033[0;33m[TEST] expected:\n  $test_type\n\n  name: $test_name\n  path: $test_path\e[0m"# >&2
@@ -803,7 +816,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
       [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet flag mode to the subcalls
       [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[TEST]    Recording ALL: ( $(($i+1)) / $tot_tests ) ( $TEST )" >&2
       start_t=`date +%s.%N`
-      ( "$prog_name" -K "$kazoj_dir" -D "$scripts_dir" -b"$quietm""$verb"T "$TEST" 2>/dev/null ; exit "$?")
+      ( "$prog_name" -K "$kazoj_dir" -D "$scripts_dir" -b"$quietm""$verb"Tt "$TEST" 2>/dev/null ; exit "$?")
       record_res="$?"
       end_t=`date +%s.%N`
       runtime=$( echo "$end_t - $start_t" | bc -l )
@@ -817,16 +830,19 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     #purge_all_tests "$relative_testpath"
   }
   fi
-  if [[ -z $query && $init_flag -eq 0 ]] ; then {
-    echo -e "\033[1;33m[INIT]    Can't proceed further with no query, quitting.\e[0m" && exit 0
+  if [[ -z $relative_testpath && $init_flag -eq 0 ]] ; then {
+    #Exit 0 as intended behaviour FIXME
+    echo -e "\033[1;33m[TEST]    Can't proceed further with no valid target path, query was ( $query ). Quitting.\e[0m" && exit 0
   }
   fi
   if [[ -z $relative_testpath && $init_flag -eq 1 && ! -z $query ]] ; then {
-    echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no testpath. ( $relative_testpath ) will be ( $query ).\e[0m"
+    #Exit 0 as intended behaviour FIXME
+    echo -e "\033[1;31m[ERROR]    Can't proceed even with -i flag, with no testpath. ( p: $relative_testpath ) can't be be ( q: $query ).\e[0m" && exit 0
   }
   fi
   if [[ -z $relative_testpath && $init_flag -eq 1 && -z $query ]] ; then {
-    echo -e "\033[1;31m[ERROR]    Can't proceed with no query.  ( q: $query, p: $relative_testpath ).\e[0m" && exit 1
+    echo -e "\033[1;31m[ERROR]    Can't proceed with no query.  ( q: $query, p: $relative_testpath ).\e[0m"
+    exit 1
   }
   fi
   run_tmp_out="$(mktemp)"
@@ -835,14 +851,14 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   run_tmp_escerr="$(mktemp)"
   echo -e "\033[1;33m[TEST]    Running ( $relative_testpath ).\e[0m"
   run_test "$relative_testpath" >>"$run_tmp_out" 2>>"$run_tmp_err"
-  ran_res=$?
+  ran_res="$?"
   echo "r: $ran_res" >> "$run_tmp_out"
   escape_colorcodes_tee "$run_tmp_out" "$run_tmp_escout"
   escape_colorcodes_tee "$run_tmp_err" "$run_tmp_escerr"
-  if [[ $build_flag -eq 0 ]] ; then {
+  if [[ $build_flag -gt 0 ]] ; then {
     :
-    cp "$run_tmp_escout" "$relative_testpath".stdout || echo -e "Failed replacing stdout with new file."
-    cp "$run_tmp_escerr" "$relative_testpath".stderr || echo -e "Failed replacing stderr with new file."
+    cp "$run_tmp_escout" "$relative_testpath.stdout" || echo -e "Failed replacing stdout with new file."
+    cp "$run_tmp_escerr" "$relative_testpath.stderr" || echo -e "Failed replacing stderr with new file."
   } else {
     :
   }
@@ -929,9 +945,9 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     echo -e "\033[1;32m[TEST]    Passed.\e[0m"
     exit 0 #We return earlier
   } elif [[ $out_res = "fail" ]] ; then {
-   :#echo "failed" #We echoed before
+   : #echo "failed" #We echoed before
   } elif [[ $err_res = "fail" ]] ; then {
-   :#echo "failed" #We echoed before
+   : #echo "failed" #We echoed before
   } else {
     echo -e "\033[1;31m[ERROR]    Unexpected values (o:$out_res/e:$err_res) should be either pass or fail.\e[0m. How?"
   }
@@ -1001,7 +1017,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
           echo -e "\033[1;31m[ERROR]    Checkout of ( $version ) failed, this stego.lock tag does not work for the repo.\e[0m" #>&2
           comp_res=1
         } else { #Checkout successful, we build
-          git submodule update --init --recursive #We set all submodules to commit state
+          git submodule update --init --recursive 2>/dev/null #We set all submodules to commit state
           make >&2 #Never try to build if checkout fails
           comp_res=$?
           #Output is expected to be in the main dir:
@@ -1042,7 +1058,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
           echo -e "\033[1;31m[ERROR]    Checkout of ( $version ) failed, stego.lock may be listing a tag name not on the repo.\e[0m"
           comp_res=1
         } else {
-          git submodule update --init --recursive #We set all submodules to commit state
+          git submodule update --init --recursive 2>/dev/null#We set all submodules to commit state
           gcc "./$source_name" -o "$script_path"/"$exec_entrypoint" -lm 2>&2 #Never try to build if checkout fails
           comp_res=$?
           #All files generated during the build should be ignored by the repo, to avoid conflict when checking out
