chore: spent a lot of time finding a missing "fi"

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -491,8 +491,7 @@ set_supported_versions "$scripts_dir" # Might as well do it now
 
 #If we're in test mode and test dir was not passed, we check if "./kazoj" is a directory and use that. If it isn't, we may get the name from stego.lock. If that is not a directory, we quit immediately.
 if [[ -z $kazoj_dir && $test_mode_flag -gt 0 ]] ; then {
-  if [[ "$amboso_currvers" > "$amboso_testflag_version" ||
-        "$amboso_currvers" = "$amboso_testflag_version" ]] ; then {
+  if [[ "$amboso_currvers" > "$amboso_testflag_version" || "$amboso_currvers" = "$amboso_testflag_version" ]] ; then {
      if [[ -d "./kazoj" ]]; then {
        kazoj_dir=$(realpath "./kazoj")
        set_tests_info "$kazoj_dir"
@@ -642,8 +641,9 @@ fi
 #check arg num
 # nothing else is allowed
 #shift all the options
-for i in $(seq 0 $(( $tot_opts - 2 )) ); do
+for i in $(seq 0 $(( $tot_opts - 2 )) ); do {
   shift
+}
 done
 
 # $0 is now target version, at position 1 in the array ??
@@ -658,6 +658,7 @@ if [[ $tot_left_args -gt 1 ]]; then {
 }
 fi
 
+
 #If we don't have init or purge flag, we bail on a missing version argument
 if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 ]]; then {
   echo -e "\033[1;31m[ERROR]    Missing query.\e[0m\n"
@@ -670,9 +671,8 @@ if [[ $tot_left_args -lt 1 && $purge_flag -eq 0 && $init_flag -eq 0 ]]; then {
   echo "can we do init/purge?"
 }
 fi
-
 #Check if we are doing a test
-if [[ $test_mode_flag -gt 0 ]] ; then {
+if [[ $test_mode_flag -gt 0 ]]; then {
   #We expect $scripts_dir to end with /
   test_name=""
   test_type=""
@@ -680,7 +680,7 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
   for i in $(seq 0 $(($count_tests_names-1))); do {
     current_item="${read_tests_files[$i]}"
     #echo "checking $current_item"
-    if [[ $query = $current_item ]] ; then {
+    if [[ $query = $current_item ]]; then {
       test_type="casetest"
       test_name="$query"
       test_path="$kazoj_dir/$cases_dir/${read_tests_files[$i]}"
@@ -689,51 +689,54 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
     fi
   }
   done
-  [[ -z $test_name ]] && for i in $(seq 0 $(($count_errortests_names-1))); do {
-    current_item="${read_errortests_files[$i]}"
-    #echo "checking $current_item"
-    if [[ $query = $current_item ]] ; then {
-      test_type="errortest"
-      test_name="$query"
-      test_path="$kazoj_dir/$errors_dir/${read_errortests_files[$i]}"
-      break; #done looking
+  if [[ -z $test_name ]] ; then {
+    for i in $(seq 0 $(($count_errortests_names-1))); do {
+      current_item="${read_errortests_files[$i]}"
+      #echo "checking $current_item"
+      if [[ $query = $current_item ]] ; then {
+	test_type="errortest"
+	test_name="$query"
+	test_path="$kazoj_dir/$errors_dir/${read_errortests_files[$i]}"
+	break; #done looking
+      }
+      fi
     }
-    fi
+    done
   }
-  done
+  fi
 
   if [[ -z $test_name ]]; then {
     #We only freak out if we don't have test_mode, purge or init flags on
     if [[ $purge_flag -eq 0 && $init_flag -eq 0 ]] ; then {
       echo -e "\033[1;31m[TEST]    ( $query ) is not a supported test.\e[0m\n"
       echo -e "\033[1;33m           Run with -h for help.\e[0m\n"
-    } elif [[ -z $test_name && -z $query && $test_mode_flag -eq 1 ]] ; then { #If we're in test mode (should be always true here...), we tell the user that the tag is supported by amboso but something failed.
+    } elif [[ -z $test_name && -z $query ]] ; then {
+      #We tell the user that the tag is supported by amboso but something failed.
       keep_run_txt=""
       [[ $init_flag -gt 0 ]] && keep_run_txt="$mode_txt[INIT]"
       [[ $purge_flag -gt 0 ]] && keep_run_txt="$mode_txt[PURGE]"
       echo -e "\n\033[1;33m[TEST]    ( \"empty\"$query ) is not a supported tag , but we go on to do $keep_run_txt.\e[0m" >&2
     } elif [[ -z $test_name && ! -z $query ]] ; then {
       echo -e "\n\033[1;33m[TEST]    ( $query ) is not a supported tag, but we go on to do $keep_run_txt.\e[0m" >&2
+    } else {
+      [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[TEST] expected:\n  $test_type\n\n  name: $test_name\n  path: $test_path\e[0m" >&2
+      echo -e "\033[0;32m[TEST]    target: ( $test_name ).\e[0m\n"
     }
     fi
-  } else {
-    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[TEST] expected:\n  $test_type\n\n  name: $test_name\n  path: $test_path\e[0m" >&2
-    echo -e "\033[0;32m[TEST]    target: ( $test_name ).\e[0m\n"
   }
   fi
 
   relative_testpath="$test_path"
 
-
   if [[ $build_flag -gt 0 ]] ; then {
-    echo "[TEST]    recording: ( $relative_testpath )."
-    record_test "$relative_testpath"
+    echo "\n[TEST]    recording: ( $relative_testpath ).\n"
+    #record_test "$relative_testpath"
   } elif [[ $delete_flag -gt 0 ]] ; then {
     echo "[TEST]    deleting: ( $relative_testpath )."
     delete_test "$relative_testpath"
   } elif [[ $init_flag -gt 0 ]] ; then {
     echo "[TEST]    recording all: query ( $relative_testpath )."
-  echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
+    echo -e "\033[1;33m[DEBUG]    ( $tot_tests ) total tests ready.\e[0m" >&2
     for i in $(seq 0 $(($tot_tests-1))); do {
       TEST="${supported_tests[$i]}"
       verb=""
@@ -741,7 +744,6 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
       [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[TEST]    Recording ( $TEST ) ( $(($i+1)) / $tot_tests )" >&2
       ( "$prog_name" -D "$scripts_dir" -b"$verb"t "$TEST" 2>/dev/null ; exit "$?")
       clean_res="$?"
-
     }
     done
     #init_all_tests "$relative_testpath"
@@ -761,9 +763,17 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
   run_tmp_escerr="$(mktemp)"
   run_test "$relative_testpath" >>"$run_tmp_out" 2>>"$run_tmp_err"
   escape_colorcodes_tee "$run_tmp_out" "$run_tmp_escout"
+  escape_colorcodes_tee "$run_tmp_err" "$run_tmp_escerr"
+  if [[ $build_flag -eq 0 ]] ; then {
+    :
+    #cp "$run_tmp_escout" "$relative_testpath".stdout || echo -e "Failed replacing stdout with new file."
+    #cp "$run_tmp_escerr" "$relative_testpath".stderr || echo -e "Failed replacing stderr with new file."
+  } else {
+    echo ciao;
+  }
+  fi
   rm -f "$run_tmp_out" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\n"
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_out".\e[0m" >&2
-  escape_colorcodes "$run_tmp_err" "$run_tmp_escerr"
   rm -f "$run_tmp_err" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\n"
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_err".\e[0m" >&2
   #Testing diff for escaped stdout
@@ -807,13 +817,13 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escerr".\e[0m" >&2
   if [[ $build_flag -gt 0 ]] ; then {
     #We simulate success since we're recording
-    [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;35m[TEST]    Phony pass (recording).\e[0m"
+    echo -e "\033[1;35m[TEST]    Phony pass (recording).\e[0m"
     [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m    (out: $out_res)\e[0m"
     [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m    (err: $err_res)\e[0m"
-    exit 0; #We return earlier
+    exit 0 #We return earlier
   } elif [[ $out_res = "pass" && $err_res = "pass" ]]; then {
     echo -e "\033[1;32m[TEST]    Passed.\e[0m"
-    exit 0; #We return earlier
+    exit 0 #We return earlier
   } elif [[ $out_res = "fail" ]] ; then {
    :#echo "failed" #We echoed before
   } elif [[ $err_res = "fail" ]] ; then {
@@ -822,7 +832,7 @@ if [[ $test_mode_flag -gt 0 ]] ; then {
     echo -e "\033[1;31m[ERROR]    Unexpected values (o:$out_res/e:$err_res) should be either pass or fail.\e[0m. How?"
   }
   fi
-  exit 1;
+  exit 1
 }
 fi
 #End of test mode block
@@ -1084,5 +1094,4 @@ if [[ purge_flag -gt 0 ]]; then
   }
   fi
 fi
-
 exit 0
