feat: added build cases for git mode
fix: build in git mode depends on checkout succes

feat: passing -g flag when doing init

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -65,6 +65,8 @@ function usage {
   echo -e "                Specifies sourcefile name for single file mode.\n"
   echo -e "        -M MAKEFILE_SUPPORT       tagname\n"
   echo -e "                Specifies a tag name for lowest version to support make.\n"
+  echo -e "        -g        git mode\n"
+  echo -e "                Uses git checkouts of supported tags.\n"
   echo -e "        -b        build\n"
   echo -e "                Tries building the binary if it's not available.\n"
   echo -e "        -r        run\n"
@@ -79,6 +81,15 @@ function usage {
   echo -e "                Prints help info in paged format.\n"
   echo -e "        -H        help\n"
   echo -e "                Prints help message and quits.\n"
+}
+
+function git_mode_checks {
+  is_git_repo=0
+  #Check if we're inside a repo
+  git rev-parse --is-inside-work-tree 2>/dev/null 1>&2
+  is_git_repo="$?"
+  [[ $is_git_repo -gt 0 ]] && echo -e "\n[DEBUG]    Not running in a valid git repo." && exit 1
+  echo -e "\n[INFO]    Running in git mode."
 }
 
 #Prepare flag values to default value
@@ -96,8 +107,9 @@ bighelp_flag=0
 smallhelp_flag=0
 vers_make_flag=0
 makefile_version=""
+git_mode_flag=0
 
-while getopts "M:S:E:D:vbpHhri" opt; do
+while getopts "M:S:E:D:gvbpHhri" opt; do
   case $opt in
     S )
       source_name="$OPTARG"
@@ -120,6 +132,10 @@ while getopts "M:S:E:D:vbpHhri" opt; do
       ;;
     h )
       smallhelp_flag=1
+      ;;
+    g )
+      git_mode_flag=1
+      git_mode_checks #Quit immediately if not running in a git repo
       ;;
     v )
       verbose_flag=1
@@ -171,7 +187,7 @@ fi
 scripts_dir="$milestones_dir" # MUST BE SET before checking for -S and -E
 set_supported_versions "$scripts_dir" # Might as well do it now
 
-#If version for makefile support was not specified, it's assumed 0.0
+#If version for makefile support was not specified, it's read from the file (an empty value would work maybe)
 if [[ -z $makefile_version ]] ; then {
   set_source_info "$milestones_dir"
   makefile_version=${sources_info[2]}
@@ -210,11 +226,14 @@ if [[ $init_flag -gt 0 ]] ; then {
   for i in $(seq 0 $(($tot_vers-1))); do
     init_vers="${supported_versions[$i]}"
     #Build this vers
+    #Init mode ALWAYS tries building, even if we have the binary already ATM
     #Save verbose flag
     verb=""
+    gitm=""
     [[ $verbose_flag -gt 0 ]] && verb="v" && echo -e "\n[INIT]    Try building ( $init_vers )" >&2
-    #Sets the verbose flag but redirects stderr to /dev/null
-    $prog_name -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -b"$verb" "$init_vers" 2>/dev/null
+    [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
+    #First pass sets the verbose flag but redirects stderr to /dev/null
+    $prog_name -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -b"$verb""$gitm" "$init_vers" 2>/dev/null
     if [[ $? -eq 0 ]] ; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[INIT]    $init_vers binary ready.\e[0m" >&2
       count_bins=$(($count_bins +1))
@@ -223,10 +242,11 @@ if [[ $init_flag -gt 0 ]] ; then {
       [[ $verbose_flag -lt 1 ]] && verbose_hint="Run with -v to see more info."
       echo -e "\n\033[1;31m[INIT]    Failed build for $init_vers binary. $verbose_hint\e[0m\n"
       #try building again to get more output, since we discarded stderr before
+      #
       #we could just pass -v to the first call if we have it on
       if [[ $verbose_flag -gt 0 ]]; then {
-	echo -e "[INIT]    Running \033[1;33m$(basename "$prog_name") -bv $init_vers\e[0m." >&2
-	("$prog_name" -M "$makefile_version" -S "$source_name" -D "$scripts_dir" -E "$exec_entrypoint" -bv "$init_vers") >&2
+	echo -e "[INIT]    Checking errors, running \033[1;33m$(basename "$prog_name") -bv $init_vers\e[0m." >&2
+	("$prog_name" -M "$makefile_version" -S "$source_name" -D "$scripts_dir" -E "$exec_entrypoint" -bv"$gitm" "$init_vers") >&2
       }
       fi
     }
@@ -299,7 +319,6 @@ if [[ -z $version ]]; then {
 fi
 
 has_makefile=0
-# We hardcoded the splitting version at which we start using make
 if [[ $version > $makefile_version || $version = $makefile_version ]] ; then
   has_makefile=1
 fi
@@ -317,26 +336,69 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
     fi
     #we try to build
     tool_txt="single file gcc"
-    if [[ $has_makefile -gt 0 ]]; then {
+    if [[ $has_makefile -gt 0 ]]; then { #Make mode
       tool_txt="make"
       echo -e "$version >= $makefile_version, has Makefile" >&2
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Building ( $version ), using make.\e[0m" >&2
       curr_dir=$(realpath .)
       start_t=`date +%s.%N`
-      cd $script_path; make >&2
-      comp_res=$?
+      if [[ $git_mode_flag -eq 0 ]] ; then { #Building in base mode, we cd into target directory before make
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m" >&2
+        cd $script_path; make >&2
+        comp_res=$?
+      } else { #Building in git mode, we checkout the tag and move the binary after the build
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in git mode, checking out ( $version ).\e[0m" >&2
+        git checkout "$version" 2>/dev/null #Repo goes back to tagged state
+        checkout_res=$?
+        if [[ $checkout_res -gt 0 ]] ; then { #Checkout failed, we don't build and we set comp_res
+          echo -e "\033[1;31m[ERROR]    Checkout of ( $version ) failed, stego.lock may be listing a tag name not in the repo.\e[0m" >&2
+          comp_res=1
+        } else { #Checkout successful, we build
+          make >&2 #Never try to build if checkout fails
+          comp_res=$?
+          #Output is expected to be in the main dir:
+          if [[ ! -e ./$exec_entrypoint ]] ; then {
+            echo -e "\033[1;31m[ERROR]    $exec_entrypoint not found at ($pwd).\e[0m" >&2
+          } else {
+            mv "./$exec_entrypoint" "$script_path" #All files generated during the build should be ignored by the repo, to avoid conflict when checking out
+            [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Moved $exec_entrypointmode to $script_path.\e[0m" >&2
+          }
+          fi
+          git switch - #We get back to starting repo state
+        }
+        fi
+      }
+      fi
       end_t=`date +%s.%N`
       runtime=$( echo "$end_t - $start_t" | bc -l )
       cd "$curr_dir"
-    } else {
-      [[ $verbose_flag -gt 0 ]] && echo -e "\n$version < 0.6.6, single file build with gcc" >&2
+    } else { #Straight gcc mode
+      [[ $verbose_flag -gt 0 ]] && echo -e "\n$version < $makefile_version, single file build with gcc" >&2
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Building ( $version ), using gcc call.\e[0m" >&2
       #echo "" >&2 #new line for error output
       [[ -z $source_name ]] && echo -e "\n\033[1;31m[WTF-ERROR]    Missing source file name. ( $version ).\e[0m\n" && usage && exit 1
 
       start_t=`date +%s.%N`
-      gcc "$script_path"/"$source_name" -o "$script_path"/"$exec_entrypoint" -lm 2>&2
-      comp_res=$?
+      if [[ $git_mode_flag -eq 0 ]] ; then { #Building in base mode, we cd into target directory before make
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m" >&2
+        gcc "$script_path"/"$source_name" -o "$script_path"/"$exec_entrypoint" -lm 2>&2
+        comp_res=$?
+      } else { #Building in git mode, we checkout the tag and move the binary after the build
+        [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Running in git mode, checking out ( $version ).\e[0m" >&2
+        git checkout "$version" 2>/dev/null #Repo goes back to tagged state
+        checkout_res=$?
+        if [[ $checkout_res -gt 0 ]] ; then { #Checkout failed, we set comp_res and don't build
+          echo -e "\033[1;31m[ERROR]    Checkout of ( $version ) failed, stego.lock may be listing a tag name not on the repo.\e[0m" >&2
+          comp_res=1
+        } else {
+          gcc "./$source_name" -o "$script_path"/"$exec_entrypoint" -lm 2>&2 #Never try to build if checkout fails
+          comp_res=$?
+          #All files generated during the build should be ignored by the repo, to avoid conflict when checking out
+          git switch - #We get back to starting repo state
+        }
+        fi
+      }
+      fi
       end_t=`date +%s.%N`
       runtime=$( echo "$end_t - $start_t" | bc -l )
     }
