feat: 1.5.0 Base pack flag (#29)

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -8,9 +8,9 @@ if [[ "$EUID" -eq 0 ]] ; then {
 fi
 # Set recursion env var if not exists
 prog_name="$(readlink -f "$0")"
-amboso_currvers="1.4.9"
-expected_AMBOSO_API_LVL="1.4.8-b"
-amboso_testflag_version="1.4.8"
+amboso_currvers="1.5.0"
+expected_AMBOSO_API_LVL="1.5.0"
+amboso_testflag_version="1.4.9"
 export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 # check recursion
 if [[ "${AMBOSO_LVL_REC}" -le "2" ]]; then
@@ -74,11 +74,15 @@ small_list_flag=0
 version_flag=0
 silent_flag=0
 print_cfg_flag=0
+pack_flag=0
 
-while getopts "M:S:E:D:K:BgVbpHhrivdlLtTqsc" opt; do
+while getopts "M:S:E:D:K:BgVbpHhrivdlLtTqscz" opt; do
   case $opt in
     c )
       print_cfg_flag=1
+      ;;
+    z )
+      pack_flag=1
       ;;
     s )
       silent_flag=1
@@ -178,6 +182,7 @@ if [[ $print_cfg_flag -gt 0 ]] ; then {
 fi
 
 [[ $verbose_flag -gt 1 ]] && echo -e "\033[0;32m[PREP]    Done getopts.\e[0m" >&2
+[[ $verbose_flag -gt 0 && ! $prog_name = "anvil" ]] && echo -e "\033[1;36m[AMBOZO]\e[0m    Please, symlink me to \"anvil\".\n" >&2
 
 if [[ $(basename $(pwd)) == "amboso" ]] ; then {
   amboso_fn_path="$(realpath $(pwd))/amboso_fn.sh"
@@ -541,16 +546,18 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ]
     basem=""
     quietm=""
     silentm=""
+    packm=""
 
-    [[ $silent_flag -gt 0 ]] && silentm="s" #Pass verbose mode
+    [[ $pack_flag -gt 0 ]] && packm="z" #Pass pack op mode
+    [[ $silent_flag -gt 0 ]] && silentm="s" #Pass silent mode
     [[ $verbose_flag -gt 0 ]] && verb="V" #Pass verbose mode
-    [[ $build_flag -gt 0 ]] && buildm="b" #Pass build mode
+    [[ $build_flag -gt 0 ]] && buildm="b" #Pass build op mode
     [[ $base_mode_flag -gt 0 ]] && basem="B" #We make sure to pass on eventual base mode to the subcalls
     [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
-    [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet flag mode to the subcalls
+    [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet mode to the subcalls
     #First pass sets the verbose flag but redirects stderr to /dev/null
-    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[VERB]    Running \"$(dirname $(basename $prog_name)) -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -b$verb$gitm$basem$quietm$silentm $init_vers\" ( $(($i+1)) / $tot_vers )" >&2
-    "$prog_name" -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -b"$verb""$gitm""$basem""$quietm""$silentm" "$init_vers" 2>/dev/null
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;35m[VERB]    Running \"$(dirname $(basename $prog_name)) -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -b$verb$gitm$basem$quietm$silentm$packm $init_vers\" ( $(($i+1)) / $tot_vers )" >&2
+    "$prog_name" -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -b"$verb""$gitm""$basem""$quietm""$silentm""$packm" "$init_vers" 2>/dev/null
     if [[ $? -eq 0 ]] ; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[INIT]    $init_vers binary ready.\e[0m" >&2
       count_bins=$(($count_bins +1))
@@ -562,8 +569,8 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ]
       #
       #we could just pass -v to the first call if we have it on
       if [[ $verbose_flag -gt 0 || $quiet_flag -eq 0 ]]; then {
-	echo -e "[INIT]    Checking errors, running \033[1;33m$(basename "$prog_name") -bV $init_vers\e[0m." >&2
-	("$prog_name" -M "$makefile_version" -S "$source_name" -D "$scripts_dir" -E "$exec_entrypoint" -bV"$gitm""$basem" "$init_vers") >&2
+	echo -e "[INIT]    Checking errors, running \033[1;33m$(basename "$prog_name") -bV$packm $init_vers\e[0m." >&2
+	("$prog_name" -M "$makefile_version" -S "$source_name" -D "$scripts_dir" -E "$exec_entrypoint" -bVV"$gitm""$basem""$packm" "$init_vers") >&2
       }
       fi
     }
@@ -1063,11 +1070,11 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
             [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Moved $exec_entrypoint to $script_path.\e[0m" #>&2
           }
           fi
-          git switch - 2>/dev/null #We get back to starting repo state
+          git switch - #We get back to starting repo state
           switch_res="$?"
-          [[ $switch_res -gt 0 ]] && echo -e "\n\033[1;31m[ERROR]    Can't finish checkin out ($version). Abort." && exit 1
+          [[ $switch_res -gt 0 ]] && echo -e "\n\033[1;31m[ERROR]    Can't finish checking out ($version).\n    You may have a dirty index and may need to run \033[1;35\"git restore .\"\e[0m.\n Abort.\n" && exit 1
           git submodule update --init --recursive #We set all submodules to commit state
-          [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[BUILD]    Switched back to starting commit.\e[0m" >&2
+          [[ $quiet_flag -eq 0 ]] && echo -e "\033[0;32m[BUILD]    Switched back to starting commit.\e[0m"
         }
         fi
       }
@@ -1080,6 +1087,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
       [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Building ( $version ), using gcc call.\e[0m" >&2
       #echo "" >&2 #new line for error output
       [[ -z $source_name ]] && echo -e "\n\033[1;31m[WTF-ERROR]    Missing source file name. ( $version ).\e[0m\n" && usage && exit 1
+      [[ $pack_flag -gt 0 ]] && echo -e "\n\033[1;33m[PACK]    -z is not supported for ($tool_txt). TAG < ($makefile_version).\n\n    \033[1;35Current: ($version @ $source_name).\e[0m\n"
 
       start_t=`date +%s.%N`
       if [[ $git_mode_flag -eq 0 ]] ; then { #Building in base mode, we cd into target directory before make
@@ -1139,6 +1147,21 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
 
   }
   fi
+  #Check if we're packing the ready version
+  if [[ $pack_flag -gt 0 ]] ; then {
+    #We just leverage make pack and assume it's ready to roll
+    echo -e "\033[0;35m[PACK]    Running in base mode, expecting full source in $script_path.\e[0m" #>&2
+    make pack
+    pack_res=$?
+    if [[ $pack_res -gt 0 ]] ; then { #make pack failed
+      echo -e "\033[1;31m[PACK]    Packing ($version) in base mode, failed.\n    Expected source at ($script_path).\e[0m" #>&2
+    } else {
+      echo -e "\033[1;32m[PACK]    Packed ($version):\n    from  ($script_path)\e[0m" #>&2
+    }
+    fi
+  }
+  fi
+
 } elif [[ ! -z $query ]] ; then {
   app "$(echo_node silence_check query_invalid)"
   echo -e "\033[1;31m[QUERY]    ( $query ) invalid query, run with -V to see more.\e[0m"
@@ -1259,17 +1282,20 @@ if [[ purge_flag -gt 0 ]]; then
     basem=""
     quietm=""
     silentm=""
+    packm=""
+    [[ $pack_flag -gt 0 ]] && packm="z"
     [[ $silent_flag -gt 0 ]] && silentm="s"
     [[ $verbose_flag -gt 0 ]] && verb="V" && echo -e "\n[PURGE]    Trying to delete ( $purge_vers ) ( $(($i+1)) / $tot_vers )" >&2
     [[ $base_mode_flag -gt 0 ]] && basem="B" #We make sure to pass on eventual base mode to the subcalls
     [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
     [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet flag mode to the subcalls
     if [[ $quiet_flag -eq 0 ]] ; then {
-      echo -e "\033[1;35m[PURGE]    Running \"$(basename "$prog_name") -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -d$verb$gitm$basem$quietm$silentm $purge_vers 2>/dev/null\"\e[0m"
+      echo -e "\033[1;35m[PURGE]    Running \"$(basename "$prog_name") -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -d$verb$gitm$basem$quietm$silentm$packm $purge_vers 2>/dev/null\"\e[0m"
     }
     fi
-    ( $prog_name -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -d"$verb""$gitm""$basem""$quietm""$silentm" "$purge_vers" ) 2>/dev/null
+    ( $prog_name -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -d"$verb""$gitm""$basem""$quietm""$silentm""$packm" "$purge_vers" ) 2>/dev/null
     clean_res="$?"
+    #To be sure delete OP is gonna be the returning op here, we assume pack just never makes the script return, so it will always go to delete OP safely.
 
     #Check clean result
     if [[ $clean_res -eq 0 && $has_bin -gt 0 ]] ; then {
@@ -1286,8 +1312,8 @@ if [[ purge_flag -gt 0 ]]; then
       #we could just pass -v to the first call if we have it on
       if [[ $verbose_flag -gt 0 ]]; then {
 	echo -e "[PURGE]    Verbose flag was asserted as ($verbose_flag)." >&2
-	echo -e "[PURGE]    Checking errors, running \033[1;33m$(basename "$prog_name") -dV $purge_vers\e[0m." >&2
-	("$prog_name" -M "$makefile_version" -S "$source_name" -D "$scripts_dir" -E "$exec_entrypoint" -dV"$gitm""$basem" "$purge_vers") #>&2
+	echo -e "[PURGE]    Checking errors, running \033[1;33m$(basename "$prog_name") -dVV $purge_vers\e[0m." >&2
+	("$prog_name" -M "$makefile_version" -S "$source_name" -D "$scripts_dir" -E "$exec_entrypoint" -dVV"$gitm""$basem" "$purge_vers") #>&2
       }
       fi
     }
