fix: trying to make -t safe when used in a test

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -2,8 +2,8 @@
 # Bash script to run a milestone build providing the version number.
 
 prog_name="$0"
-amboso_currvers="1.4.0-devel"
-amboso_testflag_version="1.3.0"
+amboso_currvers="1.4.0"
+amboso_testflag_version="1.4.0"
 amboso_version="amboso version $amboso_currvers"
 
 PARENT_COMMAND=$(ps -o comm= $PPID)
@@ -14,10 +14,10 @@ export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 
 # check recursion
 if [[ "${AMBOSO_LVL_REC}" -le "2" ]]; then
-  [[ "$AMBOSO_LVL_REC" -eq 0 ]] && echo -e "\033[1;35m[AMBOSO]    Current version: $amboso_currvers\e[0m\n"
+  [[ $PARENT_COMMAND = "$prog_name" ]] && echo "what" && exit 1
 else
-  echo -e "\n[AMBOSO]    exceeded depth for recursion ( at ${AMBOSO_LVL_REC})"
-  exit 1
+  echo -e "\n[AMBOSO]    Exceeded depth for recursion ( nested ${AMBOSO_LVL_REC} times).\n"
+  exit 69
 fi
 # increment depth counter
 export AMBOSO_LVL_REC=$(($AMBOSO_LVL_REC+1))
@@ -277,7 +277,7 @@ function echo_supported_tags {
 }
 
 function echo_options {
-  echo -e "\n    [RUNMODES]:\n"
+  echo -e "\n    [MODES]:\n"
   echo -e "        -B        base mode\n"
   echo -e "                Uses full source builds. Not recommended.\n"
   echo -e "        -g        git mode\n"
@@ -325,7 +325,7 @@ function git_mode_check {
   git rev-parse --is-inside-work-tree 2>/dev/null 1>&2
   is_git_repo="$?"
   [[ $is_git_repo -gt 0 ]] && echo -e "\n\033[1;31m[ERROR]    Not running in a git repo. Try running with -B to use base mode.\e[0m\n" && exit 1
-  [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;34m[AMBOSO-MODE]    Running in git mode.\e[0m" >&2
+  [[ $verbose_flag -gt 0 ]] && echo -e "\033[1;34m[MODE]    Running in git mode.\e[0m" >&2
 }
 
 function usage {
@@ -514,12 +514,14 @@ done
 #Won't print call info for top level calls
 if [[ ${AMBOSO_LVL_REC} -gt 1 ]] ; then {
 #and 1+ nested test calls ( with -T, from -t calling -T)
-  echo -e "\033[1;34m[AMBOSO]    Recursive call , depth: ( $((${AMBOSO_LVL_REC}-1)) )\e[0m"
+  [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;34m[AMBOSO]    Amboso depth: ( $((${AMBOSO_LVL_REC}-1)) )\e[0m"
   if [[ $AMBOSO_LVL_REC -lt 2 ]] ; then {
     echo -e "\\n\n        args: (\"$@\")" >&2
     echo_current_tags >&2
   } elif [[ $AMBOSO_LVL_REC -gt 2 ]] ; then {
-    echo -e "[AMBOSO]    deep recursion, are you calling \"$prog_name\" in a test? ;)"
+    echo -e "[AMBOSO]    Deep recursion (>1), are you calling \"$prog_name\" in a test? ;)" >&2
+    #[[ $small_test_mode_flag -gt 0 ]] && echo "[ERROR]    Can't proceed and macro -t for -T on all tags." && exit 69
+    #[[ $test_mode_flag -gt 0 ]] && echo "[ERROR]    Can't proceed with test mode." && exit 69
   }
   fi
 }
@@ -534,12 +536,14 @@ if [[ $version_flag -gt 1 ]] ; then {
 }
 fi
 
+[[ "$AMBOSO_LVL_REC" -eq 0 ]] && echo -e "\033[1;35m[AMBOSO]    Current version: $amboso_currvers\e[0m\n"
+
 #We check again if testmode was requested, and reset the other mode flags.
 # -T always overrides -g and -B
 if [[ $test_mode_flag -gt 0 ]] ; then {
   git_mode_flag=0
   base_mode_flag=0
-  echo -e "\033[1;33m[AMBOSO-MODE]    Running in test mode.\e[0m" >&2
+  echo -e "\033[1;33m[MODE]    Running in test mode.\e[0m" >&2
 }
 fi
 
@@ -547,7 +551,7 @@ fi
 #If base_mode_flag is asserted, we always override git_mode_flag
 
 #Default mode with no flags should be git mode
-[[ $base_mode_flag -gt 0 ]] && git_mode_flag=0 && echo -e "\033[1;31m[AMBOSO-MODE]    Running in base mode, expecting full source builds.\e[0m" >&2
+[[ $base_mode_flag -gt 0 ]] && git_mode_flag=0 && echo -e "\033[1;31m[MODE]    Running in base mode, expecting full source builds.\e[0m" >&2
 [[ $git_mode_flag -gt 0 ]] && git_mode_check #We are now sure we can quit immediately if not running in a git repo
 
 #We always notify of missing -D argument
@@ -561,6 +565,33 @@ if [[ $test_mode_flag -gt 0 && ! $testdir_flag -gt 0 ]] ; then {
   set_supported_tests "$kazoj_dir"
   #kazoj_dir="$(pwd)/kazoj/"
   echo -e "\033[1;33m[DEBUG]    No -K flag, using ( $kazoj_dir ) for target dir. Run with -V to see more.\e[0m" >&2 #&& usage && exit 1
+}
+fi
+if [[ $test_mode_flag -gt 0 && $test_info_was_set -gt 0 ]] ; then {
+  if [[ $AMBOSO_LVL_REC -lt 3 ]] ; then {
+    echo -e "\033[1;32m[DEBUG]    bone dir: ( $cases_dir )\e[0m" >&2
+    echo -e "\033[1;32m           kulpo dir: ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
+  } else {
+    echo -e "\033[1;32m[DEBUG]    bone dir: ( $cases_dir )\e[0m" >&2
+    echo -e "\033[1;32m           kulpo dir: ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
+    echo -e "\n\033[1;31m[PANIC]    Running \"$prog_name\" using test mode in a program that will be called by test mode is not supported.\e[0m\n" #&& usage && exit 1
+    exit 69
+    #We return 69 and will check for this somewhere
+  }
+  fi
+} elif [[ $test_info_was_set -eq 0 && $test_mode_flag -gt 0 ]] ; then {
+  if [[ $AMBOSO_LVL_REC -lt 3 ]] ; then {
+    echo -e "\033[1;33m[DEBUG]    bone dir (NO -K passed to this call): ( $cases_dir )\e[0m" >&2
+    echo -e "\033[1;33m           kulpo dir (NO -K passed to this amboso call): ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
+  } else {
+    #Deep case: we're running a test, calling a program that calls amboso in test mode.
+    echo -e "\033[1;33m[DEBUG]    bone dir (NO -K passed to this call): ( $cases_dir )\e[0m" >&2
+    echo -e "\033[1;33m           kulpo dir (NO -K passed to this amboso call): ( $errors_dir )\e[0m" >&2 #&& usage && exit 1
+
+    echo -e "\n\033[1;31m[PANIC]    Running \"$prog_name\" using test mode in a program that will be called by test mode is not supported.\e[0m\n" >&2 #&& usage && exit 1
+    exit 1
+  }
+  fi
 }
 fi
 
@@ -615,14 +646,14 @@ if [[ -z $kazoj_dir && $test_mode_flag -gt 0 ]] ; then {
        kazoj_dir="./kazoj"
        set_tests_info "$kazoj_dir"
        set_supported_tests "$kazoj_dir"
-       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m" >&2
+       [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), using \"./kazoj\" as tests dir.\e[0m" >&2
      } else {
-       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
+       [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
        set_source_info "$milestones_dir"
        kazoj_dir="${sources_info[3]}"
        set_tests_info "$kazoj_dir"
        set_supported_tests "$kazoj_dir"
-       [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
+       [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[DEBUG]  No -K flag on a test run (amboso > $amboso_testflag_version), reading stego.lock.\e[0m" >&2
      }
      fi
   } else {
@@ -704,7 +735,7 @@ if [[ $init_flag -gt 0 && $test_mode_flag -eq 0 && $small_test_mode_flag -eq 0 ]
   start_t_init=`date +%s.%N`
   for i in $(seq 0 $(($tot_vers-1))); do
     init_vers="${supported_versions[$i]}"
-    [[ $quiet_flag -eq 0 ]] && echo -e "\n[INIT]    Trying to build ( $init_vers ) ( $(($i+1)) / $tot_vers )" >&2
+    [[ $quiet_flag -eq 0 ]] && echo -e "[INIT]    Trying to build ( $init_vers ) ( $(($i+1)) / $tot_vers )" >&2
     #Build this vers
     #Init mode ALWAYS tries building, even if we have the binary already ATM
     #Save verbose flag
@@ -793,7 +824,7 @@ if [[ $small_test_mode_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
 
   start_t_tests=`date +%s.%N`
   for i in $(seq 0 $(($tot_tests-1))); do {
-    [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;34m[TEST]    Run:  \"$prog_name -T$quietm$verbm$buildm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m" >&2
+    [[ $quiet_flag -eq 0 ]] && echo -e "\033[1;35m[TEST]    Running:  \"$prog_name -T$quietm$verbm$buildm -K $kazoj_dir -D $milestones_dir ${supported_tests[$i]}\"\e[0m" >&2
     start_t_curr_test=`date +%s.%N`
     "$prog_name" -T"$quietm""$verbm""$buildm" -K "$kazoj_dir" -D "$milestones_dir" "${supported_tests[$i]}"
     retcod="$?"
@@ -818,10 +849,12 @@ if [[ $small_test_mode_flag -gt 0 && $test_mode_flag -eq 0 ]] ; then {
     display_zero="" #what?
   }
   fi
-  echo -e "\033[0;34m[TEST]    Full testing took $display_zero$runtime_tests seconds ( $tot_tests done).\e[0m"
+  #echo -e "\033[0;34m[TEST]    Full testing took $display_zero$runtime_tests seconds ( $tot_tests done).\e[0m\n"
+  exit 0
 } elif [[ $small_test_mode_flag -gt 0 && $test_mode_flag -gt 0 ]] ; then {
-  echo -e "\033[1;31m[TEST]    Error: -t was asserted with -T. -t is a shortcut to run as -T on all tests found.\e[0m"
+  echo -e "\033[1;31m[TEST]    Error: -t was asserted with -T. -t is a shortcut to run as -T on all tests found.\e[0m\n"
   exit 1
+  echo "UNREACHABLE"
 }
 fi
 
@@ -1002,6 +1035,21 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   echo -e "\033[1;33m[TEST]    Running ( $relative_testpath ).\e[0m"
   run_test "$relative_testpath" >>"$run_tmp_out" 2>>"$run_tmp_err"
   ran_res="$?"
+
+  if [[ $ran_res -eq 69 ]] ; then {
+    echo "\033[1;31m[PANIC]    Test program returned 69, we follow suit.\e[0m\n"
+    #Delete tmpfiles
+    rm -f "$run_tmp_out" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\e[0m\n"
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_out".\e[0m" >&2
+    rm -f "$run_tmp_err" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_err). Why?\e[0m\n"
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_err".\e[0m" >&2
+    rm -f "$run_tmp_escout" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escout). Why?\n"
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escout".\e[0m" >&2
+    rm -f "$run_tmp_escerr" || echo "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_escerr). Why?\n"
+    [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escerr".\e[0m" >&2
+    exit 69
+  }
+  fi
   #echo "r: $ran_res" >> "$run_tmp_out"
   escape_colorcodes_tee "$run_tmp_out" "$run_tmp_escout"
   escape_colorcodes_tee "$run_tmp_err" "$run_tmp_escerr"
@@ -1009,7 +1057,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
     cp "$run_tmp_escout" "$relative_testpath.stdout" || echo -e "Failed replacing stdout with new file."
     cp "$run_tmp_escerr" "$relative_testpath.stderr" || echo -e "Failed replacing stderr with new file."
   } else {
-    echo -e "\033[1;33m[TEST]    Won't record, no [-b].\e[0m\n"
+    [[ $quiet_flag -eq 0 || $verbose_flag -gt 0 ]] && echo -e "\033[1;33m[TEST]    Won't record, no [-b].\e[0m\n"
   }
   fi
   rm -f "$run_tmp_out" || echo -e "\033[1;31m[ERROR]    Failed removing tmpfile ($run_tmp_out). Why?\e[0m\n"
@@ -1086,7 +1134,7 @@ if [[ $test_mode_flag -gt 0 ]]; then {
   [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;32m[TEST]    Removed tempfile "$run_tmp_escerr".\e[0m" >&2
   if [[ $build_flag -gt 0 ]] ; then {
     #We simulate success since we're recording
-    echo -e "\033[1;35m[TEST]    Phony pass (recording).\e[0m"
+    echo -e "\033[1;33m[TEST]    Phony pass (recording).\e[0m"
     [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m    (out: $out_res)\e[0m"
     [[ $verbose_flag -gt 0 ]] && echo -e "\033[0;33m    (err: $err_res)\e[0m"
     exit 0 #We return earlier
@@ -1225,9 +1273,9 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
     fi
     #Check compilation result
     if [[ $comp_res -eq 0 ]] ; then
-      echo -e "\n\033[1;32m[BUILD]    Done Building ( $version ) , took $runtime seconds, using ( $tool_txt ).\e[0m"
+      echo -e "\033[1;32m[BUILD]    Done Building ( $version ) , took $runtime seconds, using ( $tool_txt ).\e[0m"
     else
-      echo -e "\n\033[1;31m[ERROR]    Build for ( $version ) failed, quitting.\e[0m\n" >&2
+      echo -e "\033[1;31m[ERROR]    Build for ( $version ) failed, quitting.\e[0m\n" >&2
       exit 1
     fi
 
@@ -1235,7 +1283,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
   fi
 
 } elif [[ ! -z $version ]] ; then { #Binary was present, we notify if we were running with build flag
-  echo -e "\n\033[1;32m[QUERY]    ( $version ) binary is ready at ( $script_path ) .\e[0m" >&2
+  echo -e "\n\033[1;32m[QUERY]    ( $version ) binary is ready at ( $script_path ) .\e[0m\n" >&2
   [[ $build_flag -gt 0 ]] && echo -e "\033[0;33m[BUILD]    Found binary for ( $version ), won't build.\e[0m" >&2
 } elif [[ ! -z $query ]] ; then {
   echo -e "\033[1;31m[QUERY]    ( $query ) invalid query, run with -V to see more.\e[0m"
@@ -1293,9 +1341,9 @@ if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
     rm $(realpath "$scripts_dir"/"v$version/$exec_entrypoint") #2>/dev/null
     clean_res=$?
     if [[ $clean_res -eq 0 ]] ; then {
-      echo -e "\033[0;32m[DELETE]    Success on ( $version ).\e[0m" >&2
+      echo -e "\033[0;32m[DELETE]    Success on ( $version ).\e[0m"
     } else {
-      echo -e "\033[0;31m[DELETE]    Failure on ( $version ).\e[0m" >&2
+      echo -e "\033[0;31m[DELETE]    Failure on ( $version ).\e[0m"
     }
     fi
     exit "$clean_res"
@@ -1333,6 +1381,10 @@ if [[ purge_flag -gt 0 ]]; then
     [[ $base_mode_flag -gt 0 ]] && basem="B" #We make sure to pass on eventual base mode to the subcalls
     [[ $git_mode_flag -gt 0 ]] && gitm="g" #We make sure to pass on eventual git mode to the subcalls
     [[ $quiet_flag -gt 0 ]] && quietm="q" #We make sure to pass on eventual quiet flag mode to the subcalls
+    if [[ $quiet_flag -eq 0 ]] ; then {
+      echo -e "\033[1;35m[PURGE]    Running \"$prog_name -M $makefile_version -S $source_name -E $exec_entrypoint -D $scripts_dir -d$verb$gitm$basem$quietm $purge_vers 2>/dev/null\"\e[0m"
+    }
+    fi
     ( $prog_name -M "$makefile_version" -S "$source_name" -E "$exec_entrypoint" -D "$scripts_dir" -d"$verb""$gitm""$basem""$quietm" "$purge_vers" ) 2>/dev/null
     clean_res="$?"
 
