feat: 1.7.4 Extract sourcing to its own function (#55)

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -30,8 +30,8 @@ kernel_release="$(uname -r)"
 kernel_version="$(uname -v)"
 machine_name="$(uname -m)"
 os_name="$(uname -o)"
-amboso_currvers="1.7.3"
-expected_AMBOSO_API_LVL="1.7.3"
+amboso_currvers="1.7.4"
+expected_AMBOSO_API_LVL="1.7.4"
 amboso_testflag_version="1.7.2"
 export AMBOSO_LVL_REC="${AMBOSO_LVL_REC:-0}"
 # check recursion
@@ -66,6 +66,83 @@ function start_digraph() {
 }
 function end_digraph() {
   app "}"
+}
+
+#Function to try sourcing amboso_fn.sh
+source_amboso_api() {
+  if [[ $(basename "$(pwd)") == "amboso" ]] ; then {
+    amboso_fn_path="$(realpath "$(pwd)")/amboso_fn.sh"
+    if [[ -f $amboso_fn_path ]] ; then {
+      [[ $verbose_flag -gt 1 ]] && printf "\033[0;35m[PREP]    Running inside amboso dir. Sourcing: \"$amboso_fn_path\".\e[0m\n" >&2
+      source "$amboso_fn_path";
+      source_res="$?"
+      if [[ $source_res -ne 0 ]] ; then {
+        printf "\033[1;31m[PREP]    Failed loading amboso_fn.\n\n    Using file: \"$amboso_fn_path\".\e[0m\n" >&2
+        exit 3
+      }
+      fi
+    } else {
+      printf "\033[1;31m[ERROR]    Couldn't load amboso_fn, check your symlinks.\e[0m\n"
+      exit 2
+    }
+    fi
+  } else {
+    amboso_fn_path="$(realpath "$(pwd)")/amboso/amboso_fn.sh"
+    found_amboso_dir=0
+    [[ $verbose_flag -gt 1 ]] && printf "\033[0;33m[PREP]    Assuming we are running in super-repo. Sourcing: \"$amboso_fn_path\".\e[0m\n" >&2
+    [[ -d "$(realpath "$(pwd)")"/amboso ]] && found_amboso_dir=1
+    [[ $verbose_flag -gt 1 && $found_amboso_dir -gt 0 ]] && printf "\033[0;32m[PREP]    Found amboso dir.\e[0m\n" >&2
+    if [[ -f $amboso_fn_path ]] ; then {
+      [[ $verbose_flag -gt 1 ]] && printf "\033[0;35m[PREP]    Valid file at: \"$amboso_fn_path\".\e[0m\n" >&2
+      source "$amboso_fn_path";
+      source_res="$?"
+      [[ $source_res -ne 0 ]] && printf "\033[1;31m[PREP]    Failed loading amboso_fn.\n\n    Using file: \"$amboso_fn_path\".\e[0m\n" >&2
+    } else {
+      [[ $quiet_flag -eq 0 ]] && printf "\033[0;31m[WARN]    \"$amboso_fn_path\" was not a valid file. Not in valid super-repo.\e[0m\n" >&2
+      try_default=1
+    }
+    fi
+    if [[ $try_default -eq 1 && -f /usr/local/bin/amboso_fn.sh ]] ; then { #We only enter here if we failed sourcing
+      #We need one more error message to show me are missing functions because of an amboso directory with no file.
+      if [[ $found_amboso_dir -gt 0 ]] ; then {
+        printf "\033[1;31m[WARN]   Deprecated amboso dir (< 1.4.3) found, as it doesn't provide a function api marker.\e[0m\n\n" >&2
+        exit 3
+      }
+      fi
+      amboso_fn_path="/usr/local/bin/amboso_fn.sh"
+      [[ $quiet_flag -eq 0 ]] && printf "\033[0;35m[WARN]    Fallback to default path for amboso_fn. Sourcing: \"$amboso_fn_path\".\e[0m\n" >&2
+      source "$amboso_fn_path";
+      source_res="$?"
+      if [[ $source_res -ne 0 ]] ; then {
+        printf "\033[1;31m[PREP]    Failed loading amboso_fn. Quitting.\n\n    Using file: \"$amboso_fn_path\".\e[0m\n" >&2
+        exit 3
+      }
+      fi
+    }
+    fi
+  }
+  fi
+
+  if [[ $source_res -ne 0 ]] ; then {
+    printf "\033[1;31m[PANIC]    Failed sourcing amboso_fn. Expected path: \"$amboso_fn_path\".\e[0m\n"
+    exit 2
+  }
+  fi
+  [[ $verbose_flag -gt 1 ]] && printf "\033[0;32m[PREP]    Done loading functions.\e[0m\n" >&2
+  [[ $verbose_flag -gt 1 ]] && printf "\033[0;37m[PREP]    \"\$AMBOSO_API_LVL\" is: (\033[0;34m $AMBOSO_API_LVL \033[0;37m, expected { \033[1;33m$expected_AMBOSO_API_LVL\033[0;37m } ).\e[0m\n" >&2
+  [[ $tell_uname_flag -eq 1 ]] && print_sysinfo
+  if [[ $expected_AMBOSO_API_LVL > $AMBOSO_API_LVL ]] ; then {
+    printf "\033[1;31m[PANIC]    AMBOSO_API_LVL not supported. Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[1;31m } , { \033[1;33m$AMBOSO_API_LVL\033[1;31m } is too low.\n\n    Maybe check your \"amboso_fn.sh\" file.\n\e[0m\n"
+    printf "\033[1;31m[PANIC]    Couldn't load functions. Quitting.\e[0m\n"
+    exit 2
+  } elif [[ $AMBOSO_API_LVL > $expected_AMBOSO_API_LVL ]] ; then {
+    [[ $verbose_flag -gt 0 ]] && printf "\033[0;31m[WARN]    AMBOSO_API_LVL is greater than expected. Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[0;31m } , { \033[1;34m$AMBOSO_API_LVL\033[0;31m } is higher.\e[0m\n" >&2
+    [[ $verbose_flag -gt 0 ]] && printf "\n\033[1;31m[WARN]    Continuing run with unexpected AMBOSO_API_LVL: Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[1;31m } , { \033[1;34m$AMBOSO_API_LVL\033[1;31m } is higher.\e[0m\n"
+    #exit 2
+  } elif [[ $AMBOSO_API_LVL = "$expected_AMBOSO_API_LVL" ]] ; then {
+    [[ $verbose_flag -gt 0 ]] && printf "\033[0;32m[PREP]   Running with \"\$AMBOSO_API_LVL\" [ \033[1;35m$AMBOSO_API_LVL\033[0;32m ]; min is { \033[1;36m$expected_AMBOSO_API_LVL\033[0;32m }.\e[0m\n" >&2
+  }
+  fi
 }
 
 #Prepare flag values to default value
@@ -285,89 +362,9 @@ fi
 [[ $verbose_flag -gt 1 ]] && printf "\033[0;32m[PREP]    Done getopts.\e[0m\n" >&2
 [[ $verbose_flag -gt 0 && ! $prog_name = "anvil" ]] && printf "\033[1;36m[AMBOZO]\e[0m    Please, symlink me to \"anvil\".\n\n" >&2
 
-if [[ $(basename "$(pwd)") == "amboso" ]] ; then {
-  amboso_fn_path="$(realpath "$(pwd)")/amboso_fn.sh"
-  if [[ -f $amboso_fn_path ]] ; then {
-    [[ $verbose_flag -gt 1 ]] && printf "\033[0;35m[PREP]    Running inside amboso dir. Sourcing: \"$amboso_fn_path\".\e[0m\n" >&2
-    source "$amboso_fn_path";
-    source_res="$?"
-    if [[ $source_res -ne 0 ]] ; then {
-      printf "\033[1;31m[PREP]    Failed loading amboso_fn.\n\n    Using file: \"$amboso_fn_path\".\e[0m\n" >&2
-      echo_timer "$amboso_start_time"  "Failed load of amboso_fn" "1"
-      exit 3
-    }
-    fi
-  } else {
-    printf "\033[1;31m[ERROR]    Couldn't load amboso_fn, check your symlinks.\e[0m\n"
-    echo_timer "$amboso_start_time"  "Invalid path [$amboso_fn_path]" "1"
-    exit 2
-  }
-  fi
-} else {
-  amboso_fn_path="$(realpath "$(pwd)")/amboso/amboso_fn.sh"
-  found_amboso_dir=0
-  [[ $verbose_flag -gt 1 ]] && printf "\033[0;33m[PREP]    Assuming we are running in super-repo. Sourcing: \"$amboso_fn_path\".\e[0m\n" >&2
-  [[ -d "$(realpath "$(pwd)")"/amboso ]] && found_amboso_dir=1
-  [[ $verbose_flag -gt 1 && $found_amboso_dir -gt 0 ]] && printf "\033[0;32m[PREP]    Found amboso dir.\e[0m\n" >&2
-  if [[ -f $amboso_fn_path ]] ; then {
-    [[ $verbose_flag -gt 1 ]] && printf "\033[0;35m[PREP]    Valid file at: \"$amboso_fn_path\".\e[0m\n" >&2
-    source "$amboso_fn_path";
-    source_res="$?"
-    [[ $source_res -ne 0 ]] && printf "\033[1;31m[PREP]    Failed loading amboso_fn.\n\n    Using file: \"$amboso_fn_path\".\e[0m\n" >&2
-  } else {
-    [[ $quiet_flag -eq 0 ]] && printf "\033[0;31m[WARN]    \"$amboso_fn_path\" was not a valid file. Not in valid super-repo.\e[0m\n" >&2
-    try_default=1
-  }
-  fi
-  if [[ $try_default -eq 1 && -f /usr/local/bin/amboso_fn.sh ]] ; then { #We only enter here if we failed sourcing
-    #We need one more error message to show me are missing functions because of an amboso directory with no file.
-    if [[ $found_amboso_dir -gt 0 ]] ; then {
-      printf "\033[1;31m[WARN]   Deprecated amboso dir (< 1.4.3) found, as it doesn't provide a function api marker.\e[0m\n\n" >&2
-      echo_timer "$amboso_start_time"  "Deprecated amboso dir found" "5"
-      exit 3
-    }
-    fi
-    amboso_fn_path="/usr/local/bin/amboso_fn.sh"
-    [[ $quiet_flag -eq 0 ]] && printf "\033[0;35m[WARN]    Fallback to default path for amboso_fn. Sourcing: \"$amboso_fn_path\".\e[0m\n" >&2
-    source "$amboso_fn_path";
-    source_res="$?"
-    if [[ $source_res -ne 0 ]] ; then {
-      printf "\033[1;31m[PREP]    Failed loading amboso_fn. Quitting.\n\n    Using file: \"$amboso_fn_path\".\e[0m\n" >&2
-      echo_timer "$amboso_start_time"  "Failed loading amboso_fn.sh" "1"
-      exit 3
-    }
-    fi
-  }
-  fi
-}
-fi
+# Load functions from amboso_fn.sh
+source_amboso_api
 
-if [[ $source_res -ne 0 ]] ; then {
-  printf "\033[1;31m[PANIC]    Failed sourcing amboso_fn. Expected path: \"$amboso_fn_path\".\e[0m\n"
-  app "$(echo_node begin_node failed_sourcing_fn)"
-  app "$(echo_node failed_sourcing_fn end_node)"
-  end_digraph
-  echo_timer "$amboso_start_time"  "Failed loading amboso_fn.sh" "1"
-  exit 2
-}
-fi
-app "$(echo_node begin_node loaded_fn)"
-[[ $verbose_flag -gt 1 ]] && printf "\033[0;32m[PREP]    Done loading functions.\e[0m\n" >&2
-[[ $verbose_flag -gt 1 ]] && printf "\033[0;37m[PREP]    \"\$AMBOSO_API_LVL\" is: (\033[0;34m $AMBOSO_API_LVL \033[0;37m, expected { \033[1;33m$expected_AMBOSO_API_LVL\033[0;37m } ).\e[0m\n" >&2
-[[ $tell_uname_flag -eq 1 ]] && print_sysinfo
-if [[ $expected_AMBOSO_API_LVL > $AMBOSO_API_LVL ]] ; then {
-  printf "\033[1;31m[PANIC]    AMBOSO_API_LVL not supported. Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[1;31m } , { \033[1;33m$AMBOSO_API_LVL\033[1;31m } is too low.\n\n    Maybe check your \"amboso_fn.sh\" file.\n\e[0m\n"
-  printf "\033[1;31m[PANIC]    Couldn't load functions. Quitting.\e[0m\n"
-  echo_timer "$amboso_start_time"  "AMBOSO_API_LVL too low." "1"
-  exit 2
-} elif [[ $AMBOSO_API_LVL > $expected_AMBOSO_API_LVL ]] ; then {
-  [[ $verbose_flag -gt 1 ]] && printf "\033[0;31m[WARN]    AMBOSO_API_LVL is greater than expected. Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[0;31m } , { \033[1;34m$AMBOSO_API_LVL\033[0;31m } is higher.\e[0m\n" >&2
-  [[ $verbose_flag -gt 1 ]] && printf "\n\033[1;31m[WARN]    Continuing run with unexpected AMBOSO_API_LVL: Needed { \033[1;35m$expected_AMBOSO_API_LVL\033[1;31m } , { \033[1;34m$AMBOSO_API_LVL\033[1;31m } is higher.\e[0m\n"
-  #exit 2
-} elif [[ $AMBOSO_API_LVL = "$expected_AMBOSO_API_LVL" ]] ; then {
-  [[ $verbose_flag -gt 1 ]] && printf "\033[0;32m[PREP]   Running with \"\$AMBOSO_API_LVL\" [ \033[1;35m$AMBOSO_API_LVL\033[0;32m ]; min is { \033[1;36m$expected_AMBOSO_API_LVL\033[0;32m }.\e[0m\n" >&2
-}
-fi
 [[ $verbose_flag -gt 1 ]] && printf "\033[0;32m[PREP]    Printing active flags:\e[0m\n" >&2 && echo_active_flags >&2
 main_at=369
 #PROG_START_LINE
@@ -431,6 +428,7 @@ if [[ $be_stego_parser_flag -eq 1 ]] ; then {
         exit $?
     } else {
         bash_gulp_stego "$filepath" 0
+        [[ $? -eq 0 ]] && print_amboso_stego_scopes
         exit $?
     }
     fi
