fix: more SC20XX fixes

diff --git a/amboso b/amboso
--- a/amboso
+++ b/amboso
@@ -1203,7 +1203,7 @@ fi
 #We expect $scripts_dir to end with /
 version=""
 for i in $(seq 0 $(($tot_vers-1))); do
-  [[ $query = ${supported_versions[$i]} ]] && version="$query" && script_path=""$scripts_dir"v"$version""
+  [[ $query = "${supported_versions[$i]}" ]] && version="$query" && script_path="${scripts_dir}v${version}"
 done
 
 if [[ -z $version ]]; then {
@@ -1236,12 +1236,12 @@ if [[ $gen_C_headers_set -gt 0 && $gen_C_headers_flag -gt 0 ]]; then {
 fi
 
 has_makefile=0
-if [[ $version > $makefile_version || $version = $makefile_version ]] ; then
+if [[ $version > $makefile_version || $version = "$makefile_version" ]] ; then
   has_makefile=1
 fi
 
 can_automake=0
-if [[ $version > $use_autoconf_version || $version = $use_autoconf_version ]] ; then
+if [[ $version > $use_autoconf_version || $version = "$use_autoconf_version" ]] ; then
   can_automake=1
 fi
 
@@ -1292,7 +1292,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
       start_t=`date +%s.%N`
       if [[ $git_mode_flag -eq 0 && $base_mode_flag -eq 1 ]] ; then { #Building in base mode, we cd into target directory before make
         [[ $verbose_flag -gt 0 ]] && printf "\033[0;35m[BUILD]    Running in base mode, expecting full source in $script_path.\e[0m\n" #>&2
-        cd $script_path; make >&2
+        cd $script_path || { printf "\033[1;31m[CRITICAL]    cd failed. Quitting.\n"; exit 4 ; }; make >&2
         comp_res=$?
       } else { #Building in git mode, we checkout the tag and move the binary after the build
         [[ $verbose_flag -gt 0 ]] && printf "\033[0;34m[BUILD]    Running in git mode, checking out ( $version ).\e[0m\n" #>&2
@@ -1307,7 +1307,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
           comp_res=$?
           #Output is expected to be in the main dir:
           if [[ ! -e ./$exec_entrypoint ]] ; then {
-            printf "\033[1;31m[ERROR]    $exec_entrypoint not found at ($pwd).\e[0m\n" #>&2
+            printf "\033[1;31m[ERROR]    $exec_entrypoint not found at $(pwd).\e[0m\n" #>&2
           } else {
             mv "./$exec_entrypoint" "$script_path" #All files generated during the build should be ignored by the repo, to avoid conflict when checking out
             [[ $verbose_flag -gt 0 ]] && printf "\033[0;33m[BUILD]    Moved $exec_entrypoint to $script_path.\e[0m\n" #>&2
@@ -1329,7 +1329,7 @@ if [[ ! -f "$script_path/$exec_entrypoint" && ! -z $version ]] ; then {
       fi
       end_t=`date +%s.%N`
       runtime=$( printf "$end_t - $start_t\n" | bc -l )
-      cd "$curr_dir"
+      cd "$curr_dir" || { printf "\033[1;31m[CRITICAL]    cd failed. Quitting.\n"; exit 4; };
     } else { #Straight gcc mode
       [[ $verbose_flag -gt 0 ]] && printf "\033[0;33m[MODE]    target ( $version ) < ( $makefile_version ), single file build with gcc.\e[0m\n" >&2
       [[ $verbose_flag -gt 0 ]] && printf "\033[0;33m[BUILD]    Building ( $version ), using gcc call.\e[0m\n" >&2
@@ -1448,7 +1448,7 @@ if [[ ! -z $version && $run_flag -eq 1 && -x $script_path/$exec_entrypoint ]] ; 
   #echo -n "."
   #sleep 1
   #echo ""
-  ( cd "$script_path" ; ./"$exec_entrypoint" )
+  ( cd "$script_path" || { printf "\033[1;31m[CRITICAL]    cd failed. Quitting.\n"; exit 4 ;} ; ./"$exec_entrypoint" )
 } elif [[ ! -z $version && $run_flag -eq 0  ]] ; then {
   printf "\033[0;33m[DEBUG]    Running without -r flag, won't run.\e[0m\n" >&2
 } elif [[ -z $version && $run_flag -gt 0 ]] ; then {
@@ -1477,9 +1477,9 @@ if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
         printf "\033[1;31m[ERROR]    '$delete_path' is not a valid directory.\n    Check your supported versions for details on ( $version ).\e[0m\n\n" #>&2
       } elif [[ -x $scripts_dir/v$version/$exec_entrypoint ]] ; then { #Executable exists
         has_bin=1 && printf "\033[0;33m[DELETE]   ( $version ) has an executable.\e[0m\n\n" >&2
-        cd "$delete_path"; make clean 2>/dev/null #1>&2
+        cd "$delete_path" || { printf "\033[1;31m[CRITICAL]    cd failed. Quitting.\n"; exit 4 ;}; make clean 2>/dev/null #1>&2
         clean_res=$?
-        cd "$curr_dir"
+        cd "$curr_dir" || { printf "\033[1;31m[CRITICAL]    cd failed. Quitting.\n"; exit 4 ;};
         echo_timer "$amboso_start_time"  "Did delete, res was [$clean_res]" "3"
         exit "$clean_res"
       } else {
@@ -1498,7 +1498,7 @@ if [[ $delete_flag -gt 0 && $purge_flag -eq 0 ]] ; then {
       has_bin=1 && [[ $verbose_flag -gt 0 ]] && printf "\033[0;33m[DELETE]    ( $version ) has an executable.\e[0m\n" >&2
     }
     fi
-    rm $(realpath "$scripts_dir"/"v$version/$exec_entrypoint") #2>/dev/null
+    rm "$(realpath "$scripts_dir"/"v$version/$exec_entrypoint")" #2>/dev/null
     clean_res=$?
     if [[ $clean_res -eq 0 ]] ; then {
       printf "\033[0;32m[DELETE]    Success on ( $version ).\e[0m\n"
